-- ==============================================================
-- Generated by Dot2Vhdl ver. 0.21
-- File created: Wed Sep 16 14:13:03 2020

-- ==============================================================
library IEEE; 
use IEEE.std_logic_1164.all; 
use IEEE.numeric_std.all; 
use work.customTypes.all; 
-- ==============================================================
entity vecTrans2 is 
port (
	clk:  in std_logic;
	rst:  in std_logic;
	start_in:  in std_logic_vector (0 downto 0);
	start_valid:  in std_logic;
	start_ready:  out std_logic;
	end_out:  out std_logic_vector (0 downto 0);
	end_valid:  out std_logic;
	end_ready:  in std_logic;
	A_address0 : out std_logic_vector (31 downto 0);
	A_ce0 : out std_logic;
	A_we0 : out std_logic;
	A_dout0 : out std_logic_vector (31 downto 0);
	A_din0 : in std_logic_vector (31 downto 0);
	A_address1 : out std_logic_vector (31 downto 0);
	A_ce1 : out std_logic;
	A_we1 : out std_logic;
	A_dout1 : out std_logic_vector (31 downto 0);
	A_din1 : in std_logic_vector (31 downto 0);
	b_address0 : out std_logic_vector (31 downto 0);
	b_ce0 : out std_logic;
	b_we0 : out std_logic;
	b_dout0 : out std_logic_vector (31 downto 0);
	b_din0 : in std_logic_vector (31 downto 0);
	b_address1 : out std_logic_vector (31 downto 0);
	b_ce1 : out std_logic;
	b_we1 : out std_logic;
	b_dout1 : out std_logic_vector (31 downto 0);
	b_din1 : in std_logic_vector (31 downto 0));
end;

architecture behavioral of vecTrans2 is 

	signal brCst_block2_clk : std_logic;
	signal brCst_block2_rst : std_logic;
	signal brCst_block2_dataInArray_0 : std_logic_vector(0 downto 0);
	signal brCst_block2_pValidArray_0 : std_logic;
	signal brCst_block2_readyArray_0 : std_logic;
	signal brCst_block2_nReadyArray_0 : std_logic;
	signal brCst_block2_validArray_0 : std_logic;
	signal brCst_block2_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal cst_8_clk : std_logic;
	signal cst_8_rst : std_logic;
	signal cst_8_dataInArray_0 : std_logic_vector(31 downto 0);
	signal cst_8_pValidArray_0 : std_logic;
	signal cst_8_readyArray_0 : std_logic;
	signal cst_8_nReadyArray_0 : std_logic;
	signal cst_8_validArray_0 : std_logic;
	signal cst_8_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal branch_0_clk : std_logic;
	signal branch_0_rst : std_logic;
	signal branch_0_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_0_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branch_0_pValidArray_0 : std_logic;
	signal branch_0_pValidArray_1 : std_logic;
	signal branch_0_readyArray_0 : std_logic;
	signal branch_0_readyArray_1 : std_logic;
	signal branch_0_nReadyArray_0 : std_logic;
	signal branch_0_validArray_0 : std_logic;
	signal branch_0_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_0_nReadyArray_1 : std_logic;
	signal branch_0_validArray_1 : std_logic;
	signal branch_0_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal start_1_clk : std_logic;
	signal start_1_rst : std_logic;
	signal start_1_dataInArray_0 : std_logic_vector(0 downto 0);
	signal start_1_pValidArray_0 : std_logic;
	signal start_1_readyArray_0 : std_logic;
	signal start_1_nReadyArray_0 : std_logic;
	signal start_1_validArray_0 : std_logic;
	signal start_1_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal forkC_12_clk : std_logic;
	signal forkC_12_rst : std_logic;
	signal forkC_12_dataInArray_0 : std_logic_vector(0 downto 0);
	signal forkC_12_pValidArray_0 : std_logic;
	signal forkC_12_readyArray_0 : std_logic;
	signal forkC_12_nReadyArray_0 : std_logic;
	signal forkC_12_validArray_0 : std_logic;
	signal forkC_12_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal forkC_12_nReadyArray_1 : std_logic;
	signal forkC_12_validArray_1 : std_logic;
	signal forkC_12_dataOutArray_1 : std_logic_vector(0 downto 0);
	signal forkC_12_nReadyArray_2 : std_logic;
	signal forkC_12_validArray_2 : std_logic;
	signal forkC_12_dataOutArray_2 : std_logic_vector(0 downto 0);

	signal branchC_5_clk : std_logic;
	signal branchC_5_rst : std_logic;
	signal branchC_5_dataInArray_0 : std_logic_vector(0 downto 0);
	signal branchC_5_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branchC_5_pValidArray_0 : std_logic;
	signal branchC_5_pValidArray_1 : std_logic;
	signal branchC_5_readyArray_0 : std_logic;
	signal branchC_5_readyArray_1 : std_logic;
	signal branchC_5_nReadyArray_0 : std_logic;
	signal branchC_5_validArray_0 : std_logic;
	signal branchC_5_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal branchC_5_nReadyArray_1 : std_logic;
	signal branchC_5_validArray_1 : std_logic;
	signal branchC_5_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal fork_13_clk : std_logic;
	signal fork_13_rst : std_logic;
	signal fork_13_dataInArray_0 : std_logic_vector(0 downto 0);
	signal fork_13_pValidArray_0 : std_logic;
	signal fork_13_readyArray_0 : std_logic;
	signal fork_13_nReadyArray_0 : std_logic;
	signal fork_13_validArray_0 : std_logic;
	signal fork_13_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal fork_13_nReadyArray_1 : std_logic;
	signal fork_13_validArray_1 : std_logic;
	signal fork_13_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal Buffer_3_clk : std_logic;
	signal Buffer_3_rst : std_logic;
	signal Buffer_3_dataInArray_0 : std_logic_vector(31 downto 0);
	signal Buffer_3_pValidArray_0 : std_logic;
	signal Buffer_3_readyArray_0 : std_logic;
	signal Buffer_3_nReadyArray_0 : std_logic;
	signal Buffer_3_validArray_0 : std_logic;
	signal Buffer_3_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal Buffer_4_clk : std_logic;
	signal Buffer_4_rst : std_logic;
	signal Buffer_4_dataInArray_0 : std_logic_vector(0 downto 0);
	signal Buffer_4_pValidArray_0 : std_logic;
	signal Buffer_4_readyArray_0 : std_logic;
	signal Buffer_4_nReadyArray_0 : std_logic;
	signal Buffer_4_validArray_0 : std_logic;
	signal Buffer_4_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal phi_16_clk : std_logic;
	signal phi_16_rst : std_logic;
	signal phi_16_dataInArray_0 : std_logic_vector(0 downto 0);
	signal phi_16_dataInArray_1 : std_logic_vector(31 downto 0);
	signal phi_16_dataInArray_2 : std_logic_vector(31 downto 0);
	signal phi_16_pValidArray_0 : std_logic;
	signal phi_16_pValidArray_1 : std_logic;
	signal phi_16_pValidArray_2 : std_logic;
	signal phi_16_readyArray_0 : std_logic;
	signal phi_16_readyArray_1 : std_logic;
	signal phi_16_readyArray_2 : std_logic;
	signal phi_16_nReadyArray_0 : std_logic;
	signal phi_16_validArray_0 : std_logic;
	signal phi_16_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal load_19_clk : std_logic;
	signal load_19_rst : std_logic;
	signal load_19_dataInArray_0 : std_logic_vector(31 downto 0);
	signal load_19_dataInArray_1 : std_logic_vector(31 downto 0);
	signal load_19_pValidArray_0 : std_logic;
	signal load_19_pValidArray_1 : std_logic;
	signal load_19_readyArray_0 : std_logic;
	signal load_19_readyArray_1 : std_logic;
	signal load_19_nReadyArray_0 : std_logic;
	signal load_19_validArray_0 : std_logic;
	signal load_19_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal load_19_nReadyArray_1 : std_logic;
	signal load_19_validArray_1 : std_logic;
	signal load_19_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal cst_9_clk : std_logic;
	signal cst_9_rst : std_logic;
	signal cst_9_dataInArray_0 : std_logic_vector(31 downto 0);
	signal cst_9_pValidArray_0 : std_logic;
	signal cst_9_readyArray_0 : std_logic;
	signal cst_9_nReadyArray_0 : std_logic;
	signal cst_9_validArray_0 : std_logic;
	signal cst_9_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal icmp_20_clk : std_logic;
	signal icmp_20_rst : std_logic;
	signal icmp_20_dataInArray_0 : std_logic_vector(31 downto 0);
	signal icmp_20_dataInArray_1 : std_logic_vector(31 downto 0);
	signal icmp_20_pValidArray_0 : std_logic;
	signal icmp_20_pValidArray_1 : std_logic;
	signal icmp_20_readyArray_0 : std_logic;
	signal icmp_20_readyArray_1 : std_logic;
	signal icmp_20_nReadyArray_0 : std_logic;
	signal icmp_20_validArray_0 : std_logic;
	signal icmp_20_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal fork_3_clk : std_logic;
	signal fork_3_rst : std_logic;
	signal fork_3_dataInArray_0 : std_logic_vector(31 downto 0);
	signal fork_3_pValidArray_0 : std_logic;
	signal fork_3_readyArray_0 : std_logic;
	signal fork_3_nReadyArray_0 : std_logic;
	signal fork_3_validArray_0 : std_logic;
	signal fork_3_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal fork_3_nReadyArray_1 : std_logic;
	signal fork_3_validArray_1 : std_logic;
	signal fork_3_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal fork_4_clk : std_logic;
	signal fork_4_rst : std_logic;
	signal fork_4_dataInArray_0 : std_logic_vector(31 downto 0);
	signal fork_4_pValidArray_0 : std_logic;
	signal fork_4_readyArray_0 : std_logic;
	signal fork_4_nReadyArray_0 : std_logic;
	signal fork_4_validArray_0 : std_logic;
	signal fork_4_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal fork_4_nReadyArray_1 : std_logic;
	signal fork_4_validArray_1 : std_logic;
	signal fork_4_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal branch_1_clk : std_logic;
	signal branch_1_rst : std_logic;
	signal branch_1_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_1_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branch_1_pValidArray_0 : std_logic;
	signal branch_1_pValidArray_1 : std_logic;
	signal branch_1_readyArray_0 : std_logic;
	signal branch_1_readyArray_1 : std_logic;
	signal branch_1_nReadyArray_0 : std_logic;
	signal branch_1_validArray_0 : std_logic;
	signal branch_1_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_1_nReadyArray_1 : std_logic;
	signal branch_1_validArray_1 : std_logic;
	signal branch_1_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal branch_2_clk : std_logic;
	signal branch_2_rst : std_logic;
	signal branch_2_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_2_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branch_2_pValidArray_0 : std_logic;
	signal branch_2_pValidArray_1 : std_logic;
	signal branch_2_readyArray_0 : std_logic;
	signal branch_2_readyArray_1 : std_logic;
	signal branch_2_nReadyArray_0 : std_logic;
	signal branch_2_validArray_0 : std_logic;
	signal branch_2_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_2_nReadyArray_1 : std_logic;
	signal branch_2_validArray_1 : std_logic;
	signal branch_2_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal fork_8_clk : std_logic;
	signal fork_8_rst : std_logic;
	signal fork_8_dataInArray_0 : std_logic_vector(0 downto 0);
	signal fork_8_pValidArray_0 : std_logic;
	signal fork_8_readyArray_0 : std_logic;
	signal fork_8_nReadyArray_0 : std_logic;
	signal fork_8_validArray_0 : std_logic;
	signal fork_8_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal fork_8_nReadyArray_1 : std_logic;
	signal fork_8_validArray_1 : std_logic;
	signal fork_8_dataOutArray_1 : std_logic_vector(0 downto 0);
	signal fork_8_nReadyArray_2 : std_logic;
	signal fork_8_validArray_2 : std_logic;
	signal fork_8_dataOutArray_2 : std_logic_vector(0 downto 0);

	signal phiC_3_clk : std_logic;
	signal phiC_3_rst : std_logic;
	signal phiC_3_dataInArray_0 : std_logic_vector(0 downto 0);
	signal phiC_3_dataInArray_1 : std_logic_vector(0 downto 0);
	signal phiC_3_pValidArray_0 : std_logic;
	signal phiC_3_pValidArray_1 : std_logic;
	signal phiC_3_readyArray_0 : std_logic;
	signal phiC_3_readyArray_1 : std_logic;
	signal phiC_3_nReadyArray_0 : std_logic;
	signal phiC_3_validArray_0 : std_logic;
	signal phiC_3_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal phiC_3_nReadyArray_1 : std_logic;
	signal phiC_3_validArray_1 : std_logic;
	signal phiC_3_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal forkC_14_clk : std_logic;
	signal forkC_14_rst : std_logic;
	signal forkC_14_dataInArray_0 : std_logic_vector(0 downto 0);
	signal forkC_14_pValidArray_0 : std_logic;
	signal forkC_14_readyArray_0 : std_logic;
	signal forkC_14_nReadyArray_0 : std_logic;
	signal forkC_14_validArray_0 : std_logic;
	signal forkC_14_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal forkC_14_nReadyArray_1 : std_logic;
	signal forkC_14_validArray_1 : std_logic;
	signal forkC_14_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal branchC_6_clk : std_logic;
	signal branchC_6_rst : std_logic;
	signal branchC_6_dataInArray_0 : std_logic_vector(0 downto 0);
	signal branchC_6_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branchC_6_pValidArray_0 : std_logic;
	signal branchC_6_pValidArray_1 : std_logic;
	signal branchC_6_readyArray_0 : std_logic;
	signal branchC_6_readyArray_1 : std_logic;
	signal branchC_6_nReadyArray_0 : std_logic;
	signal branchC_6_validArray_0 : std_logic;
	signal branchC_6_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal branchC_6_nReadyArray_1 : std_logic;
	signal branchC_6_validArray_1 : std_logic;
	signal branchC_6_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal source_8_clk : std_logic;
	signal source_8_rst : std_logic;
	signal source_8_nReadyArray_0 : std_logic;
	signal source_8_validArray_0 : std_logic;
	signal source_8_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal Buffer_1_clk : std_logic;
	signal Buffer_1_rst : std_logic;
	signal Buffer_1_dataInArray_0 : std_logic_vector(31 downto 0);
	signal Buffer_1_pValidArray_0 : std_logic;
	signal Buffer_1_readyArray_0 : std_logic;
	signal Buffer_1_nReadyArray_0 : std_logic;
	signal Buffer_1_validArray_0 : std_logic;
	signal Buffer_1_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal Buffer_2_clk : std_logic;
	signal Buffer_2_rst : std_logic;
	signal Buffer_2_dataInArray_0 : std_logic_vector(31 downto 0);
	signal Buffer_2_pValidArray_0 : std_logic;
	signal Buffer_2_readyArray_0 : std_logic;
	signal Buffer_2_nReadyArray_0 : std_logic;
	signal Buffer_2_validArray_0 : std_logic;
	signal Buffer_2_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal Buffer_5_clk : std_logic;
	signal Buffer_5_rst : std_logic;
	signal Buffer_5_dataInArray_0 : std_logic_vector(0 downto 0);
	signal Buffer_5_pValidArray_0 : std_logic;
	signal Buffer_5_readyArray_0 : std_logic;
	signal Buffer_5_nReadyArray_0 : std_logic;
	signal Buffer_5_validArray_0 : std_logic;
	signal Buffer_5_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal call_0_clk : std_logic;
	signal call_0_rst : std_logic;
	signal call_0_dataInArray_0 : std_logic_vector(31 downto 0);
	signal call_0_pValidArray_0 : std_logic;
	signal call_0_readyArray_0 : std_logic;
	signal call_0_nReadyArray_0 : std_logic;
	signal call_0_validArray_0 : std_logic;
	signal call_0_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal load_24_clk : std_logic;
	signal load_24_rst : std_logic;
	signal load_24_dataInArray_0 : std_logic_vector(31 downto 0);
	signal load_24_dataInArray_1 : std_logic_vector(31 downto 0);
	signal load_24_pValidArray_0 : std_logic;
	signal load_24_pValidArray_1 : std_logic;
	signal load_24_readyArray_0 : std_logic;
	signal load_24_readyArray_1 : std_logic;
	signal load_24_nReadyArray_0 : std_logic;
	signal load_24_validArray_0 : std_logic;
	signal load_24_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal load_24_nReadyArray_1 : std_logic;
	signal load_24_validArray_1 : std_logic;
	signal load_24_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal store_0_clk : std_logic;
	signal store_0_rst : std_logic;
	signal store_0_dataInArray_0 : std_logic_vector(31 downto 0);
	signal store_0_dataInArray_1 : std_logic_vector(31 downto 0);
	signal store_0_pValidArray_0 : std_logic;
	signal store_0_pValidArray_1 : std_logic;
	signal store_0_readyArray_0 : std_logic;
	signal store_0_readyArray_1 : std_logic;
	signal store_0_nReadyArray_0 : std_logic;
	signal store_0_validArray_0 : std_logic;
	signal store_0_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal store_0_nReadyArray_1 : std_logic;
	signal store_0_validArray_1 : std_logic;
	signal store_0_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal brCst_block4_clk : std_logic;
	signal brCst_block4_rst : std_logic;
	signal brCst_block4_dataInArray_0 : std_logic_vector(0 downto 0);
	signal brCst_block4_pValidArray_0 : std_logic;
	signal brCst_block4_readyArray_0 : std_logic;
	signal brCst_block4_nReadyArray_0 : std_logic;
	signal brCst_block4_validArray_0 : std_logic;
	signal brCst_block4_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal phi_n1_clk : std_logic;
	signal phi_n1_rst : std_logic;
	signal phi_n1_dataInArray_0 : std_logic_vector(31 downto 0);
	signal phi_n1_pValidArray_0 : std_logic;
	signal phi_n1_readyArray_0 : std_logic;
	signal phi_n1_nReadyArray_0 : std_logic;
	signal phi_n1_validArray_0 : std_logic;
	signal phi_n1_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal phi_n2_clk : std_logic;
	signal phi_n2_rst : std_logic;
	signal phi_n2_dataInArray_0 : std_logic_vector(31 downto 0);
	signal phi_n2_pValidArray_0 : std_logic;
	signal phi_n2_readyArray_0 : std_logic;
	signal phi_n2_nReadyArray_0 : std_logic;
	signal phi_n2_validArray_0 : std_logic;
	signal phi_n2_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal fork_6_clk : std_logic;
	signal fork_6_rst : std_logic;
	signal fork_6_dataInArray_0 : std_logic_vector(31 downto 0);
	signal fork_6_pValidArray_0 : std_logic;
	signal fork_6_readyArray_0 : std_logic;
	signal fork_6_nReadyArray_0 : std_logic;
	signal fork_6_validArray_0 : std_logic;
	signal fork_6_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal fork_6_nReadyArray_1 : std_logic;
	signal fork_6_validArray_1 : std_logic;
	signal fork_6_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal branch_3_clk : std_logic;
	signal branch_3_rst : std_logic;
	signal branch_3_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_3_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branch_3_pValidArray_0 : std_logic;
	signal branch_3_pValidArray_1 : std_logic;
	signal branch_3_readyArray_0 : std_logic;
	signal branch_3_readyArray_1 : std_logic;
	signal branch_3_nReadyArray_0 : std_logic;
	signal branch_3_validArray_0 : std_logic;
	signal branch_3_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_3_nReadyArray_1 : std_logic;
	signal branch_3_validArray_1 : std_logic;
	signal branch_3_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal phiC_4_clk : std_logic;
	signal phiC_4_rst : std_logic;
	signal phiC_4_dataInArray_0 : std_logic_vector(0 downto 0);
	signal phiC_4_pValidArray_0 : std_logic;
	signal phiC_4_readyArray_0 : std_logic;
	signal phiC_4_nReadyArray_0 : std_logic;
	signal phiC_4_validArray_0 : std_logic;
	signal phiC_4_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal forkC_15_clk : std_logic;
	signal forkC_15_rst : std_logic;
	signal forkC_15_dataInArray_0 : std_logic_vector(0 downto 0);
	signal forkC_15_pValidArray_0 : std_logic;
	signal forkC_15_readyArray_0 : std_logic;
	signal forkC_15_nReadyArray_0 : std_logic;
	signal forkC_15_validArray_0 : std_logic;
	signal forkC_15_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal forkC_15_nReadyArray_1 : std_logic;
	signal forkC_15_validArray_1 : std_logic;
	signal forkC_15_dataOutArray_1 : std_logic_vector(0 downto 0);
	signal forkC_15_nReadyArray_2 : std_logic;
	signal forkC_15_validArray_2 : std_logic;
	signal forkC_15_dataOutArray_2 : std_logic_vector(0 downto 0);

	signal branchC_7_clk : std_logic;
	signal branchC_7_rst : std_logic;
	signal branchC_7_dataInArray_0 : std_logic_vector(0 downto 0);
	signal branchC_7_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branchC_7_pValidArray_0 : std_logic;
	signal branchC_7_pValidArray_1 : std_logic;
	signal branchC_7_readyArray_0 : std_logic;
	signal branchC_7_readyArray_1 : std_logic;
	signal branchC_7_nReadyArray_0 : std_logic;
	signal branchC_7_validArray_0 : std_logic;
	signal branchC_7_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal branchC_7_nReadyArray_1 : std_logic;
	signal branchC_7_validArray_1 : std_logic;
	signal branchC_7_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal fork_16_clk : std_logic;
	signal fork_16_rst : std_logic;
	signal fork_16_dataInArray_0 : std_logic_vector(0 downto 0);
	signal fork_16_pValidArray_0 : std_logic;
	signal fork_16_readyArray_0 : std_logic;
	signal fork_16_nReadyArray_0 : std_logic;
	signal fork_16_validArray_0 : std_logic;
	signal fork_16_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal fork_16_nReadyArray_1 : std_logic;
	signal fork_16_validArray_1 : std_logic;
	signal fork_16_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal Buffer_6_clk : std_logic;
	signal Buffer_6_rst : std_logic;
	signal Buffer_6_dataInArray_0 : std_logic_vector(0 downto 0);
	signal Buffer_6_pValidArray_0 : std_logic;
	signal Buffer_6_readyArray_0 : std_logic;
	signal Buffer_6_nReadyArray_0 : std_logic;
	signal Buffer_6_validArray_0 : std_logic;
	signal Buffer_6_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal cst_10_clk : std_logic;
	signal cst_10_rst : std_logic;
	signal cst_10_dataInArray_0 : std_logic_vector(31 downto 0);
	signal cst_10_pValidArray_0 : std_logic;
	signal cst_10_readyArray_0 : std_logic;
	signal cst_10_nReadyArray_0 : std_logic;
	signal cst_10_validArray_0 : std_logic;
	signal cst_10_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal add_28_clk : std_logic;
	signal add_28_rst : std_logic;
	signal add_28_dataInArray_0 : std_logic_vector(31 downto 0);
	signal add_28_dataInArray_1 : std_logic_vector(31 downto 0);
	signal add_28_pValidArray_0 : std_logic;
	signal add_28_pValidArray_1 : std_logic;
	signal add_28_readyArray_0 : std_logic;
	signal add_28_readyArray_1 : std_logic;
	signal add_28_nReadyArray_0 : std_logic;
	signal add_28_validArray_0 : std_logic;
	signal add_28_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal cst_11_clk : std_logic;
	signal cst_11_rst : std_logic;
	signal cst_11_dataInArray_0 : std_logic_vector(31 downto 0);
	signal cst_11_pValidArray_0 : std_logic;
	signal cst_11_readyArray_0 : std_logic;
	signal cst_11_nReadyArray_0 : std_logic;
	signal cst_11_validArray_0 : std_logic;
	signal cst_11_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal icmp_29_clk : std_logic;
	signal icmp_29_rst : std_logic;
	signal icmp_29_dataInArray_0 : std_logic_vector(31 downto 0);
	signal icmp_29_dataInArray_1 : std_logic_vector(31 downto 0);
	signal icmp_29_pValidArray_0 : std_logic;
	signal icmp_29_pValidArray_1 : std_logic;
	signal icmp_29_readyArray_0 : std_logic;
	signal icmp_29_readyArray_1 : std_logic;
	signal icmp_29_nReadyArray_0 : std_logic;
	signal icmp_29_validArray_0 : std_logic;
	signal icmp_29_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal phi_n0_clk : std_logic;
	signal phi_n0_rst : std_logic;
	signal phi_n0_dataInArray_0 : std_logic_vector(31 downto 0);
	signal phi_n0_dataInArray_1 : std_logic_vector(31 downto 0);
	signal phi_n0_pValidArray_0 : std_logic;
	signal phi_n0_pValidArray_1 : std_logic;
	signal phi_n0_readyArray_0 : std_logic;
	signal phi_n0_readyArray_1 : std_logic;
	signal phi_n0_nReadyArray_0 : std_logic;
	signal phi_n0_validArray_0 : std_logic;
	signal phi_n0_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal fork_5_clk : std_logic;
	signal fork_5_rst : std_logic;
	signal fork_5_dataInArray_0 : std_logic_vector(31 downto 0);
	signal fork_5_pValidArray_0 : std_logic;
	signal fork_5_readyArray_0 : std_logic;
	signal fork_5_nReadyArray_0 : std_logic;
	signal fork_5_validArray_0 : std_logic;
	signal fork_5_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal fork_5_nReadyArray_1 : std_logic;
	signal fork_5_validArray_1 : std_logic;
	signal fork_5_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal branch_4_clk : std_logic;
	signal branch_4_rst : std_logic;
	signal branch_4_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_4_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branch_4_pValidArray_0 : std_logic;
	signal branch_4_pValidArray_1 : std_logic;
	signal branch_4_readyArray_0 : std_logic;
	signal branch_4_readyArray_1 : std_logic;
	signal branch_4_nReadyArray_0 : std_logic;
	signal branch_4_validArray_0 : std_logic;
	signal branch_4_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_4_nReadyArray_1 : std_logic;
	signal branch_4_validArray_1 : std_logic;
	signal branch_4_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal phiC_5_clk : std_logic;
	signal phiC_5_rst : std_logic;
	signal phiC_5_dataInArray_0 : std_logic_vector(0 downto 0);
	signal phiC_5_dataInArray_1 : std_logic_vector(0 downto 0);
	signal phiC_5_pValidArray_0 : std_logic;
	signal phiC_5_pValidArray_1 : std_logic;
	signal phiC_5_readyArray_0 : std_logic;
	signal phiC_5_readyArray_1 : std_logic;
	signal phiC_5_nReadyArray_0 : std_logic;
	signal phiC_5_validArray_0 : std_logic;
	signal phiC_5_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal branchC_8_clk : std_logic;
	signal branchC_8_rst : std_logic;
	signal branchC_8_dataInArray_0 : std_logic_vector(0 downto 0);
	signal branchC_8_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branchC_8_pValidArray_0 : std_logic;
	signal branchC_8_pValidArray_1 : std_logic;
	signal branchC_8_readyArray_0 : std_logic;
	signal branchC_8_readyArray_1 : std_logic;
	signal branchC_8_nReadyArray_0 : std_logic;
	signal branchC_8_validArray_0 : std_logic;
	signal branchC_8_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal branchC_8_nReadyArray_1 : std_logic;
	signal branchC_8_validArray_1 : std_logic;
	signal branchC_8_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal fork_18_clk : std_logic;
	signal fork_18_rst : std_logic;
	signal fork_18_dataInArray_0 : std_logic_vector(0 downto 0);
	signal fork_18_pValidArray_0 : std_logic;
	signal fork_18_readyArray_0 : std_logic;
	signal fork_18_nReadyArray_0 : std_logic;
	signal fork_18_validArray_0 : std_logic;
	signal fork_18_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal fork_18_nReadyArray_1 : std_logic;
	signal fork_18_validArray_1 : std_logic;
	signal fork_18_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal source_9_clk : std_logic;
	signal source_9_rst : std_logic;
	signal source_9_nReadyArray_0 : std_logic;
	signal source_9_validArray_0 : std_logic;
	signal source_9_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal source_10_clk : std_logic;
	signal source_10_rst : std_logic;
	signal source_10_nReadyArray_0 : std_logic;
	signal source_10_validArray_0 : std_logic;
	signal source_10_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal Buffer_7_clk : std_logic;
	signal Buffer_7_rst : std_logic;
	signal Buffer_7_dataInArray_0 : std_logic_vector(0 downto 0);
	signal Buffer_7_pValidArray_0 : std_logic;
	signal Buffer_7_readyArray_0 : std_logic;
	signal Buffer_7_nReadyArray_0 : std_logic;
	signal Buffer_7_validArray_0 : std_logic;
	signal Buffer_7_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal ret_1_clk : std_logic;
	signal ret_1_rst : std_logic;
	signal ret_1_dataInArray_0 : std_logic_vector(0 downto 0);
	signal ret_1_pValidArray_0 : std_logic;
	signal ret_1_readyArray_0 : std_logic;
	signal ret_1_nReadyArray_0 : std_logic;
	signal ret_1_validArray_0 : std_logic;
	signal ret_1_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal phiC_6_clk : std_logic;
	signal phiC_6_rst : std_logic;
	signal phiC_6_dataInArray_0 : std_logic_vector(0 downto 0);
	signal phiC_6_pValidArray_0 : std_logic;
	signal phiC_6_readyArray_0 : std_logic;
	signal phiC_6_nReadyArray_0 : std_logic;
	signal phiC_6_validArray_0 : std_logic;
	signal phiC_6_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal LSQ_A_clk : std_logic;
	signal LSQ_A_rst : std_logic;
	signal LSQ_A_dataInArray_0 : std_logic_vector(0 downto 0);
	signal LSQ_A_dataInArray_1 : std_logic_vector(0 downto 0);
	signal LSQ_A_dataInArray_2 : std_logic_vector(31 downto 0);
	signal LSQ_A_dataInArray_3 : std_logic_vector(31 downto 0);
	signal LSQ_A_dataInArray_4 : std_logic_vector(31 downto 0);
	signal LSQ_A_pValidArray_0 : std_logic;
	signal LSQ_A_pValidArray_1 : std_logic;
	signal LSQ_A_pValidArray_2 : std_logic;
	signal LSQ_A_pValidArray_3 : std_logic;
	signal LSQ_A_pValidArray_4 : std_logic;
	signal LSQ_A_readyArray_0 : std_logic;
	signal LSQ_A_readyArray_1 : std_logic;
	signal LSQ_A_readyArray_2 : std_logic;
	signal LSQ_A_readyArray_3 : std_logic;
	signal LSQ_A_readyArray_4 : std_logic;
	signal LSQ_A_nReadyArray_0 : std_logic;
	signal LSQ_A_validArray_0 : std_logic;
	signal LSQ_A_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal LSQ_A_nReadyArray_1 : std_logic;
	signal LSQ_A_validArray_1 : std_logic;
	signal LSQ_A_dataOutArray_1 : std_logic_vector(0 downto 0);
	signal LSQ_A_io_queueEmpty : std_logic;
	signal LSQ_A_we0_ce0 : std_logic;
	signal LSQ_A_address0 : std_logic_vector (31 downto 0);
	signal LSQ_A_ce0 : std_logic;
	signal LSQ_A_we0 : std_logic;
	signal LSQ_A_dout0 : std_logic_vector (31 downto 0);
	signal LSQ_A_din0 : std_logic_vector (31 downto 0);
	signal LSQ_A_address1 : std_logic_vector (31 downto 0);
	signal LSQ_A_ce1 : std_logic;
	signal LSQ_A_we1 : std_logic;
	signal LSQ_A_dout1 : std_logic_vector (31 downto 0);
	signal LSQ_A_din1 : std_logic_vector (31 downto 0);
	signal LSQ_A_load_ready : std_logic;
	signal LSQ_A_store_ready : std_logic;

	signal MC_b_clk : std_logic;
	signal MC_b_rst : std_logic;
	signal MC_b_dataInArray_0 : std_logic_vector(31 downto 0);
	signal MC_b_dataInArray_1 : std_logic_vector(31 downto 0);
	signal MC_b_dataInArray_2 : std_logic_vector(31 downto 0);
	signal MC_b_dataInArray_3 : std_logic_vector(31 downto 0);
	signal MC_b_pValidArray_0 : std_logic;
	signal MC_b_pValidArray_1 : std_logic;
	signal MC_b_pValidArray_2 : std_logic;
	signal MC_b_pValidArray_3 : std_logic;
	signal MC_b_readyArray_0 : std_logic;
	signal MC_b_readyArray_1 : std_logic;
	signal MC_b_readyArray_2 : std_logic;
	signal MC_b_readyArray_3 : std_logic;
	signal MC_b_nReadyArray_0 : std_logic;
	signal MC_b_validArray_0 : std_logic;
	signal MC_b_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal MC_b_nReadyArray_1 : std_logic;
	signal MC_b_validArray_1 : std_logic;
	signal MC_b_dataOutArray_1 : std_logic_vector(0 downto 0);
	signal MC_b_we0_ce0 : std_logic;

	signal end_0_clk : std_logic;
	signal end_0_rst : std_logic;
	signal end_0_dataInArray_0 : std_logic_vector(0 downto 0);
	signal end_0_dataInArray_1 : std_logic_vector(0 downto 0);
	signal end_0_dataInArray_2 : std_logic_vector(0 downto 0);
	signal end_0_pValidArray_0 : std_logic;
	signal end_0_pValidArray_1 : std_logic;
	signal end_0_pValidArray_2 : std_logic;
	signal end_0_readyArray_0 : std_logic;
	signal end_0_readyArray_1 : std_logic;
	signal end_0_readyArray_2 : std_logic;
	signal end_0_nReadyArray_0 : std_logic;
	signal end_0_validArray_0 : std_logic;
	signal end_0_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal end_0_validArray_1 :  std_logic;
	signal end_0_dataOutArray_1 :  std_logic_vector (31 downto 0);
	signal end_0_nReadyArray_1 :  std_logic;

	signal sink_1_clk : std_logic;
	signal sink_1_rst : std_logic;
	signal sink_1_dataInArray_0 : std_logic_vector(31 downto 0);
	signal sink_1_pValidArray_0 : std_logic;
	signal sink_1_readyArray_0 : std_logic;

	signal sink_2_clk : std_logic;
	signal sink_2_rst : std_logic;
	signal sink_2_dataInArray_0 : std_logic_vector(31 downto 0);
	signal sink_2_pValidArray_0 : std_logic;
	signal sink_2_readyArray_0 : std_logic;

	signal sink_3_clk : std_logic;
	signal sink_3_rst : std_logic;
	signal sink_3_dataInArray_0 : std_logic_vector(31 downto 0);
	signal sink_3_pValidArray_0 : std_logic;
	signal sink_3_readyArray_0 : std_logic;

	signal sink_4_clk : std_logic;
	signal sink_4_rst : std_logic;
	signal sink_4_dataInArray_0 : std_logic_vector(31 downto 0);
	signal sink_4_pValidArray_0 : std_logic;
	signal sink_4_readyArray_0 : std_logic;

	signal sink_5_clk : std_logic;
	signal sink_5_rst : std_logic;
	signal sink_5_dataInArray_0 : std_logic_vector(0 downto 0);
	signal sink_5_pValidArray_0 : std_logic;
	signal sink_5_readyArray_0 : std_logic;

	signal sink_6_clk : std_logic;
	signal sink_6_rst : std_logic;
	signal sink_6_dataInArray_0 : std_logic_vector(0 downto 0);
	signal sink_6_pValidArray_0 : std_logic;
	signal sink_6_readyArray_0 : std_logic;

begin


	brCst_block2_clk <= clk;
	brCst_block2_rst <= rst;
	fork_13_pValidArray_0 <= brCst_block2_validArray_0;
	brCst_block2_nReadyArray_0 <= fork_13_readyArray_0;
	fork_13_dataInArray_0 <= std_logic_vector (resize(unsigned(brCst_block2_dataOutArray_0),fork_13_dataInArray_0'length));

	cst_8_clk <= clk;
	cst_8_rst <= rst;
	branch_0_pValidArray_0 <= cst_8_validArray_0;
	cst_8_nReadyArray_0 <= branch_0_readyArray_0;
	branch_0_dataInArray_0 <= std_logic_vector (resize(unsigned(cst_8_dataOutArray_0),branch_0_dataInArray_0'length));

	branch_0_clk <= clk;
	branch_0_rst <= rst;
	Buffer_3_pValidArray_0 <= branch_0_validArray_0;
	branch_0_nReadyArray_0 <= Buffer_3_readyArray_0;
	Buffer_3_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_0_dataOutArray_0),Buffer_3_dataInArray_0'length));
	sink_1_pValidArray_0 <= branch_0_validArray_1;
	branch_0_nReadyArray_1 <= sink_1_readyArray_0;
	sink_1_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_0_dataOutArray_1),sink_1_dataInArray_0'length));

	start_1_clk <= clk;
	start_1_rst <= rst;
	start_1_pValidArray_0 <= start_valid;
	start_ready <= start_1_readyArray_0;
	forkC_12_pValidArray_0 <= start_1_validArray_0;
	start_1_nReadyArray_0 <= forkC_12_readyArray_0;
	forkC_12_dataInArray_0 <= std_logic_vector (resize(unsigned(start_1_dataOutArray_0),forkC_12_dataInArray_0'length));

	forkC_12_clk <= clk;
	forkC_12_rst <= rst;
	cst_8_pValidArray_0 <= forkC_12_validArray_0;
	forkC_12_nReadyArray_0 <= cst_8_readyArray_0;
	cst_8_dataInArray_0 <= "00000000000000000000000000000000";
	branchC_5_pValidArray_0 <= forkC_12_validArray_1;
	forkC_12_nReadyArray_1 <= branchC_5_readyArray_0;
	branchC_5_dataInArray_0 <= std_logic_vector (resize(unsigned(forkC_12_dataOutArray_1),branchC_5_dataInArray_0'length));
	brCst_block2_pValidArray_0 <= forkC_12_validArray_2;
	forkC_12_nReadyArray_2 <= brCst_block2_readyArray_0;
	brCst_block2_dataInArray_0 <= "1";

	branchC_5_clk <= clk;
	branchC_5_rst <= rst;
	Buffer_4_pValidArray_0 <= branchC_5_validArray_0;
	branchC_5_nReadyArray_0 <= Buffer_4_readyArray_0;
	Buffer_4_dataInArray_0 <= std_logic_vector (resize(unsigned(branchC_5_dataOutArray_0),Buffer_4_dataInArray_0'length));
	sink_5_pValidArray_0 <= branchC_5_validArray_1;
	branchC_5_nReadyArray_1 <= sink_5_readyArray_0;
	sink_5_dataInArray_0 <= std_logic_vector (resize(unsigned(branchC_5_dataOutArray_1),sink_5_dataInArray_0'length));

	fork_13_clk <= clk;
	fork_13_rst <= rst;
	branch_0_pValidArray_1 <= fork_13_validArray_0;
	fork_13_nReadyArray_0 <= branch_0_readyArray_1;
	branch_0_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_13_dataOutArray_0),branch_0_dataInArray_1'length));
	branchC_5_pValidArray_1 <= fork_13_validArray_1;
	fork_13_nReadyArray_1 <= branchC_5_readyArray_1;
	branchC_5_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_13_dataOutArray_1),branchC_5_dataInArray_1'length));

	Buffer_3_clk <= clk;
	Buffer_3_rst <= rst;
	phi_16_pValidArray_1 <= Buffer_3_validArray_0;
	Buffer_3_nReadyArray_0 <= phi_16_readyArray_1;
	phi_16_dataInArray_1 <= std_logic_vector (resize(unsigned(Buffer_3_dataOutArray_0),phi_16_dataInArray_1'length));

	Buffer_4_clk <= clk;
	Buffer_4_rst <= rst;
	phiC_3_pValidArray_0 <= Buffer_4_validArray_0;
	Buffer_4_nReadyArray_0 <= phiC_3_readyArray_0;
	phiC_3_dataInArray_0 <= std_logic_vector (resize(unsigned(Buffer_4_dataOutArray_0),phiC_3_dataInArray_0'length));

	phi_16_clk <= clk;
	phi_16_rst <= rst;
	Buffer_1_pValidArray_0 <= phi_16_validArray_0;
	phi_16_nReadyArray_0 <= Buffer_1_readyArray_0;
	Buffer_1_dataInArray_0 <= std_logic_vector (resize(unsigned(phi_16_dataOutArray_0),Buffer_1_dataInArray_0'length));

	load_19_clk <= clk;
	load_19_rst <= rst;
	fork_4_pValidArray_0 <= load_19_validArray_0;
	load_19_nReadyArray_0 <= fork_4_readyArray_0;
	fork_4_dataInArray_0 <= std_logic_vector (resize(unsigned(load_19_dataOutArray_0),fork_4_dataInArray_0'length));
	LSQ_A_pValidArray_2 <= load_19_validArray_1;
	load_19_nReadyArray_1 <= LSQ_A_readyArray_2;
	LSQ_A_dataInArray_2 <= std_logic_vector (resize(unsigned(load_19_dataOutArray_1),LSQ_A_dataInArray_2'length));

	cst_9_clk <= clk;
	cst_9_rst <= rst;
	icmp_20_pValidArray_1 <= cst_9_validArray_0;
	cst_9_nReadyArray_0 <= icmp_20_readyArray_1;
	icmp_20_dataInArray_1 <= std_logic_vector (resize(unsigned(cst_9_dataOutArray_0),icmp_20_dataInArray_1'length));

	icmp_20_clk <= clk;
	icmp_20_rst <= rst;
	fork_8_pValidArray_0 <= icmp_20_validArray_0;
	icmp_20_nReadyArray_0 <= fork_8_readyArray_0;
	fork_8_dataInArray_0 <= std_logic_vector (resize(unsigned(icmp_20_dataOutArray_0),fork_8_dataInArray_0'length));

	fork_3_clk <= clk;
	fork_3_rst <= rst;
	load_19_pValidArray_1 <= fork_3_validArray_0;
	fork_3_nReadyArray_0 <= load_19_readyArray_1;
	load_19_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_3_dataOutArray_0),load_19_dataInArray_1'length));
	Buffer_2_pValidArray_0 <= fork_3_validArray_1;
	fork_3_nReadyArray_1 <= Buffer_2_readyArray_0;
	Buffer_2_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_3_dataOutArray_1),Buffer_2_dataInArray_0'length));

	fork_4_clk <= clk;
	fork_4_rst <= rst;
	icmp_20_pValidArray_0 <= fork_4_validArray_0;
	fork_4_nReadyArray_0 <= icmp_20_readyArray_0;
	icmp_20_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_4_dataOutArray_0),icmp_20_dataInArray_0'length));
	branch_2_pValidArray_0 <= fork_4_validArray_1;
	fork_4_nReadyArray_1 <= branch_2_readyArray_0;
	branch_2_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_4_dataOutArray_1),branch_2_dataInArray_0'length));

	branch_1_clk <= clk;
	branch_1_rst <= rst;
	phi_n2_pValidArray_0 <= branch_1_validArray_0;
	branch_1_nReadyArray_0 <= phi_n2_readyArray_0;
	phi_n2_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_1_dataOutArray_0),phi_n2_dataInArray_0'length));
	phi_n0_pValidArray_0 <= branch_1_validArray_1;
	branch_1_nReadyArray_1 <= phi_n0_readyArray_0;
	phi_n0_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_1_dataOutArray_1),phi_n0_dataInArray_0'length));

	branch_2_clk <= clk;
	branch_2_rst <= rst;
	phi_n1_pValidArray_0 <= branch_2_validArray_0;
	branch_2_nReadyArray_0 <= phi_n1_readyArray_0;
	phi_n1_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_2_dataOutArray_0),phi_n1_dataInArray_0'length));
	sink_2_pValidArray_0 <= branch_2_validArray_1;
	branch_2_nReadyArray_1 <= sink_2_readyArray_0;
	sink_2_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_2_dataOutArray_1),sink_2_dataInArray_0'length));

	fork_8_clk <= clk;
	fork_8_rst <= rst;
	branch_2_pValidArray_1 <= fork_8_validArray_0;
	fork_8_nReadyArray_0 <= branch_2_readyArray_1;
	branch_2_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_8_dataOutArray_0),branch_2_dataInArray_1'length));
	branch_1_pValidArray_1 <= fork_8_validArray_1;
	fork_8_nReadyArray_1 <= branch_1_readyArray_1;
	branch_1_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_8_dataOutArray_1),branch_1_dataInArray_1'length));
	branchC_6_pValidArray_1 <= fork_8_validArray_2;
	fork_8_nReadyArray_2 <= branchC_6_readyArray_1;
	branchC_6_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_8_dataOutArray_2),branchC_6_dataInArray_1'length));

	phiC_3_clk <= clk;
	phiC_3_rst <= rst;
	forkC_14_pValidArray_0 <= phiC_3_validArray_0;
	phiC_3_nReadyArray_0 <= forkC_14_readyArray_0;
	forkC_14_dataInArray_0 <= std_logic_vector (resize(unsigned(phiC_3_dataOutArray_0),forkC_14_dataInArray_0'length));
	phi_16_pValidArray_0 <= phiC_3_validArray_1;
	phiC_3_nReadyArray_1 <= phi_16_readyArray_0;
	phi_16_dataInArray_0 <= std_logic_vector (resize(unsigned(phiC_3_dataOutArray_1),phi_16_dataInArray_0'length));

	forkC_14_clk <= clk;
	forkC_14_rst <= rst;
	LSQ_A_pValidArray_0 <= forkC_14_validArray_0;
	forkC_14_nReadyArray_0 <= LSQ_A_readyArray_0;
	LSQ_A_dataInArray_0 <= std_logic_vector (resize(unsigned(forkC_14_dataOutArray_0),LSQ_A_dataInArray_0'length));
	Buffer_5_pValidArray_0 <= forkC_14_validArray_1;
	forkC_14_nReadyArray_1 <= Buffer_5_readyArray_0;
	Buffer_5_dataInArray_0 <= std_logic_vector (resize(unsigned(forkC_14_dataOutArray_1),Buffer_5_dataInArray_0'length));

	branchC_6_clk <= clk;
	branchC_6_rst <= rst;
	phiC_4_pValidArray_0 <= branchC_6_validArray_0;
	branchC_6_nReadyArray_0 <= phiC_4_readyArray_0;
	phiC_4_dataInArray_0 <= std_logic_vector (resize(unsigned(branchC_6_dataOutArray_0),phiC_4_dataInArray_0'length));
	phiC_5_pValidArray_0 <= branchC_6_validArray_1;
	branchC_6_nReadyArray_1 <= phiC_5_readyArray_0;
	phiC_5_dataInArray_0 <= std_logic_vector (resize(unsigned(branchC_6_dataOutArray_1),phiC_5_dataInArray_0'length));

	source_8_clk <= clk;
	source_8_rst <= rst;
	cst_9_pValidArray_0 <= source_8_validArray_0;
	source_8_nReadyArray_0 <= cst_9_readyArray_0;
	cst_9_dataInArray_0 <= "00000000000000000000000000000000";

	Buffer_1_clk <= clk;
	Buffer_1_rst <= rst;
	fork_3_pValidArray_0 <= Buffer_1_validArray_0;
	Buffer_1_nReadyArray_0 <= fork_3_readyArray_0;
	fork_3_dataInArray_0 <= std_logic_vector (resize(unsigned(Buffer_1_dataOutArray_0),fork_3_dataInArray_0'length));

	Buffer_2_clk <= clk;
	Buffer_2_rst <= rst;
	branch_1_pValidArray_0 <= Buffer_2_validArray_0;
	Buffer_2_nReadyArray_0 <= branch_1_readyArray_0;
	branch_1_dataInArray_0 <= std_logic_vector (resize(unsigned(Buffer_2_dataOutArray_0),branch_1_dataInArray_0'length));

	Buffer_5_clk <= clk;
	Buffer_5_rst <= rst;
	branchC_6_pValidArray_0 <= Buffer_5_validArray_0;
	Buffer_5_nReadyArray_0 <= branchC_6_readyArray_0;
	branchC_6_dataInArray_0 <= std_logic_vector (resize(unsigned(Buffer_5_dataOutArray_0),branchC_6_dataInArray_0'length));

	call_0_clk <= clk;
	call_0_rst <= rst;
	store_0_pValidArray_0 <= call_0_validArray_0;
	call_0_nReadyArray_0 <= store_0_readyArray_0;
	store_0_dataInArray_0 <= std_logic_vector (resize(unsigned(call_0_dataOutArray_0),store_0_dataInArray_0'length));

	load_24_clk <= clk;
	load_24_rst <= rst;
	store_0_pValidArray_1 <= load_24_validArray_0;
	load_24_nReadyArray_0 <= store_0_readyArray_1;
	store_0_dataInArray_1 <= std_logic_vector (resize(unsigned(load_24_dataOutArray_0),store_0_dataInArray_1'length));
	MC_b_pValidArray_0 <= load_24_validArray_1;
	load_24_nReadyArray_1 <= MC_b_readyArray_0;
	MC_b_dataInArray_0 <= std_logic_vector (resize(unsigned(load_24_dataOutArray_1),MC_b_dataInArray_0'length));

	store_0_clk <= clk;
	store_0_rst <= rst;
	LSQ_A_pValidArray_4 <= store_0_validArray_0;
	store_0_nReadyArray_0 <= LSQ_A_readyArray_4;
	LSQ_A_dataInArray_4 <= std_logic_vector (resize(unsigned(store_0_dataOutArray_0),LSQ_A_dataInArray_4'length));
	LSQ_A_pValidArray_3 <= store_0_validArray_1;
	store_0_nReadyArray_1 <= LSQ_A_readyArray_3;
	LSQ_A_dataInArray_3 <= std_logic_vector (resize(unsigned(store_0_dataOutArray_1),LSQ_A_dataInArray_3'length));

	brCst_block4_clk <= clk;
	brCst_block4_rst <= rst;
	fork_16_pValidArray_0 <= brCst_block4_validArray_0;
	brCst_block4_nReadyArray_0 <= fork_16_readyArray_0;
	fork_16_dataInArray_0 <= std_logic_vector (resize(unsigned(brCst_block4_dataOutArray_0),fork_16_dataInArray_0'length));

	phi_n1_clk <= clk;
	phi_n1_rst <= rst;
	call_0_pValidArray_0 <= phi_n1_validArray_0;
	phi_n1_nReadyArray_0 <= call_0_readyArray_0;
	call_0_dataInArray_0 <= std_logic_vector (resize(unsigned(phi_n1_dataOutArray_0),call_0_dataInArray_0'length));

	phi_n2_clk <= clk;
	phi_n2_rst <= rst;
	fork_6_pValidArray_0 <= phi_n2_validArray_0;
	phi_n2_nReadyArray_0 <= fork_6_readyArray_0;
	fork_6_dataInArray_0 <= std_logic_vector (resize(unsigned(phi_n2_dataOutArray_0),fork_6_dataInArray_0'length));

	fork_6_clk <= clk;
	fork_6_rst <= rst;
	load_24_pValidArray_1 <= fork_6_validArray_0;
	fork_6_nReadyArray_0 <= load_24_readyArray_1;
	load_24_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_6_dataOutArray_0),load_24_dataInArray_1'length));
	branch_3_pValidArray_0 <= fork_6_validArray_1;
	fork_6_nReadyArray_1 <= branch_3_readyArray_0;
	branch_3_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_6_dataOutArray_1),branch_3_dataInArray_0'length));

	branch_3_clk <= clk;
	branch_3_rst <= rst;
	phi_n0_pValidArray_1 <= branch_3_validArray_0;
	branch_3_nReadyArray_0 <= phi_n0_readyArray_1;
	phi_n0_dataInArray_1 <= std_logic_vector (resize(unsigned(branch_3_dataOutArray_0),phi_n0_dataInArray_1'length));
	sink_3_pValidArray_0 <= branch_3_validArray_1;
	branch_3_nReadyArray_1 <= sink_3_readyArray_0;
	sink_3_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_3_dataOutArray_1),sink_3_dataInArray_0'length));

	phiC_4_clk <= clk;
	phiC_4_rst <= rst;
	forkC_15_pValidArray_0 <= phiC_4_validArray_0;
	phiC_4_nReadyArray_0 <= forkC_15_readyArray_0;
	forkC_15_dataInArray_0 <= std_logic_vector (resize(unsigned(phiC_4_dataOutArray_0),forkC_15_dataInArray_0'length));

	forkC_15_clk <= clk;
	forkC_15_rst <= rst;
	LSQ_A_pValidArray_1 <= forkC_15_validArray_0;
	forkC_15_nReadyArray_0 <= LSQ_A_readyArray_1;
	LSQ_A_dataInArray_1 <= std_logic_vector (resize(unsigned(forkC_15_dataOutArray_0),LSQ_A_dataInArray_1'length));
	Buffer_6_pValidArray_0 <= forkC_15_validArray_1;
	forkC_15_nReadyArray_1 <= Buffer_6_readyArray_0;
	Buffer_6_dataInArray_0 <= std_logic_vector (resize(unsigned(forkC_15_dataOutArray_1),Buffer_6_dataInArray_0'length));
	brCst_block4_pValidArray_0 <= forkC_15_validArray_2;
	forkC_15_nReadyArray_2 <= brCst_block4_readyArray_0;
	brCst_block4_dataInArray_0 <= "1";

	branchC_7_clk <= clk;
	branchC_7_rst <= rst;
	phiC_5_pValidArray_1 <= branchC_7_validArray_0;
	branchC_7_nReadyArray_0 <= phiC_5_readyArray_1;
	phiC_5_dataInArray_1 <= std_logic_vector (resize(unsigned(branchC_7_dataOutArray_0),phiC_5_dataInArray_1'length));
	sink_6_pValidArray_0 <= branchC_7_validArray_1;
	branchC_7_nReadyArray_1 <= sink_6_readyArray_0;
	sink_6_dataInArray_0 <= std_logic_vector (resize(unsigned(branchC_7_dataOutArray_1),sink_6_dataInArray_0'length));

	fork_16_clk <= clk;
	fork_16_rst <= rst;
	branch_3_pValidArray_1 <= fork_16_validArray_0;
	fork_16_nReadyArray_0 <= branch_3_readyArray_1;
	branch_3_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_16_dataOutArray_0),branch_3_dataInArray_1'length));
	branchC_7_pValidArray_1 <= fork_16_validArray_1;
	fork_16_nReadyArray_1 <= branchC_7_readyArray_1;
	branchC_7_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_16_dataOutArray_1),branchC_7_dataInArray_1'length));

	Buffer_6_clk <= clk;
	Buffer_6_rst <= rst;
	branchC_7_pValidArray_0 <= Buffer_6_validArray_0;
	Buffer_6_nReadyArray_0 <= branchC_7_readyArray_0;
	branchC_7_dataInArray_0 <= std_logic_vector (resize(unsigned(Buffer_6_dataOutArray_0),branchC_7_dataInArray_0'length));

	cst_10_clk <= clk;
	cst_10_rst <= rst;
	add_28_pValidArray_1 <= cst_10_validArray_0;
	cst_10_nReadyArray_0 <= add_28_readyArray_1;
	add_28_dataInArray_1 <= std_logic_vector (resize(unsigned(cst_10_dataOutArray_0),add_28_dataInArray_1'length));

	add_28_clk <= clk;
	add_28_rst <= rst;
	fork_5_pValidArray_0 <= add_28_validArray_0;
	add_28_nReadyArray_0 <= fork_5_readyArray_0;
	fork_5_dataInArray_0 <= std_logic_vector (resize(unsigned(add_28_dataOutArray_0),fork_5_dataInArray_0'length));

	cst_11_clk <= clk;
	cst_11_rst <= rst;
	icmp_29_pValidArray_1 <= cst_11_validArray_0;
	cst_11_nReadyArray_0 <= icmp_29_readyArray_1;
	icmp_29_dataInArray_1 <= std_logic_vector (resize(unsigned(cst_11_dataOutArray_0),icmp_29_dataInArray_1'length));

	icmp_29_clk <= clk;
	icmp_29_rst <= rst;
	fork_18_pValidArray_0 <= icmp_29_validArray_0;
	icmp_29_nReadyArray_0 <= fork_18_readyArray_0;
	fork_18_dataInArray_0 <= std_logic_vector (resize(unsigned(icmp_29_dataOutArray_0),fork_18_dataInArray_0'length));

	phi_n0_clk <= clk;
	phi_n0_rst <= rst;
	add_28_pValidArray_0 <= phi_n0_validArray_0;
	phi_n0_nReadyArray_0 <= add_28_readyArray_0;
	add_28_dataInArray_0 <= std_logic_vector (resize(unsigned(phi_n0_dataOutArray_0),add_28_dataInArray_0'length));

	fork_5_clk <= clk;
	fork_5_rst <= rst;
	icmp_29_pValidArray_0 <= fork_5_validArray_0;
	fork_5_nReadyArray_0 <= icmp_29_readyArray_0;
	icmp_29_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_5_dataOutArray_0),icmp_29_dataInArray_0'length));
	branch_4_pValidArray_0 <= fork_5_validArray_1;
	fork_5_nReadyArray_1 <= branch_4_readyArray_0;
	branch_4_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_5_dataOutArray_1),branch_4_dataInArray_0'length));

	branch_4_clk <= clk;
	branch_4_rst <= rst;
	phi_16_pValidArray_2 <= branch_4_validArray_0;
	branch_4_nReadyArray_0 <= phi_16_readyArray_2;
	phi_16_dataInArray_2 <= std_logic_vector (resize(unsigned(branch_4_dataOutArray_0),phi_16_dataInArray_2'length));
	sink_4_pValidArray_0 <= branch_4_validArray_1;
	branch_4_nReadyArray_1 <= sink_4_readyArray_0;
	sink_4_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_4_dataOutArray_1),sink_4_dataInArray_0'length));

	phiC_5_clk <= clk;
	phiC_5_rst <= rst;
	branchC_8_pValidArray_0 <= phiC_5_validArray_0;
	phiC_5_nReadyArray_0 <= branchC_8_readyArray_0;
	branchC_8_dataInArray_0 <= std_logic_vector (resize(unsigned(phiC_5_dataOutArray_0),branchC_8_dataInArray_0'length));

	branchC_8_clk <= clk;
	branchC_8_rst <= rst;
	phiC_3_pValidArray_1 <= branchC_8_validArray_0;
	branchC_8_nReadyArray_0 <= phiC_3_readyArray_1;
	phiC_3_dataInArray_1 <= std_logic_vector (resize(unsigned(branchC_8_dataOutArray_0),phiC_3_dataInArray_1'length));
	Buffer_7_pValidArray_0 <= branchC_8_validArray_1;
	branchC_8_nReadyArray_1 <= Buffer_7_readyArray_0;
	Buffer_7_dataInArray_0 <= std_logic_vector (resize(unsigned(branchC_8_dataOutArray_1),Buffer_7_dataInArray_0'length));

	fork_18_clk <= clk;
	fork_18_rst <= rst;
	branch_4_pValidArray_1 <= fork_18_validArray_0;
	fork_18_nReadyArray_0 <= branch_4_readyArray_1;
	branch_4_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_18_dataOutArray_0),branch_4_dataInArray_1'length));
	branchC_8_pValidArray_1 <= fork_18_validArray_1;
	fork_18_nReadyArray_1 <= branchC_8_readyArray_1;
	branchC_8_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_18_dataOutArray_1),branchC_8_dataInArray_1'length));

	source_9_clk <= clk;
	source_9_rst <= rst;
	cst_10_pValidArray_0 <= source_9_validArray_0;
	source_9_nReadyArray_0 <= cst_10_readyArray_0;
	cst_10_dataInArray_0 <= "00000000000000000000000000000001";

	source_10_clk <= clk;
	source_10_rst <= rst;
	cst_11_pValidArray_0 <= source_10_validArray_0;
	source_10_nReadyArray_0 <= cst_11_readyArray_0;
	cst_11_dataInArray_0 <= "00000000000000000000001111101000";

	Buffer_7_clk <= clk;
	Buffer_7_rst <= rst;
	phiC_6_pValidArray_0 <= Buffer_7_validArray_0;
	Buffer_7_nReadyArray_0 <= phiC_6_readyArray_0;
	phiC_6_dataInArray_0 <= std_logic_vector (resize(unsigned(Buffer_7_dataOutArray_0),phiC_6_dataInArray_0'length));

	ret_1_clk <= clk;
	ret_1_rst <= rst;
	end_0_pValidArray_2 <= ret_1_validArray_0;
	ret_1_nReadyArray_0 <= end_0_readyArray_2;
	end_0_dataInArray_2 <= std_logic_vector (resize(unsigned(ret_1_dataOutArray_0),end_0_dataInArray_2'length));

	phiC_6_clk <= clk;
	phiC_6_rst <= rst;
	ret_1_pValidArray_0 <= phiC_6_validArray_0;
	phiC_6_nReadyArray_0 <= ret_1_readyArray_0;
	ret_1_dataInArray_0 <= std_logic_vector (resize(unsigned(phiC_6_dataOutArray_0),ret_1_dataInArray_0'length));

	LSQ_A_clk <= clk;
	LSQ_A_rst <= rst;
	LSQ_A_din1 <= A_din1;
	LSQ_A_store_ready <= '1';
	LSQ_A_load_ready <= '1';
	A_address1 <= std_logic_vector (resize(unsigned(LSQ_A_address1),A_address1'length));
	A_ce1 <= LSQ_A_ce1;
	A_address0 <= std_logic_vector (resize(unsigned(LSQ_A_address0),A_address0'length));
	A_ce0 <= LSQ_A_we0_ce0;
	A_we0 <= LSQ_A_we0_ce0;
	A_dout0 <= LSQ_A_dout0;
	load_19_pValidArray_0 <= LSQ_A_validArray_0;
	LSQ_A_nReadyArray_0 <= load_19_readyArray_0;
	load_19_dataInArray_0 <= std_logic_vector (resize(unsigned(LSQ_A_dataOutArray_0),load_19_dataInArray_0'length));
	end_0_pValidArray_0 <= LSQ_A_validArray_1;
	LSQ_A_nReadyArray_1 <= end_0_readyArray_0;
	end_0_dataInArray_0 <= std_logic_vector (resize(unsigned(LSQ_A_dataOutArray_1),end_0_dataInArray_0'length));

	MC_b_clk <= clk;
	MC_b_rst <= rst;
	b_ce0 <= MC_b_we0_ce0;
	b_we0 <= MC_b_we0_ce0;
	load_24_pValidArray_0 <= MC_b_validArray_0;
	MC_b_nReadyArray_0 <= load_24_readyArray_0;
	load_24_dataInArray_0 <= std_logic_vector (resize(unsigned(MC_b_dataOutArray_0),load_24_dataInArray_0'length));
	end_0_pValidArray_1 <= MC_b_validArray_1;
	MC_b_nReadyArray_1 <= end_0_readyArray_1;
	end_0_dataInArray_1 <= std_logic_vector (resize(unsigned(MC_b_dataOutArray_1),end_0_dataInArray_1'length));

	end_0_clk <= clk;
	end_0_rst <= rst;
	end_valid <= end_0_validArray_0;
	end_out <= end_0_dataOutArray_0;
	end_0_nReadyArray_0 <= end_ready;

	sink_1_clk <= clk;
	sink_1_rst <= rst;

	sink_2_clk <= clk;
	sink_2_rst <= rst;

	sink_3_clk <= clk;
	sink_3_rst <= rst;

	sink_4_clk <= clk;
	sink_4_rst <= rst;

	sink_5_clk <= clk;
	sink_5_rst <= rst;

	sink_6_clk <= clk;
	sink_6_rst <= rst;

brCst_block2: entity work.Const(arch) generic map (1,1,1,1)
port map (
	clk => brCst_block2_clk,
	rst => brCst_block2_rst,
	dataInArray(0) => brCst_block2_dataInArray_0,
	pValidArray(0) => brCst_block2_pValidArray_0,
	readyArray(0) => brCst_block2_readyArray_0,
	nReadyArray(0) => brCst_block2_nReadyArray_0,
	validArray(0) => brCst_block2_validArray_0,
	dataOutArray(0) => brCst_block2_dataOutArray_0
);

cst_8: entity work.Const(arch) generic map (1,1,32,32)
port map (
	clk => cst_8_clk,
	rst => cst_8_rst,
	dataInArray(0) => cst_8_dataInArray_0,
	pValidArray(0) => cst_8_pValidArray_0,
	readyArray(0) => cst_8_readyArray_0,
	nReadyArray(0) => cst_8_nReadyArray_0,
	validArray(0) => cst_8_validArray_0,
	dataOutArray(0) => cst_8_dataOutArray_0
);

branch_0: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_0_clk,
	rst => branch_0_rst,
	dataInArray(0) => branch_0_dataInArray_0,
	Condition(0) => branch_0_dataInArray_1,
	pValidArray(0) => branch_0_pValidArray_0,
	pValidArray(1) => branch_0_pValidArray_1,
	readyArray(0) => branch_0_readyArray_0,
	readyArray(1) => branch_0_readyArray_1,
	nReadyArray(0) => branch_0_nReadyArray_0,
	nReadyArray(1) => branch_0_nReadyArray_1,
	validArray(0) => branch_0_validArray_0,
	validArray(1) => branch_0_validArray_1,
	dataOutArray(0) => branch_0_dataOutArray_0,
	dataOutArray(1) => branch_0_dataOutArray_1
);

start_1: entity work.start_node(arch) generic map (1,1,1,1)
port map (
	clk => start_1_clk,
	rst => start_1_rst,
	dataInArray(0) => start_1_dataInArray_0,
	pValidArray(0) => start_1_pValidArray_0,
	readyArray(0) => start_1_readyArray_0,
	nReadyArray(0) => start_1_nReadyArray_0,
	validArray(0) => start_1_validArray_0,
	dataOutArray(0) => start_1_dataOutArray_0
);

forkC_12: entity work.fork(arch) generic map (1,3,1,1)
port map (
	clk => forkC_12_clk,
	rst => forkC_12_rst,
	dataInArray(0) => forkC_12_dataInArray_0,
	pValidArray(0) => forkC_12_pValidArray_0,
	readyArray(0) => forkC_12_readyArray_0,
	nReadyArray(0) => forkC_12_nReadyArray_0,
	nReadyArray(1) => forkC_12_nReadyArray_1,
	nReadyArray(2) => forkC_12_nReadyArray_2,
	validArray(0) => forkC_12_validArray_0,
	validArray(1) => forkC_12_validArray_1,
	validArray(2) => forkC_12_validArray_2,
	dataOutArray(0) => forkC_12_dataOutArray_0,
	dataOutArray(1) => forkC_12_dataOutArray_1,
	dataOutArray(2) => forkC_12_dataOutArray_2
);

branchC_5: entity work.Branch(arch) generic map (2,2,1,1)
port map (
	clk => branchC_5_clk,
	rst => branchC_5_rst,
	dataInArray(0) => branchC_5_dataInArray_0,
	Condition(0) => branchC_5_dataInArray_1,
	pValidArray(0) => branchC_5_pValidArray_0,
	pValidArray(1) => branchC_5_pValidArray_1,
	readyArray(0) => branchC_5_readyArray_0,
	readyArray(1) => branchC_5_readyArray_1,
	nReadyArray(0) => branchC_5_nReadyArray_0,
	nReadyArray(1) => branchC_5_nReadyArray_1,
	validArray(0) => branchC_5_validArray_0,
	validArray(1) => branchC_5_validArray_1,
	dataOutArray(0) => branchC_5_dataOutArray_0,
	dataOutArray(1) => branchC_5_dataOutArray_1
);

fork_13: entity work.fork(arch) generic map (1,2,1,1)
port map (
	clk => fork_13_clk,
	rst => fork_13_rst,
	dataInArray(0) => fork_13_dataInArray_0,
	pValidArray(0) => fork_13_pValidArray_0,
	readyArray(0) => fork_13_readyArray_0,
	nReadyArray(0) => fork_13_nReadyArray_0,
	nReadyArray(1) => fork_13_nReadyArray_1,
	validArray(0) => fork_13_validArray_0,
	validArray(1) => fork_13_validArray_1,
	dataOutArray(0) => fork_13_dataOutArray_0,
	dataOutArray(1) => fork_13_dataOutArray_1
);

Buffer_3: entity work.elasticBuffer(arch) generic map (1,1,32,32)
port map (
	clk => Buffer_3_clk,
	rst => Buffer_3_rst,
	dataInArray(0) => Buffer_3_dataInArray_0,
	pValidArray(0) => Buffer_3_pValidArray_0,
	readyArray(0) => Buffer_3_readyArray_0,
	nReadyArray(0) => Buffer_3_nReadyArray_0,
	validArray(0) => Buffer_3_validArray_0,
	dataOutArray(0) => Buffer_3_dataOutArray_0
);

Buffer_4: entity work.elasticBuffer(arch) generic map (1,1,1,1)
port map (
	clk => Buffer_4_clk,
	rst => Buffer_4_rst,
	dataInArray(0) => Buffer_4_dataInArray_0,
	pValidArray(0) => Buffer_4_pValidArray_0,
	readyArray(0) => Buffer_4_readyArray_0,
	nReadyArray(0) => Buffer_4_nReadyArray_0,
	validArray(0) => Buffer_4_validArray_0,
	dataOutArray(0) => Buffer_4_dataOutArray_0
);

phi_16: entity work.Mux(arch) generic map (3,1,32,32,1)
port map (
	clk => phi_16_clk,
	rst => phi_16_rst,
	Condition(0) => phi_16_dataInArray_0,
	dataInArray(0) => phi_16_dataInArray_1,
	dataInArray(1) => phi_16_dataInArray_2,
	pValidArray(0) => phi_16_pValidArray_0,
	pValidArray(1) => phi_16_pValidArray_1,
	pValidArray(2) => phi_16_pValidArray_2,
	readyArray(0) => phi_16_readyArray_0,
	readyArray(1) => phi_16_readyArray_1,
	readyArray(2) => phi_16_readyArray_2,
	nReadyArray(0) => phi_16_nReadyArray_0,
	validArray(0) => phi_16_validArray_0,
	dataOutArray(0) => phi_16_dataOutArray_0
);

load_19: entity work.lsq_load_op(arch) generic map (2,2,32,32)
port map (
	clk => load_19_clk,
	rst => load_19_rst,
	dataInArray(0) => load_19_dataInArray_0,
	dataInArray(1) => load_19_dataInArray_1,
	pValidArray(0) => load_19_pValidArray_0,
	pValidArray(1) => load_19_pValidArray_1,
	readyArray(0) => load_19_readyArray_0,
	readyArray(1) => load_19_readyArray_1,
	nReadyArray(0) => load_19_nReadyArray_0,
	nReadyArray(1) => load_19_nReadyArray_1,
	validArray(0) => load_19_validArray_0,
	validArray(1) => load_19_validArray_1,
	dataOutArray(0) => load_19_dataOutArray_0,
	dataOutArray(1) => load_19_dataOutArray_1
);

cst_9: entity work.Const(arch) generic map (1,1,32,32)
port map (
	clk => cst_9_clk,
	rst => cst_9_rst,
	dataInArray(0) => cst_9_dataInArray_0,
	pValidArray(0) => cst_9_pValidArray_0,
	readyArray(0) => cst_9_readyArray_0,
	nReadyArray(0) => cst_9_nReadyArray_0,
	validArray(0) => cst_9_validArray_0,
	dataOutArray(0) => cst_9_dataOutArray_0
);

icmp_20: entity work.icmp_sgt_op(arch) generic map (2,1,32,1)
port map (
	clk => icmp_20_clk,
	rst => icmp_20_rst,
	dataInArray(0) => icmp_20_dataInArray_0,
	dataInArray(1) => icmp_20_dataInArray_1,
	pValidArray(0) => icmp_20_pValidArray_0,
	pValidArray(1) => icmp_20_pValidArray_1,
	readyArray(0) => icmp_20_readyArray_0,
	readyArray(1) => icmp_20_readyArray_1,
	nReadyArray(0) => icmp_20_nReadyArray_0,
	validArray(0) => icmp_20_validArray_0,
	dataOutArray(0) => icmp_20_dataOutArray_0
);

fork_3: entity work.fork(arch) generic map (1,2,32,32)
port map (
	clk => fork_3_clk,
	rst => fork_3_rst,
	dataInArray(0) => fork_3_dataInArray_0,
	pValidArray(0) => fork_3_pValidArray_0,
	readyArray(0) => fork_3_readyArray_0,
	nReadyArray(0) => fork_3_nReadyArray_0,
	nReadyArray(1) => fork_3_nReadyArray_1,
	validArray(0) => fork_3_validArray_0,
	validArray(1) => fork_3_validArray_1,
	dataOutArray(0) => fork_3_dataOutArray_0,
	dataOutArray(1) => fork_3_dataOutArray_1
);

fork_4: entity work.fork(arch) generic map (1,2,32,32)
port map (
	clk => fork_4_clk,
	rst => fork_4_rst,
	dataInArray(0) => fork_4_dataInArray_0,
	pValidArray(0) => fork_4_pValidArray_0,
	readyArray(0) => fork_4_readyArray_0,
	nReadyArray(0) => fork_4_nReadyArray_0,
	nReadyArray(1) => fork_4_nReadyArray_1,
	validArray(0) => fork_4_validArray_0,
	validArray(1) => fork_4_validArray_1,
	dataOutArray(0) => fork_4_dataOutArray_0,
	dataOutArray(1) => fork_4_dataOutArray_1
);

branch_1: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_1_clk,
	rst => branch_1_rst,
	dataInArray(0) => branch_1_dataInArray_0,
	Condition(0) => branch_1_dataInArray_1,
	pValidArray(0) => branch_1_pValidArray_0,
	pValidArray(1) => branch_1_pValidArray_1,
	readyArray(0) => branch_1_readyArray_0,
	readyArray(1) => branch_1_readyArray_1,
	nReadyArray(0) => branch_1_nReadyArray_0,
	nReadyArray(1) => branch_1_nReadyArray_1,
	validArray(0) => branch_1_validArray_0,
	validArray(1) => branch_1_validArray_1,
	dataOutArray(0) => branch_1_dataOutArray_0,
	dataOutArray(1) => branch_1_dataOutArray_1
);

branch_2: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_2_clk,
	rst => branch_2_rst,
	dataInArray(0) => branch_2_dataInArray_0,
	Condition(0) => branch_2_dataInArray_1,
	pValidArray(0) => branch_2_pValidArray_0,
	pValidArray(1) => branch_2_pValidArray_1,
	readyArray(0) => branch_2_readyArray_0,
	readyArray(1) => branch_2_readyArray_1,
	nReadyArray(0) => branch_2_nReadyArray_0,
	nReadyArray(1) => branch_2_nReadyArray_1,
	validArray(0) => branch_2_validArray_0,
	validArray(1) => branch_2_validArray_1,
	dataOutArray(0) => branch_2_dataOutArray_0,
	dataOutArray(1) => branch_2_dataOutArray_1
);

fork_8: entity work.fork(arch) generic map (1,3,1,1)
port map (
	clk => fork_8_clk,
	rst => fork_8_rst,
	dataInArray(0) => fork_8_dataInArray_0,
	pValidArray(0) => fork_8_pValidArray_0,
	readyArray(0) => fork_8_readyArray_0,
	nReadyArray(0) => fork_8_nReadyArray_0,
	nReadyArray(1) => fork_8_nReadyArray_1,
	nReadyArray(2) => fork_8_nReadyArray_2,
	validArray(0) => fork_8_validArray_0,
	validArray(1) => fork_8_validArray_1,
	validArray(2) => fork_8_validArray_2,
	dataOutArray(0) => fork_8_dataOutArray_0,
	dataOutArray(1) => fork_8_dataOutArray_1,
	dataOutArray(2) => fork_8_dataOutArray_2
);

phiC_3: entity work.CntrlMerge(arch) generic map (2,2,1,1,1)
port map (
	clk => phiC_3_clk,
	rst => phiC_3_rst,
	dataInArray(0) => phiC_3_dataInArray_0,
	dataInArray(1) => phiC_3_dataInArray_1,
	pValidArray(0) => phiC_3_pValidArray_0,
	pValidArray(1) => phiC_3_pValidArray_1,
	readyArray(0) => phiC_3_readyArray_0,
	readyArray(1) => phiC_3_readyArray_1,
	nReadyArray(0) => phiC_3_nReadyArray_0,
	nReadyArray(1) => phiC_3_nReadyArray_1,
	validArray(0) => phiC_3_validArray_0,
	validArray(1) => phiC_3_validArray_1,
	dataOutArray(0) => phiC_3_dataOutArray_0,
	Condition(0) => phiC_3_dataOutArray_1
);

forkC_14: entity work.fork(arch) generic map (1,2,1,1)
port map (
	clk => forkC_14_clk,
	rst => forkC_14_rst,
	dataInArray(0) => forkC_14_dataInArray_0,
	pValidArray(0) => forkC_14_pValidArray_0,
	readyArray(0) => forkC_14_readyArray_0,
	nReadyArray(0) => forkC_14_nReadyArray_0,
	nReadyArray(1) => forkC_14_nReadyArray_1,
	validArray(0) => forkC_14_validArray_0,
	validArray(1) => forkC_14_validArray_1,
	dataOutArray(0) => forkC_14_dataOutArray_0,
	dataOutArray(1) => forkC_14_dataOutArray_1
);

branchC_6: entity work.Branch(arch) generic map (2,2,1,1)
port map (
	clk => branchC_6_clk,
	rst => branchC_6_rst,
	dataInArray(0) => branchC_6_dataInArray_0,
	Condition(0) => branchC_6_dataInArray_1,
	pValidArray(0) => branchC_6_pValidArray_0,
	pValidArray(1) => branchC_6_pValidArray_1,
	readyArray(0) => branchC_6_readyArray_0,
	readyArray(1) => branchC_6_readyArray_1,
	nReadyArray(0) => branchC_6_nReadyArray_0,
	nReadyArray(1) => branchC_6_nReadyArray_1,
	validArray(0) => branchC_6_validArray_0,
	validArray(1) => branchC_6_validArray_1,
	dataOutArray(0) => branchC_6_dataOutArray_0,
	dataOutArray(1) => branchC_6_dataOutArray_1
);

source_8: entity work.source(arch) generic map (0,1,32,32)
port map (
	clk => source_8_clk,
	rst => source_8_rst,
	nReadyArray(0) => source_8_nReadyArray_0,
	validArray(0) => source_8_validArray_0,
	dataOutArray(0) => source_8_dataOutArray_0
);

Buffer_1: entity work.elasticBuffer(arch) generic map (1,1,32,32)
port map (
	clk => Buffer_1_clk,
	rst => Buffer_1_rst,
	dataInArray(0) => Buffer_1_dataInArray_0,
	pValidArray(0) => Buffer_1_pValidArray_0,
	readyArray(0) => Buffer_1_readyArray_0,
	nReadyArray(0) => Buffer_1_nReadyArray_0,
	validArray(0) => Buffer_1_validArray_0,
	dataOutArray(0) => Buffer_1_dataOutArray_0
);

Buffer_2: entity work.TEHB(arch) generic map (1,1,32,32)
port map (
	clk => Buffer_2_clk,
	rst => Buffer_2_rst,
	dataInArray(0) => Buffer_2_dataInArray_0,
	pValidArray(0) => Buffer_2_pValidArray_0,
	readyArray(0) => Buffer_2_readyArray_0,
	nReadyArray(0) => Buffer_2_nReadyArray_0,
	validArray(0) => Buffer_2_validArray_0,
	dataOutArray(0) => Buffer_2_dataOutArray_0
);

Buffer_5: entity work.elasticBuffer(arch) generic map (1,1,1,1)
port map (
	clk => Buffer_5_clk,
	rst => Buffer_5_rst,
	dataInArray(0) => Buffer_5_dataInArray_0,
	pValidArray(0) => Buffer_5_pValidArray_0,
	readyArray(0) => Buffer_5_readyArray_0,
	nReadyArray(0) => Buffer_5_nReadyArray_0,
	validArray(0) => Buffer_5_validArray_0,
	dataOutArray(0) => Buffer_5_dataOutArray_0
);

call_0: entity work.ss_g(arch) generic map (1,1,32,32,15,2)
port map (
	clk => call_0_clk,
	rst => call_0_rst,
	dataInArray(0) => call_0_dataInArray_0,
	pValidArray(0) => call_0_pValidArray_0,
	readyArray(0) => call_0_readyArray_0,
	nReadyArray(0) => call_0_nReadyArray_0,
	validArray(0) => call_0_validArray_0,
	dataOutArray(0) => call_0_dataOutArray_0
);

load_24: entity work.mc_load_op(arch) generic map (2,2,32,32)
port map (
	clk => load_24_clk,
	rst => load_24_rst,
	dataInArray(0) => load_24_dataInArray_0,
	input_addr => load_24_dataInArray_1,
	pValidArray(0) => load_24_pValidArray_0,
	pValidArray(1) => load_24_pValidArray_1,
	readyArray(0) => load_24_readyArray_0,
	readyArray(1) => load_24_readyArray_1,
	nReadyArray(0) => load_24_nReadyArray_0,
	nReadyArray(1) => load_24_nReadyArray_1,
	validArray(0) => load_24_validArray_0,
	validArray(1) => load_24_validArray_1,
	dataOutArray(0) => load_24_dataOutArray_0,
	output_addr => load_24_dataOutArray_1
);

store_0: entity work.lsq_store_op(arch) generic map (2,2,32,32)
port map (
	clk => store_0_clk,
	rst => store_0_rst,
	dataInArray(0) => store_0_dataInArray_0,
	input_addr => store_0_dataInArray_1,
	pValidArray(0) => store_0_pValidArray_0,
	pValidArray(1) => store_0_pValidArray_1,
	readyArray(0) => store_0_readyArray_0,
	readyArray(1) => store_0_readyArray_1,
	nReadyArray(0) => store_0_nReadyArray_0,
	nReadyArray(1) => store_0_nReadyArray_1,
	validArray(0) => store_0_validArray_0,
	validArray(1) => store_0_validArray_1,
	dataOutArray(0) => store_0_dataOutArray_0,
	dataOutArray(1) => store_0_dataOutArray_1
);

brCst_block4: entity work.Const(arch) generic map (1,1,1,1)
port map (
	clk => brCst_block4_clk,
	rst => brCst_block4_rst,
	dataInArray(0) => brCst_block4_dataInArray_0,
	pValidArray(0) => brCst_block4_pValidArray_0,
	readyArray(0) => brCst_block4_readyArray_0,
	nReadyArray(0) => brCst_block4_nReadyArray_0,
	validArray(0) => brCst_block4_validArray_0,
	dataOutArray(0) => brCst_block4_dataOutArray_0
);

phi_n1: entity work.merge(arch) generic map (1,1,32,32)
port map (
	clk => phi_n1_clk,
	rst => phi_n1_rst,
	dataInArray(0) => phi_n1_dataInArray_0,
	pValidArray(0) => phi_n1_pValidArray_0,
	readyArray(0) => phi_n1_readyArray_0,
	nReadyArray(0) => phi_n1_nReadyArray_0,
	validArray(0) => phi_n1_validArray_0,
	dataOutArray(0) => phi_n1_dataOutArray_0
);

phi_n2: entity work.merge(arch) generic map (1,1,32,32)
port map (
	clk => phi_n2_clk,
	rst => phi_n2_rst,
	dataInArray(0) => phi_n2_dataInArray_0,
	pValidArray(0) => phi_n2_pValidArray_0,
	readyArray(0) => phi_n2_readyArray_0,
	nReadyArray(0) => phi_n2_nReadyArray_0,
	validArray(0) => phi_n2_validArray_0,
	dataOutArray(0) => phi_n2_dataOutArray_0
);

fork_6: entity work.fork(arch) generic map (1,2,32,32)
port map (
	clk => fork_6_clk,
	rst => fork_6_rst,
	dataInArray(0) => fork_6_dataInArray_0,
	pValidArray(0) => fork_6_pValidArray_0,
	readyArray(0) => fork_6_readyArray_0,
	nReadyArray(0) => fork_6_nReadyArray_0,
	nReadyArray(1) => fork_6_nReadyArray_1,
	validArray(0) => fork_6_validArray_0,
	validArray(1) => fork_6_validArray_1,
	dataOutArray(0) => fork_6_dataOutArray_0,
	dataOutArray(1) => fork_6_dataOutArray_1
);

branch_3: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_3_clk,
	rst => branch_3_rst,
	dataInArray(0) => branch_3_dataInArray_0,
	Condition(0) => branch_3_dataInArray_1,
	pValidArray(0) => branch_3_pValidArray_0,
	pValidArray(1) => branch_3_pValidArray_1,
	readyArray(0) => branch_3_readyArray_0,
	readyArray(1) => branch_3_readyArray_1,
	nReadyArray(0) => branch_3_nReadyArray_0,
	nReadyArray(1) => branch_3_nReadyArray_1,
	validArray(0) => branch_3_validArray_0,
	validArray(1) => branch_3_validArray_1,
	dataOutArray(0) => branch_3_dataOutArray_0,
	dataOutArray(1) => branch_3_dataOutArray_1
);

phiC_4: entity work.merge(arch) generic map (1,1,1,1)
port map (
	clk => phiC_4_clk,
	rst => phiC_4_rst,
	dataInArray(0) => phiC_4_dataInArray_0,
	pValidArray(0) => phiC_4_pValidArray_0,
	readyArray(0) => phiC_4_readyArray_0,
	nReadyArray(0) => phiC_4_nReadyArray_0,
	validArray(0) => phiC_4_validArray_0,
	dataOutArray(0) => phiC_4_dataOutArray_0
);

forkC_15: entity work.fork(arch) generic map (1,3,1,1)
port map (
	clk => forkC_15_clk,
	rst => forkC_15_rst,
	dataInArray(0) => forkC_15_dataInArray_0,
	pValidArray(0) => forkC_15_pValidArray_0,
	readyArray(0) => forkC_15_readyArray_0,
	nReadyArray(0) => forkC_15_nReadyArray_0,
	nReadyArray(1) => forkC_15_nReadyArray_1,
	nReadyArray(2) => forkC_15_nReadyArray_2,
	validArray(0) => forkC_15_validArray_0,
	validArray(1) => forkC_15_validArray_1,
	validArray(2) => forkC_15_validArray_2,
	dataOutArray(0) => forkC_15_dataOutArray_0,
	dataOutArray(1) => forkC_15_dataOutArray_1,
	dataOutArray(2) => forkC_15_dataOutArray_2
);

branchC_7: entity work.Branch(arch) generic map (2,2,1,1)
port map (
	clk => branchC_7_clk,
	rst => branchC_7_rst,
	dataInArray(0) => branchC_7_dataInArray_0,
	Condition(0) => branchC_7_dataInArray_1,
	pValidArray(0) => branchC_7_pValidArray_0,
	pValidArray(1) => branchC_7_pValidArray_1,
	readyArray(0) => branchC_7_readyArray_0,
	readyArray(1) => branchC_7_readyArray_1,
	nReadyArray(0) => branchC_7_nReadyArray_0,
	nReadyArray(1) => branchC_7_nReadyArray_1,
	validArray(0) => branchC_7_validArray_0,
	validArray(1) => branchC_7_validArray_1,
	dataOutArray(0) => branchC_7_dataOutArray_0,
	dataOutArray(1) => branchC_7_dataOutArray_1
);

fork_16: entity work.fork(arch) generic map (1,2,1,1)
port map (
	clk => fork_16_clk,
	rst => fork_16_rst,
	dataInArray(0) => fork_16_dataInArray_0,
	pValidArray(0) => fork_16_pValidArray_0,
	readyArray(0) => fork_16_readyArray_0,
	nReadyArray(0) => fork_16_nReadyArray_0,
	nReadyArray(1) => fork_16_nReadyArray_1,
	validArray(0) => fork_16_validArray_0,
	validArray(1) => fork_16_validArray_1,
	dataOutArray(0) => fork_16_dataOutArray_0,
	dataOutArray(1) => fork_16_dataOutArray_1
);

Buffer_6: entity work.elasticBuffer(arch) generic map (1,1,1,1)
port map (
	clk => Buffer_6_clk,
	rst => Buffer_6_rst,
	dataInArray(0) => Buffer_6_dataInArray_0,
	pValidArray(0) => Buffer_6_pValidArray_0,
	readyArray(0) => Buffer_6_readyArray_0,
	nReadyArray(0) => Buffer_6_nReadyArray_0,
	validArray(0) => Buffer_6_validArray_0,
	dataOutArray(0) => Buffer_6_dataOutArray_0
);

cst_10: entity work.Const(arch) generic map (1,1,32,32)
port map (
	clk => cst_10_clk,
	rst => cst_10_rst,
	dataInArray(0) => cst_10_dataInArray_0,
	pValidArray(0) => cst_10_pValidArray_0,
	readyArray(0) => cst_10_readyArray_0,
	nReadyArray(0) => cst_10_nReadyArray_0,
	validArray(0) => cst_10_validArray_0,
	dataOutArray(0) => cst_10_dataOutArray_0
);

add_28: entity work.add_op(arch) generic map (2,1,32,32)
port map (
	clk => add_28_clk,
	rst => add_28_rst,
	dataInArray(0) => add_28_dataInArray_0,
	dataInArray(1) => add_28_dataInArray_1,
	pValidArray(0) => add_28_pValidArray_0,
	pValidArray(1) => add_28_pValidArray_1,
	readyArray(0) => add_28_readyArray_0,
	readyArray(1) => add_28_readyArray_1,
	nReadyArray(0) => add_28_nReadyArray_0,
	validArray(0) => add_28_validArray_0,
	dataOutArray(0) => add_28_dataOutArray_0
);

cst_11: entity work.Const(arch) generic map (1,1,32,32)
port map (
	clk => cst_11_clk,
	rst => cst_11_rst,
	dataInArray(0) => cst_11_dataInArray_0,
	pValidArray(0) => cst_11_pValidArray_0,
	readyArray(0) => cst_11_readyArray_0,
	nReadyArray(0) => cst_11_nReadyArray_0,
	validArray(0) => cst_11_validArray_0,
	dataOutArray(0) => cst_11_dataOutArray_0
);

icmp_29: entity work.icmp_ult_op(arch) generic map (2,1,32,1)
port map (
	clk => icmp_29_clk,
	rst => icmp_29_rst,
	dataInArray(0) => icmp_29_dataInArray_0,
	dataInArray(1) => icmp_29_dataInArray_1,
	pValidArray(0) => icmp_29_pValidArray_0,
	pValidArray(1) => icmp_29_pValidArray_1,
	readyArray(0) => icmp_29_readyArray_0,
	readyArray(1) => icmp_29_readyArray_1,
	nReadyArray(0) => icmp_29_nReadyArray_0,
	validArray(0) => icmp_29_validArray_0,
	dataOutArray(0) => icmp_29_dataOutArray_0
);

phi_n0: entity work.merge(arch) generic map (2,1,32,32)
port map (
	clk => phi_n0_clk,
	rst => phi_n0_rst,
	dataInArray(0) => phi_n0_dataInArray_0,
	dataInArray(1) => phi_n0_dataInArray_1,
	pValidArray(0) => phi_n0_pValidArray_0,
	pValidArray(1) => phi_n0_pValidArray_1,
	readyArray(0) => phi_n0_readyArray_0,
	readyArray(1) => phi_n0_readyArray_1,
	nReadyArray(0) => phi_n0_nReadyArray_0,
	validArray(0) => phi_n0_validArray_0,
	dataOutArray(0) => phi_n0_dataOutArray_0
);

fork_5: entity work.fork(arch) generic map (1,2,32,32)
port map (
	clk => fork_5_clk,
	rst => fork_5_rst,
	dataInArray(0) => fork_5_dataInArray_0,
	pValidArray(0) => fork_5_pValidArray_0,
	readyArray(0) => fork_5_readyArray_0,
	nReadyArray(0) => fork_5_nReadyArray_0,
	nReadyArray(1) => fork_5_nReadyArray_1,
	validArray(0) => fork_5_validArray_0,
	validArray(1) => fork_5_validArray_1,
	dataOutArray(0) => fork_5_dataOutArray_0,
	dataOutArray(1) => fork_5_dataOutArray_1
);

branch_4: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_4_clk,
	rst => branch_4_rst,
	dataInArray(0) => branch_4_dataInArray_0,
	Condition(0) => branch_4_dataInArray_1,
	pValidArray(0) => branch_4_pValidArray_0,
	pValidArray(1) => branch_4_pValidArray_1,
	readyArray(0) => branch_4_readyArray_0,
	readyArray(1) => branch_4_readyArray_1,
	nReadyArray(0) => branch_4_nReadyArray_0,
	nReadyArray(1) => branch_4_nReadyArray_1,
	validArray(0) => branch_4_validArray_0,
	validArray(1) => branch_4_validArray_1,
	dataOutArray(0) => branch_4_dataOutArray_0,
	dataOutArray(1) => branch_4_dataOutArray_1
);

phiC_5: entity work.merge(arch) generic map (2,1,1,1)
port map (
	clk => phiC_5_clk,
	rst => phiC_5_rst,
	dataInArray(0) => phiC_5_dataInArray_0,
	dataInArray(1) => phiC_5_dataInArray_1,
	pValidArray(0) => phiC_5_pValidArray_0,
	pValidArray(1) => phiC_5_pValidArray_1,
	readyArray(0) => phiC_5_readyArray_0,
	readyArray(1) => phiC_5_readyArray_1,
	nReadyArray(0) => phiC_5_nReadyArray_0,
	validArray(0) => phiC_5_validArray_0,
	dataOutArray(0) => phiC_5_dataOutArray_0
);

branchC_8: entity work.Branch(arch) generic map (2,2,1,1)
port map (
	clk => branchC_8_clk,
	rst => branchC_8_rst,
	dataInArray(0) => branchC_8_dataInArray_0,
	Condition(0) => branchC_8_dataInArray_1,
	pValidArray(0) => branchC_8_pValidArray_0,
	pValidArray(1) => branchC_8_pValidArray_1,
	readyArray(0) => branchC_8_readyArray_0,
	readyArray(1) => branchC_8_readyArray_1,
	nReadyArray(0) => branchC_8_nReadyArray_0,
	nReadyArray(1) => branchC_8_nReadyArray_1,
	validArray(0) => branchC_8_validArray_0,
	validArray(1) => branchC_8_validArray_1,
	dataOutArray(0) => branchC_8_dataOutArray_0,
	dataOutArray(1) => branchC_8_dataOutArray_1
);

fork_18: entity work.fork(arch) generic map (1,2,1,1)
port map (
	clk => fork_18_clk,
	rst => fork_18_rst,
	dataInArray(0) => fork_18_dataInArray_0,
	pValidArray(0) => fork_18_pValidArray_0,
	readyArray(0) => fork_18_readyArray_0,
	nReadyArray(0) => fork_18_nReadyArray_0,
	nReadyArray(1) => fork_18_nReadyArray_1,
	validArray(0) => fork_18_validArray_0,
	validArray(1) => fork_18_validArray_1,
	dataOutArray(0) => fork_18_dataOutArray_0,
	dataOutArray(1) => fork_18_dataOutArray_1
);

source_9: entity work.source(arch) generic map (0,1,32,32)
port map (
	clk => source_9_clk,
	rst => source_9_rst,
	nReadyArray(0) => source_9_nReadyArray_0,
	validArray(0) => source_9_validArray_0,
	dataOutArray(0) => source_9_dataOutArray_0
);

source_10: entity work.source(arch) generic map (0,1,32,32)
port map (
	clk => source_10_clk,
	rst => source_10_rst,
	nReadyArray(0) => source_10_nReadyArray_0,
	validArray(0) => source_10_validArray_0,
	dataOutArray(0) => source_10_dataOutArray_0
);

Buffer_7: entity work.elasticBuffer(arch) generic map (1,1,1,1)
port map (
	clk => Buffer_7_clk,
	rst => Buffer_7_rst,
	dataInArray(0) => Buffer_7_dataInArray_0,
	pValidArray(0) => Buffer_7_pValidArray_0,
	readyArray(0) => Buffer_7_readyArray_0,
	nReadyArray(0) => Buffer_7_nReadyArray_0,
	validArray(0) => Buffer_7_validArray_0,
	dataOutArray(0) => Buffer_7_dataOutArray_0
);

ret_1: entity work.ret_op(arch) generic map (1,1,1,1)
port map (
	clk => ret_1_clk,
	rst => ret_1_rst,
	dataInArray(0) => ret_1_dataInArray_0,
	pValidArray(0) => ret_1_pValidArray_0,
	readyArray(0) => ret_1_readyArray_0,
	nReadyArray(0) => ret_1_nReadyArray_0,
	validArray(0) => ret_1_validArray_0,
	dataOutArray(0) => ret_1_dataOutArray_0
);

phiC_6: entity work.merge(arch) generic map (1,1,1,1)
port map (
	clk => phiC_6_clk,
	rst => phiC_6_rst,
	dataInArray(0) => phiC_6_dataInArray_0,
	pValidArray(0) => phiC_6_pValidArray_0,
	readyArray(0) => phiC_6_readyArray_0,
	nReadyArray(0) => phiC_6_nReadyArray_0,
	validArray(0) => phiC_6_validArray_0,
	dataOutArray(0) => phiC_6_dataOutArray_0
);

LSQ_A: entity work.LSQ_A
port map (
	clock => LSQ_A_clk,
	reset => LSQ_A_rst,
	io_memIsReadyForLoads => LSQ_A_load_ready,
	io_memIsReadyForStores => LSQ_A_store_ready,
	io_storeDataOut => LSQ_A_dout0,
	io_storeAddrOut => LSQ_A_address0,
	io_storeEnable => LSQ_A_we0_ce0,
	io_loadDataIn => LSQ_A_din1,
	io_loadAddrOut => LSQ_A_address1,
	io_loadEnable => LSQ_A_ce1,
	io_bbReadyToPrevs_0 => LSQ_A_readyArray_0,
	io_bbReadyToPrevs_1 => LSQ_A_readyArray_1,
	io_bbpValids_0 => LSQ_A_pValidArray_0,
	io_bbpValids_1 => LSQ_A_pValidArray_1,
	io_rdPortsPrev_0_ready => LSQ_A_readyArray_2,
	io_rdPortsPrev_0_valid => LSQ_A_pValidArray_2,
	io_rdPortsPrev_0_bits => LSQ_A_dataInArray_2,
	io_wrAddrPorts_0_ready => LSQ_A_readyArray_3,
	io_wrAddrPorts_0_valid => LSQ_A_pValidArray_3,
	io_wrAddrPorts_0_bits => LSQ_A_dataInArray_3,
	io_wrDataPorts_0_ready => LSQ_A_readyArray_4,
	io_wrDataPorts_0_valid => LSQ_A_pValidArray_4,
	io_wrDataPorts_0_bits => LSQ_A_dataInArray_4,
	io_rdPortsNext_0_ready => LSQ_A_nReadyArray_0,
	io_rdPortsNext_0_valid => LSQ_A_validArray_0,
	io_rdPortsNext_0_bits => LSQ_A_dataOutArray_0,
	io_Empty_Valid => LSQ_A_validArray_1

);

MC_b: entity work.MemCont(arch) generic map (32,32,1,1,1)
port map (
	clk => MC_b_clk,
	rst => MC_b_rst,
	io_storeDataOut => b_dout0,
	io_storeAddrOut => b_address0,
	io_storeEnable => MC_b_we0_ce0,
	io_loadDataIn => b_din1,
	io_loadAddrOut => b_address1,
	io_loadEnable => b_ce1,
	io_bbReadyToPrevs(0) => MC_b_readyArray_1,
	io_bbpValids(0) => '0',
	io_bb_stCountArray(0) => x"00000000",
	io_rdPortsPrev_ready(0) => MC_b_readyArray_0,
	io_rdPortsPrev_valid(0) => MC_b_pValidArray_0,
	io_rdPortsPrev_bits(0) => MC_b_dataInArray_0,
	io_wrAddrPorts_ready(0) => MC_b_readyArray_2,
	io_wrAddrPorts_valid(0) => MC_b_pValidArray_2,
	io_wrAddrPorts_bits(0) => MC_b_dataInArray_2,
	io_wrDataPorts_ready(0) => MC_b_readyArray_3,
	io_wrDataPorts_valid(0) => MC_b_pValidArray_3,
	io_wrDataPorts_bits(0) => MC_b_dataInArray_3,
	io_rdPortsNext_ready(0) => MC_b_nReadyArray_0,
	io_rdPortsNext_valid(0) => MC_b_validArray_0,
	io_rdPortsNext_bits(0) => MC_b_dataOutArray_0,
	io_Empty_Valid => MC_b_validArray_1,
	io_Empty_Ready => MC_b_nReadyArray_1

);

end_0: entity work.end_node(arch) generic map (1,2,1,1,1)
port map (
	clk => end_0_clk,
	rst => end_0_rst,
	dataInArray(0) => end_0_dataInArray_2,
	eValidArray(0) => end_0_pValidArray_0,
	eValidArray(1) => end_0_pValidArray_1,
	pValidArray(0) => end_0_pValidArray_2,
	eReadyArray(0) => end_0_readyArray_0,
	eReadyArray(1) => end_0_readyArray_1,
	readyArray(0) => end_0_readyArray_2,
	dataOutArray(0) => end_0_dataOutArray_0,
	validArray(0) => end_0_validArray_0,
	nReadyArray(0) => end_0_nReadyArray_0
);

sink_1: entity work.sink(arch) generic map (1,0,32,32)
port map (
	clk => sink_1_clk,
	rst => sink_1_rst,
	dataInArray(0) => sink_1_dataInArray_0,
	pValidArray(0) => sink_1_pValidArray_0,
	readyArray(0) => sink_1_readyArray_0
);

sink_2: entity work.sink(arch) generic map (1,0,32,32)
port map (
	clk => sink_2_clk,
	rst => sink_2_rst,
	dataInArray(0) => sink_2_dataInArray_0,
	pValidArray(0) => sink_2_pValidArray_0,
	readyArray(0) => sink_2_readyArray_0
);

sink_3: entity work.sink(arch) generic map (1,0,32,32)
port map (
	clk => sink_3_clk,
	rst => sink_3_rst,
	dataInArray(0) => sink_3_dataInArray_0,
	pValidArray(0) => sink_3_pValidArray_0,
	readyArray(0) => sink_3_readyArray_0
);

sink_4: entity work.sink(arch) generic map (1,0,32,32)
port map (
	clk => sink_4_clk,
	rst => sink_4_rst,
	dataInArray(0) => sink_4_dataInArray_0,
	pValidArray(0) => sink_4_pValidArray_0,
	readyArray(0) => sink_4_readyArray_0
);

sink_5: entity work.sink(arch) generic map (1,0,1,32)
port map (
	clk => sink_5_clk,
	rst => sink_5_rst,
	dataInArray(0) => sink_5_dataInArray_0,
	pValidArray(0) => sink_5_pValidArray_0,
	readyArray(0) => sink_5_readyArray_0
);

sink_6: entity work.sink(arch) generic map (1,0,1,32)
port map (
	clk => sink_6_clk,
	rst => sink_6_rst,
	dataInArray(0) => sink_6_dataInArray_0,
	pValidArray(0) => sink_6_pValidArray_0,
	readyArray(0) => sink_6_readyArray_0
);

end behavioral; 
