#!/bin/bash
# # This is the installation script for the DASS compiler.
# Written by Jianyi Cheng, 24/01/2021

# --------------------------------------------------------------------
#                   Install Required packages
# --------------------------------------------------------------------

sudo apt-get update
sudo apt install graphviz clang cmake graphviz-dev pkg-config \
coinor-cbc g++ llvm libxtst6 xdg-utils desktop-file-utils \
libboost-regex1.65.1 python-pip clang-tools --assume-yes
pip install cxxfilt

exit 3
