-- ==============================================================
-- Generated by Dot2Vhdl ver. 0.21
-- File created: Wed Sep 16 13:47:59 2020

-- ==============================================================
library IEEE; 
use IEEE.std_logic_1164.all; 
use IEEE.numeric_std.all; 
use work.customTypes.all; 
-- ==============================================================
entity gSum is 
port (
	clk:  in std_logic;
	rst:  in std_logic;
	start_in:  in std_logic_vector (0 downto 0);
	start_valid:  in std_logic;
	start_ready:  out std_logic;
	end_out:  out std_logic_vector (31 downto 0);
	end_valid:  out std_logic;
	end_ready:  in std_logic;
	A_address0 : out std_logic_vector (31 downto 0);
	A_ce0 : out std_logic;
	A_we0 : out std_logic;
	A_dout0 : out std_logic_vector (31 downto 0);
	A_din0 : in std_logic_vector (31 downto 0);
	A_address1 : out std_logic_vector (31 downto 0);
	A_ce1 : out std_logic;
	A_we1 : out std_logic;
	A_dout1 : out std_logic_vector (31 downto 0);
	A_din1 : in std_logic_vector (31 downto 0));
end;

architecture behavioral of gSum is 

	signal brCst_block2_clk : std_logic;
	signal brCst_block2_rst : std_logic;
	signal brCst_block2_dataInArray_0 : std_logic_vector(0 downto 0);
	signal brCst_block2_pValidArray_0 : std_logic;
	signal brCst_block2_readyArray_0 : std_logic;
	signal brCst_block2_nReadyArray_0 : std_logic;
	signal brCst_block2_validArray_0 : std_logic;
	signal brCst_block2_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal cst_6_clk : std_logic;
	signal cst_6_rst : std_logic;
	signal cst_6_dataInArray_0 : std_logic_vector(31 downto 0);
	signal cst_6_pValidArray_0 : std_logic;
	signal cst_6_readyArray_0 : std_logic;
	signal cst_6_nReadyArray_0 : std_logic;
	signal cst_6_validArray_0 : std_logic;
	signal cst_6_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal cst_7_clk : std_logic;
	signal cst_7_rst : std_logic;
	signal cst_7_dataInArray_0 : std_logic_vector(31 downto 0);
	signal cst_7_pValidArray_0 : std_logic;
	signal cst_7_readyArray_0 : std_logic;
	signal cst_7_nReadyArray_0 : std_logic;
	signal cst_7_validArray_0 : std_logic;
	signal cst_7_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal branch_0_clk : std_logic;
	signal branch_0_rst : std_logic;
	signal branch_0_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_0_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branch_0_pValidArray_0 : std_logic;
	signal branch_0_pValidArray_1 : std_logic;
	signal branch_0_readyArray_0 : std_logic;
	signal branch_0_readyArray_1 : std_logic;
	signal branch_0_nReadyArray_0 : std_logic;
	signal branch_0_validArray_0 : std_logic;
	signal branch_0_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_0_nReadyArray_1 : std_logic;
	signal branch_0_validArray_1 : std_logic;
	signal branch_0_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal branch_1_clk : std_logic;
	signal branch_1_rst : std_logic;
	signal branch_1_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_1_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branch_1_pValidArray_0 : std_logic;
	signal branch_1_pValidArray_1 : std_logic;
	signal branch_1_readyArray_0 : std_logic;
	signal branch_1_readyArray_1 : std_logic;
	signal branch_1_nReadyArray_0 : std_logic;
	signal branch_1_validArray_0 : std_logic;
	signal branch_1_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_1_nReadyArray_1 : std_logic;
	signal branch_1_validArray_1 : std_logic;
	signal branch_1_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal fork_8_clk : std_logic;
	signal fork_8_rst : std_logic;
	signal fork_8_dataInArray_0 : std_logic_vector(0 downto 0);
	signal fork_8_pValidArray_0 : std_logic;
	signal fork_8_readyArray_0 : std_logic;
	signal fork_8_nReadyArray_0 : std_logic;
	signal fork_8_validArray_0 : std_logic;
	signal fork_8_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal fork_8_nReadyArray_1 : std_logic;
	signal fork_8_validArray_1 : std_logic;
	signal fork_8_dataOutArray_1 : std_logic_vector(0 downto 0);
	signal fork_8_nReadyArray_2 : std_logic;
	signal fork_8_validArray_2 : std_logic;
	signal fork_8_dataOutArray_2 : std_logic_vector(0 downto 0);

	signal start_1_clk : std_logic;
	signal start_1_rst : std_logic;
	signal start_1_dataInArray_0 : std_logic_vector(0 downto 0);
	signal start_1_pValidArray_0 : std_logic;
	signal start_1_readyArray_0 : std_logic;
	signal start_1_nReadyArray_0 : std_logic;
	signal start_1_validArray_0 : std_logic;
	signal start_1_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal forkC_13_clk : std_logic;
	signal forkC_13_rst : std_logic;
	signal forkC_13_dataInArray_0 : std_logic_vector(0 downto 0);
	signal forkC_13_pValidArray_0 : std_logic;
	signal forkC_13_readyArray_0 : std_logic;
	signal forkC_13_nReadyArray_0 : std_logic;
	signal forkC_13_validArray_0 : std_logic;
	signal forkC_13_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal forkC_13_nReadyArray_1 : std_logic;
	signal forkC_13_validArray_1 : std_logic;
	signal forkC_13_dataOutArray_1 : std_logic_vector(0 downto 0);
	signal forkC_13_nReadyArray_2 : std_logic;
	signal forkC_13_validArray_2 : std_logic;
	signal forkC_13_dataOutArray_2 : std_logic_vector(0 downto 0);
	signal forkC_13_nReadyArray_3 : std_logic;
	signal forkC_13_validArray_3 : std_logic;
	signal forkC_13_dataOutArray_3 : std_logic_vector(0 downto 0);

	signal branchC_9_clk : std_logic;
	signal branchC_9_rst : std_logic;
	signal branchC_9_dataInArray_0 : std_logic_vector(0 downto 0);
	signal branchC_9_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branchC_9_pValidArray_0 : std_logic;
	signal branchC_9_pValidArray_1 : std_logic;
	signal branchC_9_readyArray_0 : std_logic;
	signal branchC_9_readyArray_1 : std_logic;
	signal branchC_9_nReadyArray_0 : std_logic;
	signal branchC_9_validArray_0 : std_logic;
	signal branchC_9_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal branchC_9_nReadyArray_1 : std_logic;
	signal branchC_9_validArray_1 : std_logic;
	signal branchC_9_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal Buffer_3_clk : std_logic;
	signal Buffer_3_rst : std_logic;
	signal Buffer_3_dataInArray_0 : std_logic_vector(31 downto 0);
	signal Buffer_3_pValidArray_0 : std_logic;
	signal Buffer_3_readyArray_0 : std_logic;
	signal Buffer_3_nReadyArray_0 : std_logic;
	signal Buffer_3_validArray_0 : std_logic;
	signal Buffer_3_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal Buffer_4_clk : std_logic;
	signal Buffer_4_rst : std_logic;
	signal Buffer_4_dataInArray_0 : std_logic_vector(31 downto 0);
	signal Buffer_4_pValidArray_0 : std_logic;
	signal Buffer_4_readyArray_0 : std_logic;
	signal Buffer_4_nReadyArray_0 : std_logic;
	signal Buffer_4_validArray_0 : std_logic;
	signal Buffer_4_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal Buffer_9_clk : std_logic;
	signal Buffer_9_rst : std_logic;
	signal Buffer_9_dataInArray_0 : std_logic_vector(0 downto 0);
	signal Buffer_9_pValidArray_0 : std_logic;
	signal Buffer_9_readyArray_0 : std_logic;
	signal Buffer_9_nReadyArray_0 : std_logic;
	signal Buffer_9_validArray_0 : std_logic;
	signal Buffer_9_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal phi_12_clk : std_logic;
	signal phi_12_rst : std_logic;
	signal phi_12_dataInArray_0 : std_logic_vector(0 downto 0);
	signal phi_12_dataInArray_1 : std_logic_vector(31 downto 0);
	signal phi_12_dataInArray_2 : std_logic_vector(31 downto 0);
	signal phi_12_pValidArray_0 : std_logic;
	signal phi_12_pValidArray_1 : std_logic;
	signal phi_12_pValidArray_2 : std_logic;
	signal phi_12_readyArray_0 : std_logic;
	signal phi_12_readyArray_1 : std_logic;
	signal phi_12_readyArray_2 : std_logic;
	signal phi_12_nReadyArray_0 : std_logic;
	signal phi_12_validArray_0 : std_logic;
	signal phi_12_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal phi_13_clk : std_logic;
	signal phi_13_rst : std_logic;
	signal phi_13_dataInArray_0 : std_logic_vector(0 downto 0);
	signal phi_13_dataInArray_1 : std_logic_vector(31 downto 0);
	signal phi_13_dataInArray_2 : std_logic_vector(31 downto 0);
	signal phi_13_pValidArray_0 : std_logic;
	signal phi_13_pValidArray_1 : std_logic;
	signal phi_13_pValidArray_2 : std_logic;
	signal phi_13_readyArray_0 : std_logic;
	signal phi_13_readyArray_1 : std_logic;
	signal phi_13_readyArray_2 : std_logic;
	signal phi_13_nReadyArray_0 : std_logic;
	signal phi_13_validArray_0 : std_logic;
	signal phi_13_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal load_16_clk : std_logic;
	signal load_16_rst : std_logic;
	signal load_16_dataInArray_0 : std_logic_vector(31 downto 0);
	signal load_16_dataInArray_1 : std_logic_vector(31 downto 0);
	signal load_16_pValidArray_0 : std_logic;
	signal load_16_pValidArray_1 : std_logic;
	signal load_16_readyArray_0 : std_logic;
	signal load_16_readyArray_1 : std_logic;
	signal load_16_nReadyArray_0 : std_logic;
	signal load_16_validArray_0 : std_logic;
	signal load_16_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal load_16_nReadyArray_1 : std_logic;
	signal load_16_validArray_1 : std_logic;
	signal load_16_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal cst_8_clk : std_logic;
	signal cst_8_rst : std_logic;
	signal cst_8_dataInArray_0 : std_logic_vector(31 downto 0);
	signal cst_8_pValidArray_0 : std_logic;
	signal cst_8_readyArray_0 : std_logic;
	signal cst_8_nReadyArray_0 : std_logic;
	signal cst_8_validArray_0 : std_logic;
	signal cst_8_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal icmp_17_clk : std_logic;
	signal icmp_17_rst : std_logic;
	signal icmp_17_dataInArray_0 : std_logic_vector(31 downto 0);
	signal icmp_17_dataInArray_1 : std_logic_vector(31 downto 0);
	signal icmp_17_pValidArray_0 : std_logic;
	signal icmp_17_pValidArray_1 : std_logic;
	signal icmp_17_readyArray_0 : std_logic;
	signal icmp_17_readyArray_1 : std_logic;
	signal icmp_17_nReadyArray_0 : std_logic;
	signal icmp_17_validArray_0 : std_logic;
	signal icmp_17_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal fork_4_clk : std_logic;
	signal fork_4_rst : std_logic;
	signal fork_4_dataInArray_0 : std_logic_vector(31 downto 0);
	signal fork_4_pValidArray_0 : std_logic;
	signal fork_4_readyArray_0 : std_logic;
	signal fork_4_nReadyArray_0 : std_logic;
	signal fork_4_validArray_0 : std_logic;
	signal fork_4_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal fork_4_nReadyArray_1 : std_logic;
	signal fork_4_validArray_1 : std_logic;
	signal fork_4_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal fork_5_clk : std_logic;
	signal fork_5_rst : std_logic;
	signal fork_5_dataInArray_0 : std_logic_vector(31 downto 0);
	signal fork_5_pValidArray_0 : std_logic;
	signal fork_5_readyArray_0 : std_logic;
	signal fork_5_nReadyArray_0 : std_logic;
	signal fork_5_validArray_0 : std_logic;
	signal fork_5_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal fork_5_nReadyArray_1 : std_logic;
	signal fork_5_validArray_1 : std_logic;
	signal fork_5_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal branch_2_clk : std_logic;
	signal branch_2_rst : std_logic;
	signal branch_2_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_2_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branch_2_pValidArray_0 : std_logic;
	signal branch_2_pValidArray_1 : std_logic;
	signal branch_2_readyArray_0 : std_logic;
	signal branch_2_readyArray_1 : std_logic;
	signal branch_2_nReadyArray_0 : std_logic;
	signal branch_2_validArray_0 : std_logic;
	signal branch_2_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_2_nReadyArray_1 : std_logic;
	signal branch_2_validArray_1 : std_logic;
	signal branch_2_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal branch_3_clk : std_logic;
	signal branch_3_rst : std_logic;
	signal branch_3_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_3_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branch_3_pValidArray_0 : std_logic;
	signal branch_3_pValidArray_1 : std_logic;
	signal branch_3_readyArray_0 : std_logic;
	signal branch_3_readyArray_1 : std_logic;
	signal branch_3_nReadyArray_0 : std_logic;
	signal branch_3_validArray_0 : std_logic;
	signal branch_3_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_3_nReadyArray_1 : std_logic;
	signal branch_3_validArray_1 : std_logic;
	signal branch_3_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal branch_4_clk : std_logic;
	signal branch_4_rst : std_logic;
	signal branch_4_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_4_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branch_4_pValidArray_0 : std_logic;
	signal branch_4_pValidArray_1 : std_logic;
	signal branch_4_readyArray_0 : std_logic;
	signal branch_4_readyArray_1 : std_logic;
	signal branch_4_nReadyArray_0 : std_logic;
	signal branch_4_validArray_0 : std_logic;
	signal branch_4_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_4_nReadyArray_1 : std_logic;
	signal branch_4_validArray_1 : std_logic;
	signal branch_4_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal fork_9_clk : std_logic;
	signal fork_9_rst : std_logic;
	signal fork_9_dataInArray_0 : std_logic_vector(0 downto 0);
	signal fork_9_pValidArray_0 : std_logic;
	signal fork_9_readyArray_0 : std_logic;
	signal fork_9_nReadyArray_0 : std_logic;
	signal fork_9_validArray_0 : std_logic;
	signal fork_9_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal fork_9_nReadyArray_1 : std_logic;
	signal fork_9_validArray_1 : std_logic;
	signal fork_9_dataOutArray_1 : std_logic_vector(0 downto 0);
	signal fork_9_nReadyArray_2 : std_logic;
	signal fork_9_validArray_2 : std_logic;
	signal fork_9_dataOutArray_2 : std_logic_vector(0 downto 0);
	signal fork_9_nReadyArray_3 : std_logic;
	signal fork_9_validArray_3 : std_logic;
	signal fork_9_dataOutArray_3 : std_logic_vector(0 downto 0);

	signal phiC_5_clk : std_logic;
	signal phiC_5_rst : std_logic;
	signal phiC_5_dataInArray_0 : std_logic_vector(0 downto 0);
	signal phiC_5_dataInArray_1 : std_logic_vector(0 downto 0);
	signal phiC_5_pValidArray_0 : std_logic;
	signal phiC_5_pValidArray_1 : std_logic;
	signal phiC_5_readyArray_0 : std_logic;
	signal phiC_5_readyArray_1 : std_logic;
	signal phiC_5_nReadyArray_0 : std_logic;
	signal phiC_5_validArray_0 : std_logic;
	signal phiC_5_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal phiC_5_nReadyArray_1 : std_logic;
	signal phiC_5_validArray_1 : std_logic;
	signal phiC_5_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal branchC_10_clk : std_logic;
	signal branchC_10_rst : std_logic;
	signal branchC_10_dataInArray_0 : std_logic_vector(0 downto 0);
	signal branchC_10_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branchC_10_pValidArray_0 : std_logic;
	signal branchC_10_pValidArray_1 : std_logic;
	signal branchC_10_readyArray_0 : std_logic;
	signal branchC_10_readyArray_1 : std_logic;
	signal branchC_10_nReadyArray_0 : std_logic;
	signal branchC_10_validArray_0 : std_logic;
	signal branchC_10_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal branchC_10_nReadyArray_1 : std_logic;
	signal branchC_10_validArray_1 : std_logic;
	signal branchC_10_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal source_6_clk : std_logic;
	signal source_6_rst : std_logic;
	signal source_6_nReadyArray_0 : std_logic;
	signal source_6_validArray_0 : std_logic;
	signal source_6_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal fork_18_clk : std_logic;
	signal fork_18_rst : std_logic;
	signal fork_18_dataInArray_0 : std_logic_vector(0 downto 0);
	signal fork_18_pValidArray_0 : std_logic;
	signal fork_18_readyArray_0 : std_logic;
	signal fork_18_nReadyArray_0 : std_logic;
	signal fork_18_validArray_0 : std_logic;
	signal fork_18_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal fork_18_nReadyArray_1 : std_logic;
	signal fork_18_validArray_1 : std_logic;
	signal fork_18_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal Buffer_1_clk : std_logic;
	signal Buffer_1_rst : std_logic;
	signal Buffer_1_dataInArray_0 : std_logic_vector(31 downto 0);
	signal Buffer_1_pValidArray_0 : std_logic;
	signal Buffer_1_readyArray_0 : std_logic;
	signal Buffer_1_nReadyArray_0 : std_logic;
	signal Buffer_1_validArray_0 : std_logic;
	signal Buffer_1_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal Buffer_2_clk : std_logic;
	signal Buffer_2_rst : std_logic;
	signal Buffer_2_dataInArray_0 : std_logic_vector(31 downto 0);
	signal Buffer_2_pValidArray_0 : std_logic;
	signal Buffer_2_readyArray_0 : std_logic;
	signal Buffer_2_nReadyArray_0 : std_logic;
	signal Buffer_2_validArray_0 : std_logic;
	signal Buffer_2_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal Buffer_5_clk : std_logic;
	signal Buffer_5_rst : std_logic;
	signal Buffer_5_dataInArray_0 : std_logic_vector(0 downto 0);
	signal Buffer_5_pValidArray_0 : std_logic;
	signal Buffer_5_readyArray_0 : std_logic;
	signal Buffer_5_nReadyArray_0 : std_logic;
	signal Buffer_5_validArray_0 : std_logic;
	signal Buffer_5_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal Buffer_10_clk : std_logic;
	signal Buffer_10_rst : std_logic;
	signal Buffer_10_dataInArray_0 : std_logic_vector(0 downto 0);
	signal Buffer_10_pValidArray_0 : std_logic;
	signal Buffer_10_readyArray_0 : std_logic;
	signal Buffer_10_nReadyArray_0 : std_logic;
	signal Buffer_10_validArray_0 : std_logic;
	signal Buffer_10_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal Buffer_13_clk : std_logic;
	signal Buffer_13_rst : std_logic;
	signal Buffer_13_dataInArray_0 : std_logic_vector(0 downto 0);
	signal Buffer_13_pValidArray_0 : std_logic;
	signal Buffer_13_readyArray_0 : std_logic;
	signal Buffer_13_nReadyArray_0 : std_logic;
	signal Buffer_13_validArray_0 : std_logic;
	signal Buffer_13_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal call_0_clk : std_logic;
	signal call_0_rst : std_logic;
	signal call_0_dataInArray_0 : std_logic_vector(31 downto 0);
	signal call_0_pValidArray_0 : std_logic;
	signal call_0_readyArray_0 : std_logic;
	signal call_0_nReadyArray_0 : std_logic;
	signal call_0_validArray_0 : std_logic;
	signal call_0_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal add_19_clk : std_logic;
	signal add_19_rst : std_logic;
	signal add_19_dataInArray_0 : std_logic_vector(31 downto 0);
	signal add_19_dataInArray_1 : std_logic_vector(31 downto 0);
	signal add_19_pValidArray_0 : std_logic;
	signal add_19_pValidArray_1 : std_logic;
	signal add_19_readyArray_0 : std_logic;
	signal add_19_readyArray_1 : std_logic;
	signal add_19_nReadyArray_0 : std_logic;
	signal add_19_validArray_0 : std_logic;
	signal add_19_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal brCst_block4_clk : std_logic;
	signal brCst_block4_rst : std_logic;
	signal brCst_block4_dataInArray_0 : std_logic_vector(0 downto 0);
	signal brCst_block4_pValidArray_0 : std_logic;
	signal brCst_block4_readyArray_0 : std_logic;
	signal brCst_block4_nReadyArray_0 : std_logic;
	signal brCst_block4_validArray_0 : std_logic;
	signal brCst_block4_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal phi_n1_clk : std_logic;
	signal phi_n1_rst : std_logic;
	signal phi_n1_dataInArray_0 : std_logic_vector(31 downto 0);
	signal phi_n1_pValidArray_0 : std_logic;
	signal phi_n1_readyArray_0 : std_logic;
	signal phi_n1_nReadyArray_0 : std_logic;
	signal phi_n1_validArray_0 : std_logic;
	signal phi_n1_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal phi_n2_clk : std_logic;
	signal phi_n2_rst : std_logic;
	signal phi_n2_dataInArray_0 : std_logic_vector(31 downto 0);
	signal phi_n2_pValidArray_0 : std_logic;
	signal phi_n2_readyArray_0 : std_logic;
	signal phi_n2_nReadyArray_0 : std_logic;
	signal phi_n2_validArray_0 : std_logic;
	signal phi_n2_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal phi_n3_clk : std_logic;
	signal phi_n3_rst : std_logic;
	signal phi_n3_dataInArray_0 : std_logic_vector(31 downto 0);
	signal phi_n3_pValidArray_0 : std_logic;
	signal phi_n3_readyArray_0 : std_logic;
	signal phi_n3_nReadyArray_0 : std_logic;
	signal phi_n3_validArray_0 : std_logic;
	signal phi_n3_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal branch_5_clk : std_logic;
	signal branch_5_rst : std_logic;
	signal branch_5_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_5_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branch_5_pValidArray_0 : std_logic;
	signal branch_5_pValidArray_1 : std_logic;
	signal branch_5_readyArray_0 : std_logic;
	signal branch_5_readyArray_1 : std_logic;
	signal branch_5_nReadyArray_0 : std_logic;
	signal branch_5_validArray_0 : std_logic;
	signal branch_5_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_5_nReadyArray_1 : std_logic;
	signal branch_5_validArray_1 : std_logic;
	signal branch_5_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal branch_6_clk : std_logic;
	signal branch_6_rst : std_logic;
	signal branch_6_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_6_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branch_6_pValidArray_0 : std_logic;
	signal branch_6_pValidArray_1 : std_logic;
	signal branch_6_readyArray_0 : std_logic;
	signal branch_6_readyArray_1 : std_logic;
	signal branch_6_nReadyArray_0 : std_logic;
	signal branch_6_validArray_0 : std_logic;
	signal branch_6_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_6_nReadyArray_1 : std_logic;
	signal branch_6_validArray_1 : std_logic;
	signal branch_6_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal fork_10_clk : std_logic;
	signal fork_10_rst : std_logic;
	signal fork_10_dataInArray_0 : std_logic_vector(0 downto 0);
	signal fork_10_pValidArray_0 : std_logic;
	signal fork_10_readyArray_0 : std_logic;
	signal fork_10_nReadyArray_0 : std_logic;
	signal fork_10_validArray_0 : std_logic;
	signal fork_10_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal fork_10_nReadyArray_1 : std_logic;
	signal fork_10_validArray_1 : std_logic;
	signal fork_10_dataOutArray_1 : std_logic_vector(0 downto 0);
	signal fork_10_nReadyArray_2 : std_logic;
	signal fork_10_validArray_2 : std_logic;
	signal fork_10_dataOutArray_2 : std_logic_vector(0 downto 0);

	signal phiC_6_clk : std_logic;
	signal phiC_6_rst : std_logic;
	signal phiC_6_dataInArray_0 : std_logic_vector(0 downto 0);
	signal phiC_6_pValidArray_0 : std_logic;
	signal phiC_6_readyArray_0 : std_logic;
	signal phiC_6_nReadyArray_0 : std_logic;
	signal phiC_6_validArray_0 : std_logic;
	signal phiC_6_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal forkC_15_clk : std_logic;
	signal forkC_15_rst : std_logic;
	signal forkC_15_dataInArray_0 : std_logic_vector(0 downto 0);
	signal forkC_15_pValidArray_0 : std_logic;
	signal forkC_15_readyArray_0 : std_logic;
	signal forkC_15_nReadyArray_0 : std_logic;
	signal forkC_15_validArray_0 : std_logic;
	signal forkC_15_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal forkC_15_nReadyArray_1 : std_logic;
	signal forkC_15_validArray_1 : std_logic;
	signal forkC_15_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal branchC_11_clk : std_logic;
	signal branchC_11_rst : std_logic;
	signal branchC_11_dataInArray_0 : std_logic_vector(0 downto 0);
	signal branchC_11_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branchC_11_pValidArray_0 : std_logic;
	signal branchC_11_pValidArray_1 : std_logic;
	signal branchC_11_readyArray_0 : std_logic;
	signal branchC_11_readyArray_1 : std_logic;
	signal branchC_11_nReadyArray_0 : std_logic;
	signal branchC_11_validArray_0 : std_logic;
	signal branchC_11_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal branchC_11_nReadyArray_1 : std_logic;
	signal branchC_11_validArray_1 : std_logic;
	signal branchC_11_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal Buffer_6_clk : std_logic;
	signal Buffer_6_rst : std_logic;
	signal Buffer_6_dataInArray_0 : std_logic_vector(0 downto 0);
	signal Buffer_6_pValidArray_0 : std_logic;
	signal Buffer_6_readyArray_0 : std_logic;
	signal Buffer_6_nReadyArray_0 : std_logic;
	signal Buffer_6_validArray_0 : std_logic;
	signal Buffer_6_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal phi_21_clk : std_logic;
	signal phi_21_rst : std_logic;
	signal phi_21_dataInArray_0 : std_logic_vector(0 downto 0);
	signal phi_21_dataInArray_1 : std_logic_vector(31 downto 0);
	signal phi_21_dataInArray_2 : std_logic_vector(31 downto 0);
	signal phi_21_pValidArray_0 : std_logic;
	signal phi_21_pValidArray_1 : std_logic;
	signal phi_21_pValidArray_2 : std_logic;
	signal phi_21_readyArray_0 : std_logic;
	signal phi_21_readyArray_1 : std_logic;
	signal phi_21_readyArray_2 : std_logic;
	signal phi_21_nReadyArray_0 : std_logic;
	signal phi_21_validArray_0 : std_logic;
	signal phi_21_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal cst_9_clk : std_logic;
	signal cst_9_rst : std_logic;
	signal cst_9_dataInArray_0 : std_logic_vector(31 downto 0);
	signal cst_9_pValidArray_0 : std_logic;
	signal cst_9_readyArray_0 : std_logic;
	signal cst_9_nReadyArray_0 : std_logic;
	signal cst_9_validArray_0 : std_logic;
	signal cst_9_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal add_22_clk : std_logic;
	signal add_22_rst : std_logic;
	signal add_22_dataInArray_0 : std_logic_vector(31 downto 0);
	signal add_22_dataInArray_1 : std_logic_vector(31 downto 0);
	signal add_22_pValidArray_0 : std_logic;
	signal add_22_pValidArray_1 : std_logic;
	signal add_22_readyArray_0 : std_logic;
	signal add_22_readyArray_1 : std_logic;
	signal add_22_nReadyArray_0 : std_logic;
	signal add_22_validArray_0 : std_logic;
	signal add_22_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal cst_10_clk : std_logic;
	signal cst_10_rst : std_logic;
	signal cst_10_dataInArray_0 : std_logic_vector(31 downto 0);
	signal cst_10_pValidArray_0 : std_logic;
	signal cst_10_readyArray_0 : std_logic;
	signal cst_10_nReadyArray_0 : std_logic;
	signal cst_10_validArray_0 : std_logic;
	signal cst_10_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal icmp_23_clk : std_logic;
	signal icmp_23_rst : std_logic;
	signal icmp_23_dataInArray_0 : std_logic_vector(31 downto 0);
	signal icmp_23_dataInArray_1 : std_logic_vector(31 downto 0);
	signal icmp_23_pValidArray_0 : std_logic;
	signal icmp_23_pValidArray_1 : std_logic;
	signal icmp_23_readyArray_0 : std_logic;
	signal icmp_23_readyArray_1 : std_logic;
	signal icmp_23_nReadyArray_0 : std_logic;
	signal icmp_23_validArray_0 : std_logic;
	signal icmp_23_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal phi_n0_clk : std_logic;
	signal phi_n0_rst : std_logic;
	signal phi_n0_dataInArray_0 : std_logic_vector(31 downto 0);
	signal phi_n0_dataInArray_1 : std_logic_vector(31 downto 0);
	signal phi_n0_pValidArray_0 : std_logic;
	signal phi_n0_pValidArray_1 : std_logic;
	signal phi_n0_readyArray_0 : std_logic;
	signal phi_n0_readyArray_1 : std_logic;
	signal phi_n0_nReadyArray_0 : std_logic;
	signal phi_n0_validArray_0 : std_logic;
	signal phi_n0_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal fork_7_clk : std_logic;
	signal fork_7_rst : std_logic;
	signal fork_7_dataInArray_0 : std_logic_vector(31 downto 0);
	signal fork_7_pValidArray_0 : std_logic;
	signal fork_7_readyArray_0 : std_logic;
	signal fork_7_nReadyArray_0 : std_logic;
	signal fork_7_validArray_0 : std_logic;
	signal fork_7_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal fork_7_nReadyArray_1 : std_logic;
	signal fork_7_validArray_1 : std_logic;
	signal fork_7_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal branch_7_clk : std_logic;
	signal branch_7_rst : std_logic;
	signal branch_7_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_7_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branch_7_pValidArray_0 : std_logic;
	signal branch_7_pValidArray_1 : std_logic;
	signal branch_7_readyArray_0 : std_logic;
	signal branch_7_readyArray_1 : std_logic;
	signal branch_7_nReadyArray_0 : std_logic;
	signal branch_7_validArray_0 : std_logic;
	signal branch_7_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_7_nReadyArray_1 : std_logic;
	signal branch_7_validArray_1 : std_logic;
	signal branch_7_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal branch_8_clk : std_logic;
	signal branch_8_rst : std_logic;
	signal branch_8_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_8_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branch_8_pValidArray_0 : std_logic;
	signal branch_8_pValidArray_1 : std_logic;
	signal branch_8_readyArray_0 : std_logic;
	signal branch_8_readyArray_1 : std_logic;
	signal branch_8_nReadyArray_0 : std_logic;
	signal branch_8_validArray_0 : std_logic;
	signal branch_8_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_8_nReadyArray_1 : std_logic;
	signal branch_8_validArray_1 : std_logic;
	signal branch_8_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal fork_11_clk : std_logic;
	signal fork_11_rst : std_logic;
	signal fork_11_dataInArray_0 : std_logic_vector(0 downto 0);
	signal fork_11_pValidArray_0 : std_logic;
	signal fork_11_readyArray_0 : std_logic;
	signal fork_11_nReadyArray_0 : std_logic;
	signal fork_11_validArray_0 : std_logic;
	signal fork_11_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal fork_11_nReadyArray_1 : std_logic;
	signal fork_11_validArray_1 : std_logic;
	signal fork_11_dataOutArray_1 : std_logic_vector(0 downto 0);
	signal fork_11_nReadyArray_2 : std_logic;
	signal fork_11_validArray_2 : std_logic;
	signal fork_11_dataOutArray_2 : std_logic_vector(0 downto 0);

	signal phiC_7_clk : std_logic;
	signal phiC_7_rst : std_logic;
	signal phiC_7_dataInArray_0 : std_logic_vector(0 downto 0);
	signal phiC_7_dataInArray_1 : std_logic_vector(0 downto 0);
	signal phiC_7_pValidArray_0 : std_logic;
	signal phiC_7_pValidArray_1 : std_logic;
	signal phiC_7_readyArray_0 : std_logic;
	signal phiC_7_readyArray_1 : std_logic;
	signal phiC_7_nReadyArray_0 : std_logic;
	signal phiC_7_validArray_0 : std_logic;
	signal phiC_7_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal phiC_7_nReadyArray_1 : std_logic;
	signal phiC_7_validArray_1 : std_logic;
	signal phiC_7_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal branchC_12_clk : std_logic;
	signal branchC_12_rst : std_logic;
	signal branchC_12_dataInArray_0 : std_logic_vector(0 downto 0);
	signal branchC_12_dataInArray_1 : std_logic_vector (0 downto 0);
	signal branchC_12_pValidArray_0 : std_logic;
	signal branchC_12_pValidArray_1 : std_logic;
	signal branchC_12_readyArray_0 : std_logic;
	signal branchC_12_readyArray_1 : std_logic;
	signal branchC_12_nReadyArray_0 : std_logic;
	signal branchC_12_validArray_0 : std_logic;
	signal branchC_12_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal branchC_12_nReadyArray_1 : std_logic;
	signal branchC_12_validArray_1 : std_logic;
	signal branchC_12_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal source_7_clk : std_logic;
	signal source_7_rst : std_logic;
	signal source_7_nReadyArray_0 : std_logic;
	signal source_7_validArray_0 : std_logic;
	signal source_7_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal source_8_clk : std_logic;
	signal source_8_rst : std_logic;
	signal source_8_nReadyArray_0 : std_logic;
	signal source_8_validArray_0 : std_logic;
	signal source_8_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal Buffer_7_clk : std_logic;
	signal Buffer_7_rst : std_logic;
	signal Buffer_7_dataInArray_0 : std_logic_vector(31 downto 0);
	signal Buffer_7_pValidArray_0 : std_logic;
	signal Buffer_7_readyArray_0 : std_logic;
	signal Buffer_7_nReadyArray_0 : std_logic;
	signal Buffer_7_validArray_0 : std_logic;
	signal Buffer_7_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal Buffer_8_clk : std_logic;
	signal Buffer_8_rst : std_logic;
	signal Buffer_8_dataInArray_0 : std_logic_vector(0 downto 0);
	signal Buffer_8_pValidArray_0 : std_logic;
	signal Buffer_8_readyArray_0 : std_logic;
	signal Buffer_8_nReadyArray_0 : std_logic;
	signal Buffer_8_validArray_0 : std_logic;
	signal Buffer_8_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal Buffer_11_clk : std_logic;
	signal Buffer_11_rst : std_logic;
	signal Buffer_11_dataInArray_0 : std_logic_vector(0 downto 0);
	signal Buffer_11_pValidArray_0 : std_logic;
	signal Buffer_11_readyArray_0 : std_logic;
	signal Buffer_11_nReadyArray_0 : std_logic;
	signal Buffer_11_validArray_0 : std_logic;
	signal Buffer_11_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal Buffer_12_clk : std_logic;
	signal Buffer_12_rst : std_logic;
	signal Buffer_12_dataInArray_0 : std_logic_vector(0 downto 0);
	signal Buffer_12_pValidArray_0 : std_logic;
	signal Buffer_12_readyArray_0 : std_logic;
	signal Buffer_12_nReadyArray_0 : std_logic;
	signal Buffer_12_validArray_0 : std_logic;
	signal Buffer_12_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal ret_1_clk : std_logic;
	signal ret_1_rst : std_logic;
	signal ret_1_dataInArray_0 : std_logic_vector(31 downto 0);
	signal ret_1_pValidArray_0 : std_logic;
	signal ret_1_readyArray_0 : std_logic;
	signal ret_1_nReadyArray_0 : std_logic;
	signal ret_1_validArray_0 : std_logic;
	signal ret_1_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal phi_n4_clk : std_logic;
	signal phi_n4_rst : std_logic;
	signal phi_n4_dataInArray_0 : std_logic_vector(31 downto 0);
	signal phi_n4_pValidArray_0 : std_logic;
	signal phi_n4_readyArray_0 : std_logic;
	signal phi_n4_nReadyArray_0 : std_logic;
	signal phi_n4_validArray_0 : std_logic;
	signal phi_n4_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal phiC_8_clk : std_logic;
	signal phiC_8_rst : std_logic;
	signal phiC_8_dataInArray_0 : std_logic_vector(0 downto 0);
	signal phiC_8_pValidArray_0 : std_logic;
	signal phiC_8_readyArray_0 : std_logic;
	signal phiC_8_nReadyArray_0 : std_logic;
	signal phiC_8_validArray_0 : std_logic;
	signal phiC_8_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal MC_A_clk : std_logic;
	signal MC_A_rst : std_logic;
	signal MC_A_dataInArray_0 : std_logic_vector(31 downto 0);
	signal MC_A_dataInArray_1 : std_logic_vector(31 downto 0);
	signal MC_A_dataInArray_2 : std_logic_vector(31 downto 0);
	signal MC_A_dataInArray_3 : std_logic_vector(31 downto 0);
	signal MC_A_pValidArray_0 : std_logic;
	signal MC_A_pValidArray_1 : std_logic;
	signal MC_A_pValidArray_2 : std_logic;
	signal MC_A_pValidArray_3 : std_logic;
	signal MC_A_readyArray_0 : std_logic;
	signal MC_A_readyArray_1 : std_logic;
	signal MC_A_readyArray_2 : std_logic;
	signal MC_A_readyArray_3 : std_logic;
	signal MC_A_nReadyArray_0 : std_logic;
	signal MC_A_validArray_0 : std_logic;
	signal MC_A_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal MC_A_nReadyArray_1 : std_logic;
	signal MC_A_validArray_1 : std_logic;
	signal MC_A_dataOutArray_1 : std_logic_vector(0 downto 0);
	signal MC_A_we0_ce0 : std_logic;

	signal end_0_clk : std_logic;
	signal end_0_rst : std_logic;
	signal end_0_dataInArray_0 : std_logic_vector(0 downto 0);
	signal end_0_dataInArray_1 : std_logic_vector(31 downto 0);
	signal end_0_pValidArray_0 : std_logic;
	signal end_0_pValidArray_1 : std_logic;
	signal end_0_readyArray_0 : std_logic;
	signal end_0_readyArray_1 : std_logic;
	signal end_0_nReadyArray_0 : std_logic;
	signal end_0_validArray_0 : std_logic;
	signal end_0_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal end_0_validArray_1 :  std_logic;
	signal end_0_dataOutArray_1 :  std_logic_vector (31 downto 0);
	signal end_0_nReadyArray_1 :  std_logic;

	signal sink_1_clk : std_logic;
	signal sink_1_rst : std_logic;
	signal sink_1_dataInArray_0 : std_logic_vector(0 downto 0);
	signal sink_1_pValidArray_0 : std_logic;
	signal sink_1_readyArray_0 : std_logic;

	signal sink_2_clk : std_logic;
	signal sink_2_rst : std_logic;
	signal sink_2_dataInArray_0 : std_logic_vector(31 downto 0);
	signal sink_2_pValidArray_0 : std_logic;
	signal sink_2_readyArray_0 : std_logic;

	signal sink_3_clk : std_logic;
	signal sink_3_rst : std_logic;
	signal sink_3_dataInArray_0 : std_logic_vector(31 downto 0);
	signal sink_3_pValidArray_0 : std_logic;
	signal sink_3_readyArray_0 : std_logic;

	signal sink_4_clk : std_logic;
	signal sink_4_rst : std_logic;
	signal sink_4_dataInArray_0 : std_logic_vector(31 downto 0);
	signal sink_4_pValidArray_0 : std_logic;
	signal sink_4_readyArray_0 : std_logic;

	signal sink_5_clk : std_logic;
	signal sink_5_rst : std_logic;
	signal sink_5_dataInArray_0 : std_logic_vector(31 downto 0);
	signal sink_5_pValidArray_0 : std_logic;
	signal sink_5_readyArray_0 : std_logic;

	signal sink_6_clk : std_logic;
	signal sink_6_rst : std_logic;
	signal sink_6_dataInArray_0 : std_logic_vector(31 downto 0);
	signal sink_6_pValidArray_0 : std_logic;
	signal sink_6_readyArray_0 : std_logic;

	signal sink_7_clk : std_logic;
	signal sink_7_rst : std_logic;
	signal sink_7_dataInArray_0 : std_logic_vector(31 downto 0);
	signal sink_7_pValidArray_0 : std_logic;
	signal sink_7_readyArray_0 : std_logic;

	signal sink_8_clk : std_logic;
	signal sink_8_rst : std_logic;
	signal sink_8_dataInArray_0 : std_logic_vector(0 downto 0);
	signal sink_8_pValidArray_0 : std_logic;
	signal sink_8_readyArray_0 : std_logic;

	signal sink_9_clk : std_logic;
	signal sink_9_rst : std_logic;
	signal sink_9_dataInArray_0 : std_logic_vector(0 downto 0);
	signal sink_9_pValidArray_0 : std_logic;
	signal sink_9_readyArray_0 : std_logic;

begin


	brCst_block2_clk <= clk;
	brCst_block2_rst <= rst;
	fork_8_pValidArray_0 <= brCst_block2_validArray_0;
	brCst_block2_nReadyArray_0 <= fork_8_readyArray_0;
	fork_8_dataInArray_0 <= std_logic_vector (resize(unsigned(brCst_block2_dataOutArray_0),fork_8_dataInArray_0'length));

	cst_6_clk <= clk;
	cst_6_rst <= rst;
	branch_0_pValidArray_0 <= cst_6_validArray_0;
	cst_6_nReadyArray_0 <= branch_0_readyArray_0;
	branch_0_dataInArray_0 <= std_logic_vector (resize(unsigned(cst_6_dataOutArray_0),branch_0_dataInArray_0'length));

	cst_7_clk <= clk;
	cst_7_rst <= rst;
	branch_1_pValidArray_0 <= cst_7_validArray_0;
	cst_7_nReadyArray_0 <= branch_1_readyArray_0;
	branch_1_dataInArray_0 <= std_logic_vector (resize(unsigned(cst_7_dataOutArray_0),branch_1_dataInArray_0'length));

	branch_0_clk <= clk;
	branch_0_rst <= rst;
	Buffer_3_pValidArray_0 <= branch_0_validArray_0;
	branch_0_nReadyArray_0 <= Buffer_3_readyArray_0;
	Buffer_3_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_0_dataOutArray_0),Buffer_3_dataInArray_0'length));
	sink_2_pValidArray_0 <= branch_0_validArray_1;
	branch_0_nReadyArray_1 <= sink_2_readyArray_0;
	sink_2_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_0_dataOutArray_1),sink_2_dataInArray_0'length));

	branch_1_clk <= clk;
	branch_1_rst <= rst;
	Buffer_4_pValidArray_0 <= branch_1_validArray_0;
	branch_1_nReadyArray_0 <= Buffer_4_readyArray_0;
	Buffer_4_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_1_dataOutArray_0),Buffer_4_dataInArray_0'length));
	sink_3_pValidArray_0 <= branch_1_validArray_1;
	branch_1_nReadyArray_1 <= sink_3_readyArray_0;
	sink_3_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_1_dataOutArray_1),sink_3_dataInArray_0'length));

	fork_8_clk <= clk;
	fork_8_rst <= rst;
	branch_1_pValidArray_1 <= fork_8_validArray_0;
	fork_8_nReadyArray_0 <= branch_1_readyArray_1;
	branch_1_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_8_dataOutArray_0),branch_1_dataInArray_1'length));
	branch_0_pValidArray_1 <= fork_8_validArray_1;
	fork_8_nReadyArray_1 <= branch_0_readyArray_1;
	branch_0_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_8_dataOutArray_1),branch_0_dataInArray_1'length));
	branchC_9_pValidArray_1 <= fork_8_validArray_2;
	fork_8_nReadyArray_2 <= branchC_9_readyArray_1;
	branchC_9_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_8_dataOutArray_2),branchC_9_dataInArray_1'length));

	start_1_clk <= clk;
	start_1_rst <= rst;
	start_1_pValidArray_0 <= start_valid;
	start_ready <= start_1_readyArray_0;
	forkC_13_pValidArray_0 <= start_1_validArray_0;
	start_1_nReadyArray_0 <= forkC_13_readyArray_0;
	forkC_13_dataInArray_0 <= std_logic_vector (resize(unsigned(start_1_dataOutArray_0),forkC_13_dataInArray_0'length));

	forkC_13_clk <= clk;
	forkC_13_rst <= rst;
	cst_6_pValidArray_0 <= forkC_13_validArray_0;
	forkC_13_nReadyArray_0 <= cst_6_readyArray_0;
	cst_6_dataInArray_0 <= "00000000000000000000000000000000";
	cst_7_pValidArray_0 <= forkC_13_validArray_1;
	forkC_13_nReadyArray_1 <= cst_7_readyArray_0;
	cst_7_dataInArray_0 <= "00000000000000000000000000000000";
	branchC_9_pValidArray_0 <= forkC_13_validArray_2;
	forkC_13_nReadyArray_2 <= branchC_9_readyArray_0;
	branchC_9_dataInArray_0 <= std_logic_vector (resize(unsigned(forkC_13_dataOutArray_2),branchC_9_dataInArray_0'length));
	brCst_block2_pValidArray_0 <= forkC_13_validArray_3;
	forkC_13_nReadyArray_3 <= brCst_block2_readyArray_0;
	brCst_block2_dataInArray_0 <= "1";

	branchC_9_clk <= clk;
	branchC_9_rst <= rst;
	Buffer_9_pValidArray_0 <= branchC_9_validArray_0;
	branchC_9_nReadyArray_0 <= Buffer_9_readyArray_0;
	Buffer_9_dataInArray_0 <= std_logic_vector (resize(unsigned(branchC_9_dataOutArray_0),Buffer_9_dataInArray_0'length));
	sink_8_pValidArray_0 <= branchC_9_validArray_1;
	branchC_9_nReadyArray_1 <= sink_8_readyArray_0;
	sink_8_dataInArray_0 <= std_logic_vector (resize(unsigned(branchC_9_dataOutArray_1),sink_8_dataInArray_0'length));

	Buffer_3_clk <= clk;
	Buffer_3_rst <= rst;
	phi_12_pValidArray_1 <= Buffer_3_validArray_0;
	Buffer_3_nReadyArray_0 <= phi_12_readyArray_1;
	phi_12_dataInArray_1 <= std_logic_vector (resize(unsigned(Buffer_3_dataOutArray_0),phi_12_dataInArray_1'length));

	Buffer_4_clk <= clk;
	Buffer_4_rst <= rst;
	phi_13_pValidArray_1 <= Buffer_4_validArray_0;
	Buffer_4_nReadyArray_0 <= phi_13_readyArray_1;
	phi_13_dataInArray_1 <= std_logic_vector (resize(unsigned(Buffer_4_dataOutArray_0),phi_13_dataInArray_1'length));

	Buffer_9_clk <= clk;
	Buffer_9_rst <= rst;
	phiC_5_pValidArray_0 <= Buffer_9_validArray_0;
	Buffer_9_nReadyArray_0 <= phiC_5_readyArray_0;
	phiC_5_dataInArray_0 <= std_logic_vector (resize(unsigned(Buffer_9_dataOutArray_0),phiC_5_dataInArray_0'length));

	phi_12_clk <= clk;
	phi_12_rst <= rst;
	Buffer_1_pValidArray_0 <= phi_12_validArray_0;
	phi_12_nReadyArray_0 <= Buffer_1_readyArray_0;
	Buffer_1_dataInArray_0 <= std_logic_vector (resize(unsigned(phi_12_dataOutArray_0),Buffer_1_dataInArray_0'length));

	phi_13_clk <= clk;
	phi_13_rst <= rst;
	fork_4_pValidArray_0 <= phi_13_validArray_0;
	phi_13_nReadyArray_0 <= fork_4_readyArray_0;
	fork_4_dataInArray_0 <= std_logic_vector (resize(unsigned(phi_13_dataOutArray_0),fork_4_dataInArray_0'length));

	load_16_clk <= clk;
	load_16_rst <= rst;
	fork_5_pValidArray_0 <= load_16_validArray_0;
	load_16_nReadyArray_0 <= fork_5_readyArray_0;
	fork_5_dataInArray_0 <= std_logic_vector (resize(unsigned(load_16_dataOutArray_0),fork_5_dataInArray_0'length));
	MC_A_pValidArray_0 <= load_16_validArray_1;
	load_16_nReadyArray_1 <= MC_A_readyArray_0;
	MC_A_dataInArray_0 <= std_logic_vector (resize(unsigned(load_16_dataOutArray_1),MC_A_dataInArray_0'length));

	cst_8_clk <= clk;
	cst_8_rst <= rst;
	icmp_17_pValidArray_1 <= cst_8_validArray_0;
	cst_8_nReadyArray_0 <= icmp_17_readyArray_1;
	icmp_17_dataInArray_1 <= std_logic_vector (resize(unsigned(cst_8_dataOutArray_0),icmp_17_dataInArray_1'length));

	icmp_17_clk <= clk;
	icmp_17_rst <= rst;
	fork_9_pValidArray_0 <= icmp_17_validArray_0;
	icmp_17_nReadyArray_0 <= fork_9_readyArray_0;
	fork_9_dataInArray_0 <= std_logic_vector (resize(unsigned(icmp_17_dataOutArray_0),fork_9_dataInArray_0'length));

	fork_4_clk <= clk;
	fork_4_rst <= rst;
	load_16_pValidArray_1 <= fork_4_validArray_0;
	fork_4_nReadyArray_0 <= load_16_readyArray_1;
	load_16_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_4_dataOutArray_0),load_16_dataInArray_1'length));
	Buffer_2_pValidArray_0 <= fork_4_validArray_1;
	fork_4_nReadyArray_1 <= Buffer_2_readyArray_0;
	Buffer_2_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_4_dataOutArray_1),Buffer_2_dataInArray_0'length));

	fork_5_clk <= clk;
	fork_5_rst <= rst;
	icmp_17_pValidArray_0 <= fork_5_validArray_0;
	fork_5_nReadyArray_0 <= icmp_17_readyArray_0;
	icmp_17_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_5_dataOutArray_0),icmp_17_dataInArray_0'length));
	branch_4_pValidArray_0 <= fork_5_validArray_1;
	fork_5_nReadyArray_1 <= branch_4_readyArray_0;
	branch_4_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_5_dataOutArray_1),branch_4_dataInArray_0'length));

	branch_2_clk <= clk;
	branch_2_rst <= rst;
	phi_n2_pValidArray_0 <= branch_2_validArray_0;
	branch_2_nReadyArray_0 <= phi_n2_readyArray_0;
	phi_n2_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_2_dataOutArray_0),phi_n2_dataInArray_0'length));
	phi_21_pValidArray_1 <= branch_2_validArray_1;
	branch_2_nReadyArray_1 <= phi_21_readyArray_1;
	phi_21_dataInArray_1 <= std_logic_vector (resize(unsigned(branch_2_dataOutArray_1),phi_21_dataInArray_1'length));

	branch_3_clk <= clk;
	branch_3_rst <= rst;
	phi_n3_pValidArray_0 <= branch_3_validArray_0;
	branch_3_nReadyArray_0 <= phi_n3_readyArray_0;
	phi_n3_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_3_dataOutArray_0),phi_n3_dataInArray_0'length));
	phi_n0_pValidArray_0 <= branch_3_validArray_1;
	branch_3_nReadyArray_1 <= phi_n0_readyArray_0;
	phi_n0_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_3_dataOutArray_1),phi_n0_dataInArray_0'length));

	branch_4_clk <= clk;
	branch_4_rst <= rst;
	phi_n1_pValidArray_0 <= branch_4_validArray_0;
	branch_4_nReadyArray_0 <= phi_n1_readyArray_0;
	phi_n1_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_4_dataOutArray_0),phi_n1_dataInArray_0'length));
	sink_4_pValidArray_0 <= branch_4_validArray_1;
	branch_4_nReadyArray_1 <= sink_4_readyArray_0;
	sink_4_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_4_dataOutArray_1),sink_4_dataInArray_0'length));

	fork_9_clk <= clk;
	fork_9_rst <= rst;
	branch_4_pValidArray_1 <= fork_9_validArray_0;
	fork_9_nReadyArray_0 <= branch_4_readyArray_1;
	branch_4_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_9_dataOutArray_0),branch_4_dataInArray_1'length));
	branch_3_pValidArray_1 <= fork_9_validArray_1;
	fork_9_nReadyArray_1 <= branch_3_readyArray_1;
	branch_3_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_9_dataOutArray_1),branch_3_dataInArray_1'length));
	Buffer_5_pValidArray_0 <= fork_9_validArray_2;
	fork_9_nReadyArray_2 <= Buffer_5_readyArray_0;
	Buffer_5_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_9_dataOutArray_2),Buffer_5_dataInArray_0'length));
	branchC_10_pValidArray_1 <= fork_9_validArray_3;
	fork_9_nReadyArray_3 <= branchC_10_readyArray_1;
	branchC_10_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_9_dataOutArray_3),branchC_10_dataInArray_1'length));

	phiC_5_clk <= clk;
	phiC_5_rst <= rst;
	Buffer_10_pValidArray_0 <= phiC_5_validArray_0;
	phiC_5_nReadyArray_0 <= Buffer_10_readyArray_0;
	Buffer_10_dataInArray_0 <= std_logic_vector (resize(unsigned(phiC_5_dataOutArray_0),Buffer_10_dataInArray_0'length));
	fork_18_pValidArray_0 <= phiC_5_validArray_1;
	phiC_5_nReadyArray_1 <= fork_18_readyArray_0;
	fork_18_dataInArray_0 <= std_logic_vector (resize(unsigned(phiC_5_dataOutArray_1),fork_18_dataInArray_0'length));

	branchC_10_clk <= clk;
	branchC_10_rst <= rst;
	phiC_6_pValidArray_0 <= branchC_10_validArray_0;
	branchC_10_nReadyArray_0 <= phiC_6_readyArray_0;
	phiC_6_dataInArray_0 <= std_logic_vector (resize(unsigned(branchC_10_dataOutArray_0),phiC_6_dataInArray_0'length));
	phiC_7_pValidArray_0 <= branchC_10_validArray_1;
	branchC_10_nReadyArray_1 <= phiC_7_readyArray_0;
	phiC_7_dataInArray_0 <= std_logic_vector (resize(unsigned(branchC_10_dataOutArray_1),phiC_7_dataInArray_0'length));

	source_6_clk <= clk;
	source_6_rst <= rst;
	cst_8_pValidArray_0 <= source_6_validArray_0;
	source_6_nReadyArray_0 <= cst_8_readyArray_0;
	cst_8_dataInArray_0 <= "00000000000000000000000000000000";

	fork_18_clk <= clk;
	fork_18_rst <= rst;
	Buffer_13_pValidArray_0 <= fork_18_validArray_0;
	fork_18_nReadyArray_0 <= Buffer_13_readyArray_0;
	Buffer_13_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_18_dataOutArray_0),Buffer_13_dataInArray_0'length));
	phi_13_pValidArray_0 <= fork_18_validArray_1;
	fork_18_nReadyArray_1 <= phi_13_readyArray_0;
	phi_13_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_18_dataOutArray_1),phi_13_dataInArray_0'length));

	Buffer_1_clk <= clk;
	Buffer_1_rst <= rst;
	branch_2_pValidArray_0 <= Buffer_1_validArray_0;
	Buffer_1_nReadyArray_0 <= branch_2_readyArray_0;
	branch_2_dataInArray_0 <= std_logic_vector (resize(unsigned(Buffer_1_dataOutArray_0),branch_2_dataInArray_0'length));

	Buffer_2_clk <= clk;
	Buffer_2_rst <= rst;
	branch_3_pValidArray_0 <= Buffer_2_validArray_0;
	Buffer_2_nReadyArray_0 <= branch_3_readyArray_0;
	branch_3_dataInArray_0 <= std_logic_vector (resize(unsigned(Buffer_2_dataOutArray_0),branch_3_dataInArray_0'length));

	Buffer_5_clk <= clk;
	Buffer_5_rst <= rst;
	branch_2_pValidArray_1 <= Buffer_5_validArray_0;
	Buffer_5_nReadyArray_0 <= branch_2_readyArray_1;
	branch_2_dataInArray_1 <= std_logic_vector (resize(unsigned(Buffer_5_dataOutArray_0),branch_2_dataInArray_1'length));

	Buffer_10_clk <= clk;
	Buffer_10_rst <= rst;
	branchC_10_pValidArray_0 <= Buffer_10_validArray_0;
	Buffer_10_nReadyArray_0 <= branchC_10_readyArray_0;
	branchC_10_dataInArray_0 <= std_logic_vector (resize(unsigned(Buffer_10_dataOutArray_0),branchC_10_dataInArray_0'length));

	Buffer_13_clk <= clk;
	Buffer_13_rst <= rst;
	phi_12_pValidArray_0 <= Buffer_13_validArray_0;
	Buffer_13_nReadyArray_0 <= phi_12_readyArray_0;
	phi_12_dataInArray_0 <= std_logic_vector (resize(unsigned(Buffer_13_dataOutArray_0),phi_12_dataInArray_0'length));

	call_0_clk <= clk;
	call_0_rst <= rst;
	add_19_pValidArray_1 <= call_0_validArray_0;
	call_0_nReadyArray_0 <= add_19_readyArray_1;
	add_19_dataInArray_1 <= std_logic_vector (resize(unsigned(call_0_dataOutArray_0),add_19_dataInArray_1'length));

	add_19_clk <= clk;
	add_19_rst <= rst;
	branch_5_pValidArray_0 <= add_19_validArray_0;
	add_19_nReadyArray_0 <= branch_5_readyArray_0;
	branch_5_dataInArray_0 <= std_logic_vector (resize(unsigned(add_19_dataOutArray_0),branch_5_dataInArray_0'length));

	brCst_block4_clk <= clk;
	brCst_block4_rst <= rst;
	fork_10_pValidArray_0 <= brCst_block4_validArray_0;
	brCst_block4_nReadyArray_0 <= fork_10_readyArray_0;
	fork_10_dataInArray_0 <= std_logic_vector (resize(unsigned(brCst_block4_dataOutArray_0),fork_10_dataInArray_0'length));

	phi_n1_clk <= clk;
	phi_n1_rst <= rst;
	call_0_pValidArray_0 <= phi_n1_validArray_0;
	phi_n1_nReadyArray_0 <= call_0_readyArray_0;
	call_0_dataInArray_0 <= std_logic_vector (resize(unsigned(phi_n1_dataOutArray_0),call_0_dataInArray_0'length));

	phi_n2_clk <= clk;
	phi_n2_rst <= rst;
	add_19_pValidArray_0 <= phi_n2_validArray_0;
	phi_n2_nReadyArray_0 <= add_19_readyArray_0;
	add_19_dataInArray_0 <= std_logic_vector (resize(unsigned(phi_n2_dataOutArray_0),add_19_dataInArray_0'length));

	phi_n3_clk <= clk;
	phi_n3_rst <= rst;
	branch_6_pValidArray_0 <= phi_n3_validArray_0;
	phi_n3_nReadyArray_0 <= branch_6_readyArray_0;
	branch_6_dataInArray_0 <= std_logic_vector (resize(unsigned(phi_n3_dataOutArray_0),branch_6_dataInArray_0'length));

	branch_5_clk <= clk;
	branch_5_rst <= rst;
	phi_21_pValidArray_2 <= branch_5_validArray_0;
	branch_5_nReadyArray_0 <= phi_21_readyArray_2;
	phi_21_dataInArray_2 <= std_logic_vector (resize(unsigned(branch_5_dataOutArray_0),phi_21_dataInArray_2'length));
	sink_5_pValidArray_0 <= branch_5_validArray_1;
	branch_5_nReadyArray_1 <= sink_5_readyArray_0;
	sink_5_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_5_dataOutArray_1),sink_5_dataInArray_0'length));

	branch_6_clk <= clk;
	branch_6_rst <= rst;
	phi_n0_pValidArray_1 <= branch_6_validArray_0;
	branch_6_nReadyArray_0 <= phi_n0_readyArray_1;
	phi_n0_dataInArray_1 <= std_logic_vector (resize(unsigned(branch_6_dataOutArray_0),phi_n0_dataInArray_1'length));
	sink_6_pValidArray_0 <= branch_6_validArray_1;
	branch_6_nReadyArray_1 <= sink_6_readyArray_0;
	sink_6_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_6_dataOutArray_1),sink_6_dataInArray_0'length));

	fork_10_clk <= clk;
	fork_10_rst <= rst;
	branch_6_pValidArray_1 <= fork_10_validArray_0;
	fork_10_nReadyArray_0 <= branch_6_readyArray_1;
	branch_6_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_10_dataOutArray_0),branch_6_dataInArray_1'length));
	Buffer_6_pValidArray_0 <= fork_10_validArray_1;
	fork_10_nReadyArray_1 <= Buffer_6_readyArray_0;
	Buffer_6_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_10_dataOutArray_1),Buffer_6_dataInArray_0'length));
	branchC_11_pValidArray_1 <= fork_10_validArray_2;
	fork_10_nReadyArray_2 <= branchC_11_readyArray_1;
	branchC_11_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_10_dataOutArray_2),branchC_11_dataInArray_1'length));

	phiC_6_clk <= clk;
	phiC_6_rst <= rst;
	forkC_15_pValidArray_0 <= phiC_6_validArray_0;
	phiC_6_nReadyArray_0 <= forkC_15_readyArray_0;
	forkC_15_dataInArray_0 <= std_logic_vector (resize(unsigned(phiC_6_dataOutArray_0),forkC_15_dataInArray_0'length));

	forkC_15_clk <= clk;
	forkC_15_rst <= rst;
	branchC_11_pValidArray_0 <= forkC_15_validArray_0;
	forkC_15_nReadyArray_0 <= branchC_11_readyArray_0;
	branchC_11_dataInArray_0 <= std_logic_vector (resize(unsigned(forkC_15_dataOutArray_0),branchC_11_dataInArray_0'length));
	brCst_block4_pValidArray_0 <= forkC_15_validArray_1;
	forkC_15_nReadyArray_1 <= brCst_block4_readyArray_0;
	brCst_block4_dataInArray_0 <= "1";

	branchC_11_clk <= clk;
	branchC_11_rst <= rst;
	phiC_7_pValidArray_1 <= branchC_11_validArray_0;
	branchC_11_nReadyArray_0 <= phiC_7_readyArray_1;
	phiC_7_dataInArray_1 <= std_logic_vector (resize(unsigned(branchC_11_dataOutArray_0),phiC_7_dataInArray_1'length));
	sink_9_pValidArray_0 <= branchC_11_validArray_1;
	branchC_11_nReadyArray_1 <= sink_9_readyArray_0;
	sink_9_dataInArray_0 <= std_logic_vector (resize(unsigned(branchC_11_dataOutArray_1),sink_9_dataInArray_0'length));

	Buffer_6_clk <= clk;
	Buffer_6_rst <= rst;
	branch_5_pValidArray_1 <= Buffer_6_validArray_0;
	Buffer_6_nReadyArray_0 <= branch_5_readyArray_1;
	branch_5_dataInArray_1 <= std_logic_vector (resize(unsigned(Buffer_6_dataOutArray_0),branch_5_dataInArray_1'length));

	phi_21_clk <= clk;
	phi_21_rst <= rst;
	branch_7_pValidArray_0 <= phi_21_validArray_0;
	phi_21_nReadyArray_0 <= branch_7_readyArray_0;
	branch_7_dataInArray_0 <= std_logic_vector (resize(unsigned(phi_21_dataOutArray_0),branch_7_dataInArray_0'length));

	cst_9_clk <= clk;
	cst_9_rst <= rst;
	add_22_pValidArray_1 <= cst_9_validArray_0;
	cst_9_nReadyArray_0 <= add_22_readyArray_1;
	add_22_dataInArray_1 <= std_logic_vector (resize(unsigned(cst_9_dataOutArray_0),add_22_dataInArray_1'length));

	add_22_clk <= clk;
	add_22_rst <= rst;
	fork_7_pValidArray_0 <= add_22_validArray_0;
	add_22_nReadyArray_0 <= fork_7_readyArray_0;
	fork_7_dataInArray_0 <= std_logic_vector (resize(unsigned(add_22_dataOutArray_0),fork_7_dataInArray_0'length));

	cst_10_clk <= clk;
	cst_10_rst <= rst;
	icmp_23_pValidArray_1 <= cst_10_validArray_0;
	cst_10_nReadyArray_0 <= icmp_23_readyArray_1;
	icmp_23_dataInArray_1 <= std_logic_vector (resize(unsigned(cst_10_dataOutArray_0),icmp_23_dataInArray_1'length));

	icmp_23_clk <= clk;
	icmp_23_rst <= rst;
	fork_11_pValidArray_0 <= icmp_23_validArray_0;
	icmp_23_nReadyArray_0 <= fork_11_readyArray_0;
	fork_11_dataInArray_0 <= std_logic_vector (resize(unsigned(icmp_23_dataOutArray_0),fork_11_dataInArray_0'length));

	phi_n0_clk <= clk;
	phi_n0_rst <= rst;
	add_22_pValidArray_0 <= phi_n0_validArray_0;
	phi_n0_nReadyArray_0 <= add_22_readyArray_0;
	add_22_dataInArray_0 <= std_logic_vector (resize(unsigned(phi_n0_dataOutArray_0),add_22_dataInArray_0'length));

	fork_7_clk <= clk;
	fork_7_rst <= rst;
	icmp_23_pValidArray_0 <= fork_7_validArray_0;
	fork_7_nReadyArray_0 <= icmp_23_readyArray_0;
	icmp_23_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_7_dataOutArray_0),icmp_23_dataInArray_0'length));
	branch_8_pValidArray_0 <= fork_7_validArray_1;
	fork_7_nReadyArray_1 <= branch_8_readyArray_0;
	branch_8_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_7_dataOutArray_1),branch_8_dataInArray_0'length));

	branch_7_clk <= clk;
	branch_7_rst <= rst;
	phi_12_pValidArray_2 <= branch_7_validArray_0;
	branch_7_nReadyArray_0 <= phi_12_readyArray_2;
	phi_12_dataInArray_2 <= std_logic_vector (resize(unsigned(branch_7_dataOutArray_0),phi_12_dataInArray_2'length));
	Buffer_7_pValidArray_0 <= branch_7_validArray_1;
	branch_7_nReadyArray_1 <= Buffer_7_readyArray_0;
	Buffer_7_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_7_dataOutArray_1),Buffer_7_dataInArray_0'length));

	branch_8_clk <= clk;
	branch_8_rst <= rst;
	phi_13_pValidArray_2 <= branch_8_validArray_0;
	branch_8_nReadyArray_0 <= phi_13_readyArray_2;
	phi_13_dataInArray_2 <= std_logic_vector (resize(unsigned(branch_8_dataOutArray_0),phi_13_dataInArray_2'length));
	sink_7_pValidArray_0 <= branch_8_validArray_1;
	branch_8_nReadyArray_1 <= sink_7_readyArray_0;
	sink_7_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_8_dataOutArray_1),sink_7_dataInArray_0'length));

	fork_11_clk <= clk;
	fork_11_rst <= rst;
	branch_8_pValidArray_1 <= fork_11_validArray_0;
	fork_11_nReadyArray_0 <= branch_8_readyArray_1;
	branch_8_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_11_dataOutArray_0),branch_8_dataInArray_1'length));
	Buffer_8_pValidArray_0 <= fork_11_validArray_1;
	fork_11_nReadyArray_1 <= Buffer_8_readyArray_0;
	Buffer_8_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_11_dataOutArray_1),Buffer_8_dataInArray_0'length));
	branchC_12_pValidArray_1 <= fork_11_validArray_2;
	fork_11_nReadyArray_2 <= branchC_12_readyArray_1;
	branchC_12_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_11_dataOutArray_2),branchC_12_dataInArray_1'length));

	phiC_7_clk <= clk;
	phiC_7_rst <= rst;
	branchC_12_pValidArray_0 <= phiC_7_validArray_0;
	phiC_7_nReadyArray_0 <= branchC_12_readyArray_0;
	branchC_12_dataInArray_0 <= std_logic_vector (resize(unsigned(phiC_7_dataOutArray_0),branchC_12_dataInArray_0'length));
	Buffer_11_pValidArray_0 <= phiC_7_validArray_1;
	phiC_7_nReadyArray_1 <= Buffer_11_readyArray_0;
	Buffer_11_dataInArray_0 <= std_logic_vector (resize(unsigned(phiC_7_dataOutArray_1),Buffer_11_dataInArray_0'length));

	branchC_12_clk <= clk;
	branchC_12_rst <= rst;
	phiC_5_pValidArray_1 <= branchC_12_validArray_0;
	branchC_12_nReadyArray_0 <= phiC_5_readyArray_1;
	phiC_5_dataInArray_1 <= std_logic_vector (resize(unsigned(branchC_12_dataOutArray_0),phiC_5_dataInArray_1'length));
	Buffer_12_pValidArray_0 <= branchC_12_validArray_1;
	branchC_12_nReadyArray_1 <= Buffer_12_readyArray_0;
	Buffer_12_dataInArray_0 <= std_logic_vector (resize(unsigned(branchC_12_dataOutArray_1),Buffer_12_dataInArray_0'length));

	source_7_clk <= clk;
	source_7_rst <= rst;
	cst_9_pValidArray_0 <= source_7_validArray_0;
	source_7_nReadyArray_0 <= cst_9_readyArray_0;
	cst_9_dataInArray_0 <= "00000000000000000000000000000001";

	source_8_clk <= clk;
	source_8_rst <= rst;
	cst_10_pValidArray_0 <= source_8_validArray_0;
	source_8_nReadyArray_0 <= cst_10_readyArray_0;
	cst_10_dataInArray_0 <= "00000000000000000000001111101000";

	Buffer_7_clk <= clk;
	Buffer_7_rst <= rst;
	phi_n4_pValidArray_0 <= Buffer_7_validArray_0;
	Buffer_7_nReadyArray_0 <= phi_n4_readyArray_0;
	phi_n4_dataInArray_0 <= std_logic_vector (resize(unsigned(Buffer_7_dataOutArray_0),phi_n4_dataInArray_0'length));

	Buffer_8_clk <= clk;
	Buffer_8_rst <= rst;
	branch_7_pValidArray_1 <= Buffer_8_validArray_0;
	Buffer_8_nReadyArray_0 <= branch_7_readyArray_1;
	branch_7_dataInArray_1 <= std_logic_vector (resize(unsigned(Buffer_8_dataOutArray_0),branch_7_dataInArray_1'length));

	Buffer_11_clk <= clk;
	Buffer_11_rst <= rst;
	phi_21_pValidArray_0 <= Buffer_11_validArray_0;
	Buffer_11_nReadyArray_0 <= phi_21_readyArray_0;
	phi_21_dataInArray_0 <= std_logic_vector (resize(unsigned(Buffer_11_dataOutArray_0),phi_21_dataInArray_0'length));

	Buffer_12_clk <= clk;
	Buffer_12_rst <= rst;
	phiC_8_pValidArray_0 <= Buffer_12_validArray_0;
	Buffer_12_nReadyArray_0 <= phiC_8_readyArray_0;
	phiC_8_dataInArray_0 <= std_logic_vector (resize(unsigned(Buffer_12_dataOutArray_0),phiC_8_dataInArray_0'length));

	ret_1_clk <= clk;
	ret_1_rst <= rst;
	end_0_pValidArray_1 <= ret_1_validArray_0;
	ret_1_nReadyArray_0 <= end_0_readyArray_1;
	end_0_dataInArray_1 <= std_logic_vector (resize(unsigned(ret_1_dataOutArray_0),end_0_dataInArray_1'length));

	phi_n4_clk <= clk;
	phi_n4_rst <= rst;
	ret_1_pValidArray_0 <= phi_n4_validArray_0;
	phi_n4_nReadyArray_0 <= ret_1_readyArray_0;
	ret_1_dataInArray_0 <= std_logic_vector (resize(unsigned(phi_n4_dataOutArray_0),ret_1_dataInArray_0'length));

	phiC_8_clk <= clk;
	phiC_8_rst <= rst;
	sink_1_pValidArray_0 <= phiC_8_validArray_0;
	phiC_8_nReadyArray_0 <= sink_1_readyArray_0;
	sink_1_dataInArray_0 <= std_logic_vector (resize(unsigned(phiC_8_dataOutArray_0),sink_1_dataInArray_0'length));

	MC_A_clk <= clk;
	MC_A_rst <= rst;
	A_ce0 <= MC_A_we0_ce0;
	A_we0 <= MC_A_we0_ce0;
	load_16_pValidArray_0 <= MC_A_validArray_0;
	MC_A_nReadyArray_0 <= load_16_readyArray_0;
	load_16_dataInArray_0 <= std_logic_vector (resize(unsigned(MC_A_dataOutArray_0),load_16_dataInArray_0'length));
	end_0_pValidArray_0 <= MC_A_validArray_1;
	MC_A_nReadyArray_1 <= end_0_readyArray_0;
	end_0_dataInArray_0 <= std_logic_vector (resize(unsigned(MC_A_dataOutArray_1),end_0_dataInArray_0'length));

	end_0_clk <= clk;
	end_0_rst <= rst;
	end_valid <= end_0_validArray_0;
	end_out <= end_0_dataOutArray_0;
	end_0_nReadyArray_0 <= end_ready;

	sink_1_clk <= clk;
	sink_1_rst <= rst;

	sink_2_clk <= clk;
	sink_2_rst <= rst;

	sink_3_clk <= clk;
	sink_3_rst <= rst;

	sink_4_clk <= clk;
	sink_4_rst <= rst;

	sink_5_clk <= clk;
	sink_5_rst <= rst;

	sink_6_clk <= clk;
	sink_6_rst <= rst;

	sink_7_clk <= clk;
	sink_7_rst <= rst;

	sink_8_clk <= clk;
	sink_8_rst <= rst;

	sink_9_clk <= clk;
	sink_9_rst <= rst;

brCst_block2: entity work.Const(arch) generic map (1,1,1,1)
port map (
	clk => brCst_block2_clk,
	rst => brCst_block2_rst,
	dataInArray(0) => brCst_block2_dataInArray_0,
	pValidArray(0) => brCst_block2_pValidArray_0,
	readyArray(0) => brCst_block2_readyArray_0,
	nReadyArray(0) => brCst_block2_nReadyArray_0,
	validArray(0) => brCst_block2_validArray_0,
	dataOutArray(0) => brCst_block2_dataOutArray_0
);

cst_6: entity work.Const(arch) generic map (1,1,32,32)
port map (
	clk => cst_6_clk,
	rst => cst_6_rst,
	dataInArray(0) => cst_6_dataInArray_0,
	pValidArray(0) => cst_6_pValidArray_0,
	readyArray(0) => cst_6_readyArray_0,
	nReadyArray(0) => cst_6_nReadyArray_0,
	validArray(0) => cst_6_validArray_0,
	dataOutArray(0) => cst_6_dataOutArray_0
);

cst_7: entity work.Const(arch) generic map (1,1,32,32)
port map (
	clk => cst_7_clk,
	rst => cst_7_rst,
	dataInArray(0) => cst_7_dataInArray_0,
	pValidArray(0) => cst_7_pValidArray_0,
	readyArray(0) => cst_7_readyArray_0,
	nReadyArray(0) => cst_7_nReadyArray_0,
	validArray(0) => cst_7_validArray_0,
	dataOutArray(0) => cst_7_dataOutArray_0
);

branch_0: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_0_clk,
	rst => branch_0_rst,
	dataInArray(0) => branch_0_dataInArray_0,
	Condition(0) => branch_0_dataInArray_1,
	pValidArray(0) => branch_0_pValidArray_0,
	pValidArray(1) => branch_0_pValidArray_1,
	readyArray(0) => branch_0_readyArray_0,
	readyArray(1) => branch_0_readyArray_1,
	nReadyArray(0) => branch_0_nReadyArray_0,
	nReadyArray(1) => branch_0_nReadyArray_1,
	validArray(0) => branch_0_validArray_0,
	validArray(1) => branch_0_validArray_1,
	dataOutArray(0) => branch_0_dataOutArray_0,
	dataOutArray(1) => branch_0_dataOutArray_1
);

branch_1: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_1_clk,
	rst => branch_1_rst,
	dataInArray(0) => branch_1_dataInArray_0,
	Condition(0) => branch_1_dataInArray_1,
	pValidArray(0) => branch_1_pValidArray_0,
	pValidArray(1) => branch_1_pValidArray_1,
	readyArray(0) => branch_1_readyArray_0,
	readyArray(1) => branch_1_readyArray_1,
	nReadyArray(0) => branch_1_nReadyArray_0,
	nReadyArray(1) => branch_1_nReadyArray_1,
	validArray(0) => branch_1_validArray_0,
	validArray(1) => branch_1_validArray_1,
	dataOutArray(0) => branch_1_dataOutArray_0,
	dataOutArray(1) => branch_1_dataOutArray_1
);

fork_8: entity work.fork(arch) generic map (1,3,1,1)
port map (
	clk => fork_8_clk,
	rst => fork_8_rst,
	dataInArray(0) => fork_8_dataInArray_0,
	pValidArray(0) => fork_8_pValidArray_0,
	readyArray(0) => fork_8_readyArray_0,
	nReadyArray(0) => fork_8_nReadyArray_0,
	nReadyArray(1) => fork_8_nReadyArray_1,
	nReadyArray(2) => fork_8_nReadyArray_2,
	validArray(0) => fork_8_validArray_0,
	validArray(1) => fork_8_validArray_1,
	validArray(2) => fork_8_validArray_2,
	dataOutArray(0) => fork_8_dataOutArray_0,
	dataOutArray(1) => fork_8_dataOutArray_1,
	dataOutArray(2) => fork_8_dataOutArray_2
);

start_1: entity work.start_node(arch) generic map (1,1,1,1)
port map (
	clk => start_1_clk,
	rst => start_1_rst,
	dataInArray(0) => start_1_dataInArray_0,
	pValidArray(0) => start_1_pValidArray_0,
	readyArray(0) => start_1_readyArray_0,
	nReadyArray(0) => start_1_nReadyArray_0,
	validArray(0) => start_1_validArray_0,
	dataOutArray(0) => start_1_dataOutArray_0
);

forkC_13: entity work.fork(arch) generic map (1,4,1,1)
port map (
	clk => forkC_13_clk,
	rst => forkC_13_rst,
	dataInArray(0) => forkC_13_dataInArray_0,
	pValidArray(0) => forkC_13_pValidArray_0,
	readyArray(0) => forkC_13_readyArray_0,
	nReadyArray(0) => forkC_13_nReadyArray_0,
	nReadyArray(1) => forkC_13_nReadyArray_1,
	nReadyArray(2) => forkC_13_nReadyArray_2,
	nReadyArray(3) => forkC_13_nReadyArray_3,
	validArray(0) => forkC_13_validArray_0,
	validArray(1) => forkC_13_validArray_1,
	validArray(2) => forkC_13_validArray_2,
	validArray(3) => forkC_13_validArray_3,
	dataOutArray(0) => forkC_13_dataOutArray_0,
	dataOutArray(1) => forkC_13_dataOutArray_1,
	dataOutArray(2) => forkC_13_dataOutArray_2,
	dataOutArray(3) => forkC_13_dataOutArray_3
);

branchC_9: entity work.Branch(arch) generic map (2,2,1,1)
port map (
	clk => branchC_9_clk,
	rst => branchC_9_rst,
	dataInArray(0) => branchC_9_dataInArray_0,
	Condition(0) => branchC_9_dataInArray_1,
	pValidArray(0) => branchC_9_pValidArray_0,
	pValidArray(1) => branchC_9_pValidArray_1,
	readyArray(0) => branchC_9_readyArray_0,
	readyArray(1) => branchC_9_readyArray_1,
	nReadyArray(0) => branchC_9_nReadyArray_0,
	nReadyArray(1) => branchC_9_nReadyArray_1,
	validArray(0) => branchC_9_validArray_0,
	validArray(1) => branchC_9_validArray_1,
	dataOutArray(0) => branchC_9_dataOutArray_0,
	dataOutArray(1) => branchC_9_dataOutArray_1
);

Buffer_3: entity work.elasticBuffer(arch) generic map (1,1,32,32)
port map (
	clk => Buffer_3_clk,
	rst => Buffer_3_rst,
	dataInArray(0) => Buffer_3_dataInArray_0,
	pValidArray(0) => Buffer_3_pValidArray_0,
	readyArray(0) => Buffer_3_readyArray_0,
	nReadyArray(0) => Buffer_3_nReadyArray_0,
	validArray(0) => Buffer_3_validArray_0,
	dataOutArray(0) => Buffer_3_dataOutArray_0
);

Buffer_4: entity work.elasticBuffer(arch) generic map (1,1,32,32)
port map (
	clk => Buffer_4_clk,
	rst => Buffer_4_rst,
	dataInArray(0) => Buffer_4_dataInArray_0,
	pValidArray(0) => Buffer_4_pValidArray_0,
	readyArray(0) => Buffer_4_readyArray_0,
	nReadyArray(0) => Buffer_4_nReadyArray_0,
	validArray(0) => Buffer_4_validArray_0,
	dataOutArray(0) => Buffer_4_dataOutArray_0
);

Buffer_9: entity work.elasticBuffer(arch) generic map (1,1,1,1)
port map (
	clk => Buffer_9_clk,
	rst => Buffer_9_rst,
	dataInArray(0) => Buffer_9_dataInArray_0,
	pValidArray(0) => Buffer_9_pValidArray_0,
	readyArray(0) => Buffer_9_readyArray_0,
	nReadyArray(0) => Buffer_9_nReadyArray_0,
	validArray(0) => Buffer_9_validArray_0,
	dataOutArray(0) => Buffer_9_dataOutArray_0
);

phi_12: entity work.Mux(arch) generic map (3,1,32,32,1)
port map (
	clk => phi_12_clk,
	rst => phi_12_rst,
	Condition(0) => phi_12_dataInArray_0,
	dataInArray(0) => phi_12_dataInArray_1,
	dataInArray(1) => phi_12_dataInArray_2,
	pValidArray(0) => phi_12_pValidArray_0,
	pValidArray(1) => phi_12_pValidArray_1,
	pValidArray(2) => phi_12_pValidArray_2,
	readyArray(0) => phi_12_readyArray_0,
	readyArray(1) => phi_12_readyArray_1,
	readyArray(2) => phi_12_readyArray_2,
	nReadyArray(0) => phi_12_nReadyArray_0,
	validArray(0) => phi_12_validArray_0,
	dataOutArray(0) => phi_12_dataOutArray_0
);

phi_13: entity work.Mux(arch) generic map (3,1,32,32,1)
port map (
	clk => phi_13_clk,
	rst => phi_13_rst,
	Condition(0) => phi_13_dataInArray_0,
	dataInArray(0) => phi_13_dataInArray_1,
	dataInArray(1) => phi_13_dataInArray_2,
	pValidArray(0) => phi_13_pValidArray_0,
	pValidArray(1) => phi_13_pValidArray_1,
	pValidArray(2) => phi_13_pValidArray_2,
	readyArray(0) => phi_13_readyArray_0,
	readyArray(1) => phi_13_readyArray_1,
	readyArray(2) => phi_13_readyArray_2,
	nReadyArray(0) => phi_13_nReadyArray_0,
	validArray(0) => phi_13_validArray_0,
	dataOutArray(0) => phi_13_dataOutArray_0
);

load_16: entity work.mc_load_op(arch) generic map (2,2,32,32)
port map (
	clk => load_16_clk,
	rst => load_16_rst,
	dataInArray(0) => load_16_dataInArray_0,
	input_addr => load_16_dataInArray_1,
	pValidArray(0) => load_16_pValidArray_0,
	pValidArray(1) => load_16_pValidArray_1,
	readyArray(0) => load_16_readyArray_0,
	readyArray(1) => load_16_readyArray_1,
	nReadyArray(0) => load_16_nReadyArray_0,
	nReadyArray(1) => load_16_nReadyArray_1,
	validArray(0) => load_16_validArray_0,
	validArray(1) => load_16_validArray_1,
	dataOutArray(0) => load_16_dataOutArray_0,
	output_addr => load_16_dataOutArray_1
);

cst_8: entity work.Const(arch) generic map (1,1,32,32)
port map (
	clk => cst_8_clk,
	rst => cst_8_rst,
	dataInArray(0) => cst_8_dataInArray_0,
	pValidArray(0) => cst_8_pValidArray_0,
	readyArray(0) => cst_8_readyArray_0,
	nReadyArray(0) => cst_8_nReadyArray_0,
	validArray(0) => cst_8_validArray_0,
	dataOutArray(0) => cst_8_dataOutArray_0
);

icmp_17: entity work.icmp_sgt_op(arch) generic map (2,1,32,1)
port map (
	clk => icmp_17_clk,
	rst => icmp_17_rst,
	dataInArray(0) => icmp_17_dataInArray_0,
	dataInArray(1) => icmp_17_dataInArray_1,
	pValidArray(0) => icmp_17_pValidArray_0,
	pValidArray(1) => icmp_17_pValidArray_1,
	readyArray(0) => icmp_17_readyArray_0,
	readyArray(1) => icmp_17_readyArray_1,
	nReadyArray(0) => icmp_17_nReadyArray_0,
	validArray(0) => icmp_17_validArray_0,
	dataOutArray(0) => icmp_17_dataOutArray_0
);

fork_4: entity work.fork(arch) generic map (1,2,32,32)
port map (
	clk => fork_4_clk,
	rst => fork_4_rst,
	dataInArray(0) => fork_4_dataInArray_0,
	pValidArray(0) => fork_4_pValidArray_0,
	readyArray(0) => fork_4_readyArray_0,
	nReadyArray(0) => fork_4_nReadyArray_0,
	nReadyArray(1) => fork_4_nReadyArray_1,
	validArray(0) => fork_4_validArray_0,
	validArray(1) => fork_4_validArray_1,
	dataOutArray(0) => fork_4_dataOutArray_0,
	dataOutArray(1) => fork_4_dataOutArray_1
);

fork_5: entity work.fork(arch) generic map (1,2,32,32)
port map (
	clk => fork_5_clk,
	rst => fork_5_rst,
	dataInArray(0) => fork_5_dataInArray_0,
	pValidArray(0) => fork_5_pValidArray_0,
	readyArray(0) => fork_5_readyArray_0,
	nReadyArray(0) => fork_5_nReadyArray_0,
	nReadyArray(1) => fork_5_nReadyArray_1,
	validArray(0) => fork_5_validArray_0,
	validArray(1) => fork_5_validArray_1,
	dataOutArray(0) => fork_5_dataOutArray_0,
	dataOutArray(1) => fork_5_dataOutArray_1
);

branch_2: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_2_clk,
	rst => branch_2_rst,
	dataInArray(0) => branch_2_dataInArray_0,
	Condition(0) => branch_2_dataInArray_1,
	pValidArray(0) => branch_2_pValidArray_0,
	pValidArray(1) => branch_2_pValidArray_1,
	readyArray(0) => branch_2_readyArray_0,
	readyArray(1) => branch_2_readyArray_1,
	nReadyArray(0) => branch_2_nReadyArray_0,
	nReadyArray(1) => branch_2_nReadyArray_1,
	validArray(0) => branch_2_validArray_0,
	validArray(1) => branch_2_validArray_1,
	dataOutArray(0) => branch_2_dataOutArray_0,
	dataOutArray(1) => branch_2_dataOutArray_1
);

branch_3: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_3_clk,
	rst => branch_3_rst,
	dataInArray(0) => branch_3_dataInArray_0,
	Condition(0) => branch_3_dataInArray_1,
	pValidArray(0) => branch_3_pValidArray_0,
	pValidArray(1) => branch_3_pValidArray_1,
	readyArray(0) => branch_3_readyArray_0,
	readyArray(1) => branch_3_readyArray_1,
	nReadyArray(0) => branch_3_nReadyArray_0,
	nReadyArray(1) => branch_3_nReadyArray_1,
	validArray(0) => branch_3_validArray_0,
	validArray(1) => branch_3_validArray_1,
	dataOutArray(0) => branch_3_dataOutArray_0,
	dataOutArray(1) => branch_3_dataOutArray_1
);

branch_4: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_4_clk,
	rst => branch_4_rst,
	dataInArray(0) => branch_4_dataInArray_0,
	Condition(0) => branch_4_dataInArray_1,
	pValidArray(0) => branch_4_pValidArray_0,
	pValidArray(1) => branch_4_pValidArray_1,
	readyArray(0) => branch_4_readyArray_0,
	readyArray(1) => branch_4_readyArray_1,
	nReadyArray(0) => branch_4_nReadyArray_0,
	nReadyArray(1) => branch_4_nReadyArray_1,
	validArray(0) => branch_4_validArray_0,
	validArray(1) => branch_4_validArray_1,
	dataOutArray(0) => branch_4_dataOutArray_0,
	dataOutArray(1) => branch_4_dataOutArray_1
);

fork_9: entity work.fork(arch) generic map (1,4,1,1)
port map (
	clk => fork_9_clk,
	rst => fork_9_rst,
	dataInArray(0) => fork_9_dataInArray_0,
	pValidArray(0) => fork_9_pValidArray_0,
	readyArray(0) => fork_9_readyArray_0,
	nReadyArray(0) => fork_9_nReadyArray_0,
	nReadyArray(1) => fork_9_nReadyArray_1,
	nReadyArray(2) => fork_9_nReadyArray_2,
	nReadyArray(3) => fork_9_nReadyArray_3,
	validArray(0) => fork_9_validArray_0,
	validArray(1) => fork_9_validArray_1,
	validArray(2) => fork_9_validArray_2,
	validArray(3) => fork_9_validArray_3,
	dataOutArray(0) => fork_9_dataOutArray_0,
	dataOutArray(1) => fork_9_dataOutArray_1,
	dataOutArray(2) => fork_9_dataOutArray_2,
	dataOutArray(3) => fork_9_dataOutArray_3
);

phiC_5: entity work.CntrlMerge(arch) generic map (2,2,1,1,1)
port map (
	clk => phiC_5_clk,
	rst => phiC_5_rst,
	dataInArray(0) => phiC_5_dataInArray_0,
	dataInArray(1) => phiC_5_dataInArray_1,
	pValidArray(0) => phiC_5_pValidArray_0,
	pValidArray(1) => phiC_5_pValidArray_1,
	readyArray(0) => phiC_5_readyArray_0,
	readyArray(1) => phiC_5_readyArray_1,
	nReadyArray(0) => phiC_5_nReadyArray_0,
	nReadyArray(1) => phiC_5_nReadyArray_1,
	validArray(0) => phiC_5_validArray_0,
	validArray(1) => phiC_5_validArray_1,
	dataOutArray(0) => phiC_5_dataOutArray_0,
	Condition(0) => phiC_5_dataOutArray_1
);

branchC_10: entity work.Branch(arch) generic map (2,2,1,1)
port map (
	clk => branchC_10_clk,
	rst => branchC_10_rst,
	dataInArray(0) => branchC_10_dataInArray_0,
	Condition(0) => branchC_10_dataInArray_1,
	pValidArray(0) => branchC_10_pValidArray_0,
	pValidArray(1) => branchC_10_pValidArray_1,
	readyArray(0) => branchC_10_readyArray_0,
	readyArray(1) => branchC_10_readyArray_1,
	nReadyArray(0) => branchC_10_nReadyArray_0,
	nReadyArray(1) => branchC_10_nReadyArray_1,
	validArray(0) => branchC_10_validArray_0,
	validArray(1) => branchC_10_validArray_1,
	dataOutArray(0) => branchC_10_dataOutArray_0,
	dataOutArray(1) => branchC_10_dataOutArray_1
);

source_6: entity work.source(arch) generic map (0,1,32,32)
port map (
	clk => source_6_clk,
	rst => source_6_rst,
	nReadyArray(0) => source_6_nReadyArray_0,
	validArray(0) => source_6_validArray_0,
	dataOutArray(0) => source_6_dataOutArray_0
);

fork_18: entity work.fork(arch) generic map (1,2,1,1)
port map (
	clk => fork_18_clk,
	rst => fork_18_rst,
	dataInArray(0) => fork_18_dataInArray_0,
	pValidArray(0) => fork_18_pValidArray_0,
	readyArray(0) => fork_18_readyArray_0,
	nReadyArray(0) => fork_18_nReadyArray_0,
	nReadyArray(1) => fork_18_nReadyArray_1,
	validArray(0) => fork_18_validArray_0,
	validArray(1) => fork_18_validArray_1,
	dataOutArray(0) => fork_18_dataOutArray_0,
	dataOutArray(1) => fork_18_dataOutArray_1
);

Buffer_1: entity work.elasticBuffer(arch) generic map (1,1,32,32)
port map (
	clk => Buffer_1_clk,
	rst => Buffer_1_rst,
	dataInArray(0) => Buffer_1_dataInArray_0,
	pValidArray(0) => Buffer_1_pValidArray_0,
	readyArray(0) => Buffer_1_readyArray_0,
	nReadyArray(0) => Buffer_1_nReadyArray_0,
	validArray(0) => Buffer_1_validArray_0,
	dataOutArray(0) => Buffer_1_dataOutArray_0
);

Buffer_2: entity work.elasticBuffer(arch) generic map (1,1,32,32)
port map (
	clk => Buffer_2_clk,
	rst => Buffer_2_rst,
	dataInArray(0) => Buffer_2_dataInArray_0,
	pValidArray(0) => Buffer_2_pValidArray_0,
	readyArray(0) => Buffer_2_readyArray_0,
	nReadyArray(0) => Buffer_2_nReadyArray_0,
	validArray(0) => Buffer_2_validArray_0,
	dataOutArray(0) => Buffer_2_dataOutArray_0
);

Buffer_5: entity work.elasticBuffer(arch) generic map (1,1,1,1)
port map (
	clk => Buffer_5_clk,
	rst => Buffer_5_rst,
	dataInArray(0) => Buffer_5_dataInArray_0,
	pValidArray(0) => Buffer_5_pValidArray_0,
	readyArray(0) => Buffer_5_readyArray_0,
	nReadyArray(0) => Buffer_5_nReadyArray_0,
	validArray(0) => Buffer_5_validArray_0,
	dataOutArray(0) => Buffer_5_dataOutArray_0
);

Buffer_10: entity work.elasticBuffer(arch) generic map (1,1,1,1)
port map (
	clk => Buffer_10_clk,
	rst => Buffer_10_rst,
	dataInArray(0) => Buffer_10_dataInArray_0,
	pValidArray(0) => Buffer_10_pValidArray_0,
	readyArray(0) => Buffer_10_readyArray_0,
	nReadyArray(0) => Buffer_10_nReadyArray_0,
	validArray(0) => Buffer_10_validArray_0,
	dataOutArray(0) => Buffer_10_dataOutArray_0
);

Buffer_13: entity work.elasticBuffer(arch) generic map (1,1,1,1)
port map (
	clk => Buffer_13_clk,
	rst => Buffer_13_rst,
	dataInArray(0) => Buffer_13_dataInArray_0,
	pValidArray(0) => Buffer_13_pValidArray_0,
	readyArray(0) => Buffer_13_readyArray_0,
	nReadyArray(0) => Buffer_13_nReadyArray_0,
	validArray(0) => Buffer_13_validArray_0,
	dataOutArray(0) => Buffer_13_dataOutArray_0
);

call_0: entity work.ss_g(arch) generic map (1,1,32,32,10,5)
port map (
	clk => call_0_clk,
	rst => call_0_rst,
	dataInArray(0) => call_0_dataInArray_0,
	pValidArray(0) => call_0_pValidArray_0,
	readyArray(0) => call_0_readyArray_0,
	nReadyArray(0) => call_0_nReadyArray_0,
	validArray(0) => call_0_validArray_0,
	dataOutArray(0) => call_0_dataOutArray_0
);

add_19: entity work.add_op(arch) generic map (2,1,32,32)
port map (
	clk => add_19_clk,
	rst => add_19_rst,
	dataInArray(0) => add_19_dataInArray_0,
	dataInArray(1) => add_19_dataInArray_1,
	pValidArray(0) => add_19_pValidArray_0,
	pValidArray(1) => add_19_pValidArray_1,
	readyArray(0) => add_19_readyArray_0,
	readyArray(1) => add_19_readyArray_1,
	nReadyArray(0) => add_19_nReadyArray_0,
	validArray(0) => add_19_validArray_0,
	dataOutArray(0) => add_19_dataOutArray_0
);

brCst_block4: entity work.Const(arch) generic map (1,1,1,1)
port map (
	clk => brCst_block4_clk,
	rst => brCst_block4_rst,
	dataInArray(0) => brCst_block4_dataInArray_0,
	pValidArray(0) => brCst_block4_pValidArray_0,
	readyArray(0) => brCst_block4_readyArray_0,
	nReadyArray(0) => brCst_block4_nReadyArray_0,
	validArray(0) => brCst_block4_validArray_0,
	dataOutArray(0) => brCst_block4_dataOutArray_0
);

phi_n1: entity work.merge(arch) generic map (1,1,32,32)
port map (
	clk => phi_n1_clk,
	rst => phi_n1_rst,
	dataInArray(0) => phi_n1_dataInArray_0,
	pValidArray(0) => phi_n1_pValidArray_0,
	readyArray(0) => phi_n1_readyArray_0,
	nReadyArray(0) => phi_n1_nReadyArray_0,
	validArray(0) => phi_n1_validArray_0,
	dataOutArray(0) => phi_n1_dataOutArray_0
);

phi_n2: entity work.merge(arch) generic map (1,1,32,32)
port map (
	clk => phi_n2_clk,
	rst => phi_n2_rst,
	dataInArray(0) => phi_n2_dataInArray_0,
	pValidArray(0) => phi_n2_pValidArray_0,
	readyArray(0) => phi_n2_readyArray_0,
	nReadyArray(0) => phi_n2_nReadyArray_0,
	validArray(0) => phi_n2_validArray_0,
	dataOutArray(0) => phi_n2_dataOutArray_0
);

phi_n3: entity work.merge(arch) generic map (1,1,32,32)
port map (
	clk => phi_n3_clk,
	rst => phi_n3_rst,
	dataInArray(0) => phi_n3_dataInArray_0,
	pValidArray(0) => phi_n3_pValidArray_0,
	readyArray(0) => phi_n3_readyArray_0,
	nReadyArray(0) => phi_n3_nReadyArray_0,
	validArray(0) => phi_n3_validArray_0,
	dataOutArray(0) => phi_n3_dataOutArray_0
);

branch_5: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_5_clk,
	rst => branch_5_rst,
	dataInArray(0) => branch_5_dataInArray_0,
	Condition(0) => branch_5_dataInArray_1,
	pValidArray(0) => branch_5_pValidArray_0,
	pValidArray(1) => branch_5_pValidArray_1,
	readyArray(0) => branch_5_readyArray_0,
	readyArray(1) => branch_5_readyArray_1,
	nReadyArray(0) => branch_5_nReadyArray_0,
	nReadyArray(1) => branch_5_nReadyArray_1,
	validArray(0) => branch_5_validArray_0,
	validArray(1) => branch_5_validArray_1,
	dataOutArray(0) => branch_5_dataOutArray_0,
	dataOutArray(1) => branch_5_dataOutArray_1
);

branch_6: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_6_clk,
	rst => branch_6_rst,
	dataInArray(0) => branch_6_dataInArray_0,
	Condition(0) => branch_6_dataInArray_1,
	pValidArray(0) => branch_6_pValidArray_0,
	pValidArray(1) => branch_6_pValidArray_1,
	readyArray(0) => branch_6_readyArray_0,
	readyArray(1) => branch_6_readyArray_1,
	nReadyArray(0) => branch_6_nReadyArray_0,
	nReadyArray(1) => branch_6_nReadyArray_1,
	validArray(0) => branch_6_validArray_0,
	validArray(1) => branch_6_validArray_1,
	dataOutArray(0) => branch_6_dataOutArray_0,
	dataOutArray(1) => branch_6_dataOutArray_1
);

fork_10: entity work.fork(arch) generic map (1,3,1,1)
port map (
	clk => fork_10_clk,
	rst => fork_10_rst,
	dataInArray(0) => fork_10_dataInArray_0,
	pValidArray(0) => fork_10_pValidArray_0,
	readyArray(0) => fork_10_readyArray_0,
	nReadyArray(0) => fork_10_nReadyArray_0,
	nReadyArray(1) => fork_10_nReadyArray_1,
	nReadyArray(2) => fork_10_nReadyArray_2,
	validArray(0) => fork_10_validArray_0,
	validArray(1) => fork_10_validArray_1,
	validArray(2) => fork_10_validArray_2,
	dataOutArray(0) => fork_10_dataOutArray_0,
	dataOutArray(1) => fork_10_dataOutArray_1,
	dataOutArray(2) => fork_10_dataOutArray_2
);

phiC_6: entity work.merge(arch) generic map (1,1,1,1)
port map (
	clk => phiC_6_clk,
	rst => phiC_6_rst,
	dataInArray(0) => phiC_6_dataInArray_0,
	pValidArray(0) => phiC_6_pValidArray_0,
	readyArray(0) => phiC_6_readyArray_0,
	nReadyArray(0) => phiC_6_nReadyArray_0,
	validArray(0) => phiC_6_validArray_0,
	dataOutArray(0) => phiC_6_dataOutArray_0
);

forkC_15: entity work.fork(arch) generic map (1,2,1,1)
port map (
	clk => forkC_15_clk,
	rst => forkC_15_rst,
	dataInArray(0) => forkC_15_dataInArray_0,
	pValidArray(0) => forkC_15_pValidArray_0,
	readyArray(0) => forkC_15_readyArray_0,
	nReadyArray(0) => forkC_15_nReadyArray_0,
	nReadyArray(1) => forkC_15_nReadyArray_1,
	validArray(0) => forkC_15_validArray_0,
	validArray(1) => forkC_15_validArray_1,
	dataOutArray(0) => forkC_15_dataOutArray_0,
	dataOutArray(1) => forkC_15_dataOutArray_1
);

branchC_11: entity work.Branch(arch) generic map (2,2,1,1)
port map (
	clk => branchC_11_clk,
	rst => branchC_11_rst,
	dataInArray(0) => branchC_11_dataInArray_0,
	Condition(0) => branchC_11_dataInArray_1,
	pValidArray(0) => branchC_11_pValidArray_0,
	pValidArray(1) => branchC_11_pValidArray_1,
	readyArray(0) => branchC_11_readyArray_0,
	readyArray(1) => branchC_11_readyArray_1,
	nReadyArray(0) => branchC_11_nReadyArray_0,
	nReadyArray(1) => branchC_11_nReadyArray_1,
	validArray(0) => branchC_11_validArray_0,
	validArray(1) => branchC_11_validArray_1,
	dataOutArray(0) => branchC_11_dataOutArray_0,
	dataOutArray(1) => branchC_11_dataOutArray_1
);

Buffer_6: entity work.elasticBuffer(arch) generic map (1,1,1,1)
port map (
	clk => Buffer_6_clk,
	rst => Buffer_6_rst,
	dataInArray(0) => Buffer_6_dataInArray_0,
	pValidArray(0) => Buffer_6_pValidArray_0,
	readyArray(0) => Buffer_6_readyArray_0,
	nReadyArray(0) => Buffer_6_nReadyArray_0,
	validArray(0) => Buffer_6_validArray_0,
	dataOutArray(0) => Buffer_6_dataOutArray_0
);

phi_21: entity work.Mux(arch) generic map (3,1,32,32,1)
port map (
	clk => phi_21_clk,
	rst => phi_21_rst,
	Condition(0) => phi_21_dataInArray_0,
	dataInArray(0) => phi_21_dataInArray_1,
	dataInArray(1) => phi_21_dataInArray_2,
	pValidArray(0) => phi_21_pValidArray_0,
	pValidArray(1) => phi_21_pValidArray_1,
	pValidArray(2) => phi_21_pValidArray_2,
	readyArray(0) => phi_21_readyArray_0,
	readyArray(1) => phi_21_readyArray_1,
	readyArray(2) => phi_21_readyArray_2,
	nReadyArray(0) => phi_21_nReadyArray_0,
	validArray(0) => phi_21_validArray_0,
	dataOutArray(0) => phi_21_dataOutArray_0
);

cst_9: entity work.Const(arch) generic map (1,1,32,32)
port map (
	clk => cst_9_clk,
	rst => cst_9_rst,
	dataInArray(0) => cst_9_dataInArray_0,
	pValidArray(0) => cst_9_pValidArray_0,
	readyArray(0) => cst_9_readyArray_0,
	nReadyArray(0) => cst_9_nReadyArray_0,
	validArray(0) => cst_9_validArray_0,
	dataOutArray(0) => cst_9_dataOutArray_0
);

add_22: entity work.add_op(arch) generic map (2,1,32,32)
port map (
	clk => add_22_clk,
	rst => add_22_rst,
	dataInArray(0) => add_22_dataInArray_0,
	dataInArray(1) => add_22_dataInArray_1,
	pValidArray(0) => add_22_pValidArray_0,
	pValidArray(1) => add_22_pValidArray_1,
	readyArray(0) => add_22_readyArray_0,
	readyArray(1) => add_22_readyArray_1,
	nReadyArray(0) => add_22_nReadyArray_0,
	validArray(0) => add_22_validArray_0,
	dataOutArray(0) => add_22_dataOutArray_0
);

cst_10: entity work.Const(arch) generic map (1,1,32,32)
port map (
	clk => cst_10_clk,
	rst => cst_10_rst,
	dataInArray(0) => cst_10_dataInArray_0,
	pValidArray(0) => cst_10_pValidArray_0,
	readyArray(0) => cst_10_readyArray_0,
	nReadyArray(0) => cst_10_nReadyArray_0,
	validArray(0) => cst_10_validArray_0,
	dataOutArray(0) => cst_10_dataOutArray_0
);

icmp_23: entity work.icmp_ult_op(arch) generic map (2,1,32,1)
port map (
	clk => icmp_23_clk,
	rst => icmp_23_rst,
	dataInArray(0) => icmp_23_dataInArray_0,
	dataInArray(1) => icmp_23_dataInArray_1,
	pValidArray(0) => icmp_23_pValidArray_0,
	pValidArray(1) => icmp_23_pValidArray_1,
	readyArray(0) => icmp_23_readyArray_0,
	readyArray(1) => icmp_23_readyArray_1,
	nReadyArray(0) => icmp_23_nReadyArray_0,
	validArray(0) => icmp_23_validArray_0,
	dataOutArray(0) => icmp_23_dataOutArray_0
);

phi_n0: entity work.merge(arch) generic map (2,1,32,32)
port map (
	clk => phi_n0_clk,
	rst => phi_n0_rst,
	dataInArray(0) => phi_n0_dataInArray_0,
	dataInArray(1) => phi_n0_dataInArray_1,
	pValidArray(0) => phi_n0_pValidArray_0,
	pValidArray(1) => phi_n0_pValidArray_1,
	readyArray(0) => phi_n0_readyArray_0,
	readyArray(1) => phi_n0_readyArray_1,
	nReadyArray(0) => phi_n0_nReadyArray_0,
	validArray(0) => phi_n0_validArray_0,
	dataOutArray(0) => phi_n0_dataOutArray_0
);

fork_7: entity work.fork(arch) generic map (1,2,32,32)
port map (
	clk => fork_7_clk,
	rst => fork_7_rst,
	dataInArray(0) => fork_7_dataInArray_0,
	pValidArray(0) => fork_7_pValidArray_0,
	readyArray(0) => fork_7_readyArray_0,
	nReadyArray(0) => fork_7_nReadyArray_0,
	nReadyArray(1) => fork_7_nReadyArray_1,
	validArray(0) => fork_7_validArray_0,
	validArray(1) => fork_7_validArray_1,
	dataOutArray(0) => fork_7_dataOutArray_0,
	dataOutArray(1) => fork_7_dataOutArray_1
);

branch_7: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_7_clk,
	rst => branch_7_rst,
	dataInArray(0) => branch_7_dataInArray_0,
	Condition(0) => branch_7_dataInArray_1,
	pValidArray(0) => branch_7_pValidArray_0,
	pValidArray(1) => branch_7_pValidArray_1,
	readyArray(0) => branch_7_readyArray_0,
	readyArray(1) => branch_7_readyArray_1,
	nReadyArray(0) => branch_7_nReadyArray_0,
	nReadyArray(1) => branch_7_nReadyArray_1,
	validArray(0) => branch_7_validArray_0,
	validArray(1) => branch_7_validArray_1,
	dataOutArray(0) => branch_7_dataOutArray_0,
	dataOutArray(1) => branch_7_dataOutArray_1
);

branch_8: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_8_clk,
	rst => branch_8_rst,
	dataInArray(0) => branch_8_dataInArray_0,
	Condition(0) => branch_8_dataInArray_1,
	pValidArray(0) => branch_8_pValidArray_0,
	pValidArray(1) => branch_8_pValidArray_1,
	readyArray(0) => branch_8_readyArray_0,
	readyArray(1) => branch_8_readyArray_1,
	nReadyArray(0) => branch_8_nReadyArray_0,
	nReadyArray(1) => branch_8_nReadyArray_1,
	validArray(0) => branch_8_validArray_0,
	validArray(1) => branch_8_validArray_1,
	dataOutArray(0) => branch_8_dataOutArray_0,
	dataOutArray(1) => branch_8_dataOutArray_1
);

fork_11: entity work.fork(arch) generic map (1,3,1,1)
port map (
	clk => fork_11_clk,
	rst => fork_11_rst,
	dataInArray(0) => fork_11_dataInArray_0,
	pValidArray(0) => fork_11_pValidArray_0,
	readyArray(0) => fork_11_readyArray_0,
	nReadyArray(0) => fork_11_nReadyArray_0,
	nReadyArray(1) => fork_11_nReadyArray_1,
	nReadyArray(2) => fork_11_nReadyArray_2,
	validArray(0) => fork_11_validArray_0,
	validArray(1) => fork_11_validArray_1,
	validArray(2) => fork_11_validArray_2,
	dataOutArray(0) => fork_11_dataOutArray_0,
	dataOutArray(1) => fork_11_dataOutArray_1,
	dataOutArray(2) => fork_11_dataOutArray_2
);

phiC_7: entity work.CntrlMerge(arch) generic map (2,2,1,1,1)
port map (
	clk => phiC_7_clk,
	rst => phiC_7_rst,
	dataInArray(0) => phiC_7_dataInArray_0,
	dataInArray(1) => phiC_7_dataInArray_1,
	pValidArray(0) => phiC_7_pValidArray_0,
	pValidArray(1) => phiC_7_pValidArray_1,
	readyArray(0) => phiC_7_readyArray_0,
	readyArray(1) => phiC_7_readyArray_1,
	nReadyArray(0) => phiC_7_nReadyArray_0,
	nReadyArray(1) => phiC_7_nReadyArray_1,
	validArray(0) => phiC_7_validArray_0,
	validArray(1) => phiC_7_validArray_1,
	dataOutArray(0) => phiC_7_dataOutArray_0,
	Condition(0) => phiC_7_dataOutArray_1
);

branchC_12: entity work.Branch(arch) generic map (2,2,1,1)
port map (
	clk => branchC_12_clk,
	rst => branchC_12_rst,
	dataInArray(0) => branchC_12_dataInArray_0,
	Condition(0) => branchC_12_dataInArray_1,
	pValidArray(0) => branchC_12_pValidArray_0,
	pValidArray(1) => branchC_12_pValidArray_1,
	readyArray(0) => branchC_12_readyArray_0,
	readyArray(1) => branchC_12_readyArray_1,
	nReadyArray(0) => branchC_12_nReadyArray_0,
	nReadyArray(1) => branchC_12_nReadyArray_1,
	validArray(0) => branchC_12_validArray_0,
	validArray(1) => branchC_12_validArray_1,
	dataOutArray(0) => branchC_12_dataOutArray_0,
	dataOutArray(1) => branchC_12_dataOutArray_1
);

source_7: entity work.source(arch) generic map (0,1,32,32)
port map (
	clk => source_7_clk,
	rst => source_7_rst,
	nReadyArray(0) => source_7_nReadyArray_0,
	validArray(0) => source_7_validArray_0,
	dataOutArray(0) => source_7_dataOutArray_0
);

source_8: entity work.source(arch) generic map (0,1,32,32)
port map (
	clk => source_8_clk,
	rst => source_8_rst,
	nReadyArray(0) => source_8_nReadyArray_0,
	validArray(0) => source_8_validArray_0,
	dataOutArray(0) => source_8_dataOutArray_0
);

Buffer_7: entity work.elasticBuffer(arch) generic map (1,1,32,32)
port map (
	clk => Buffer_7_clk,
	rst => Buffer_7_rst,
	dataInArray(0) => Buffer_7_dataInArray_0,
	pValidArray(0) => Buffer_7_pValidArray_0,
	readyArray(0) => Buffer_7_readyArray_0,
	nReadyArray(0) => Buffer_7_nReadyArray_0,
	validArray(0) => Buffer_7_validArray_0,
	dataOutArray(0) => Buffer_7_dataOutArray_0
);

Buffer_8: entity work.elasticBuffer(arch) generic map (1,1,1,1)
port map (
	clk => Buffer_8_clk,
	rst => Buffer_8_rst,
	dataInArray(0) => Buffer_8_dataInArray_0,
	pValidArray(0) => Buffer_8_pValidArray_0,
	readyArray(0) => Buffer_8_readyArray_0,
	nReadyArray(0) => Buffer_8_nReadyArray_0,
	validArray(0) => Buffer_8_validArray_0,
	dataOutArray(0) => Buffer_8_dataOutArray_0
);

Buffer_11: entity work.elasticBuffer(arch) generic map (1,1,1,1)
port map (
	clk => Buffer_11_clk,
	rst => Buffer_11_rst,
	dataInArray(0) => Buffer_11_dataInArray_0,
	pValidArray(0) => Buffer_11_pValidArray_0,
	readyArray(0) => Buffer_11_readyArray_0,
	nReadyArray(0) => Buffer_11_nReadyArray_0,
	validArray(0) => Buffer_11_validArray_0,
	dataOutArray(0) => Buffer_11_dataOutArray_0
);

Buffer_12: entity work.elasticBuffer(arch) generic map (1,1,1,1)
port map (
	clk => Buffer_12_clk,
	rst => Buffer_12_rst,
	dataInArray(0) => Buffer_12_dataInArray_0,
	pValidArray(0) => Buffer_12_pValidArray_0,
	readyArray(0) => Buffer_12_readyArray_0,
	nReadyArray(0) => Buffer_12_nReadyArray_0,
	validArray(0) => Buffer_12_validArray_0,
	dataOutArray(0) => Buffer_12_dataOutArray_0
);

ret_1: entity work.ret_op(arch) generic map (1,1,32,32)
port map (
	clk => ret_1_clk,
	rst => ret_1_rst,
	dataInArray(0) => ret_1_dataInArray_0,
	pValidArray(0) => ret_1_pValidArray_0,
	readyArray(0) => ret_1_readyArray_0,
	nReadyArray(0) => ret_1_nReadyArray_0,
	validArray(0) => ret_1_validArray_0,
	dataOutArray(0) => ret_1_dataOutArray_0
);

phi_n4: entity work.merge(arch) generic map (1,1,32,32)
port map (
	clk => phi_n4_clk,
	rst => phi_n4_rst,
	dataInArray(0) => phi_n4_dataInArray_0,
	pValidArray(0) => phi_n4_pValidArray_0,
	readyArray(0) => phi_n4_readyArray_0,
	nReadyArray(0) => phi_n4_nReadyArray_0,
	validArray(0) => phi_n4_validArray_0,
	dataOutArray(0) => phi_n4_dataOutArray_0
);

phiC_8: entity work.merge(arch) generic map (1,1,1,1)
port map (
	clk => phiC_8_clk,
	rst => phiC_8_rst,
	dataInArray(0) => phiC_8_dataInArray_0,
	pValidArray(0) => phiC_8_pValidArray_0,
	readyArray(0) => phiC_8_readyArray_0,
	nReadyArray(0) => phiC_8_nReadyArray_0,
	validArray(0) => phiC_8_validArray_0,
	dataOutArray(0) => phiC_8_dataOutArray_0
);

MC_A: entity work.MemCont(arch) generic map (32,32,1,1,1)
port map (
	clk => MC_A_clk,
	rst => MC_A_rst,
	io_storeDataOut => A_dout0,
	io_storeAddrOut => A_address0,
	io_storeEnable => MC_A_we0_ce0,
	io_loadDataIn => A_din1,
	io_loadAddrOut => A_address1,
	io_loadEnable => A_ce1,
	io_bbReadyToPrevs(0) => MC_A_readyArray_1,
	io_bbpValids(0) => '0',
	io_bb_stCountArray(0) => x"00000000",
	io_rdPortsPrev_ready(0) => MC_A_readyArray_0,
	io_rdPortsPrev_valid(0) => MC_A_pValidArray_0,
	io_rdPortsPrev_bits(0) => MC_A_dataInArray_0,
	io_wrAddrPorts_ready(0) => MC_A_readyArray_2,
	io_wrAddrPorts_valid(0) => MC_A_pValidArray_2,
	io_wrAddrPorts_bits(0) => MC_A_dataInArray_2,
	io_wrDataPorts_ready(0) => MC_A_readyArray_3,
	io_wrDataPorts_valid(0) => MC_A_pValidArray_3,
	io_wrDataPorts_bits(0) => MC_A_dataInArray_3,
	io_rdPortsNext_ready(0) => MC_A_nReadyArray_0,
	io_rdPortsNext_valid(0) => MC_A_validArray_0,
	io_rdPortsNext_bits(0) => MC_A_dataOutArray_0,
	io_Empty_Valid => MC_A_validArray_1,
	io_Empty_Ready => MC_A_nReadyArray_1

);

end_0: entity work.end_node(arch) generic map (1,1,1,32,32)
port map (
	clk => end_0_clk,
	rst => end_0_rst,
	dataInArray(0) => end_0_dataInArray_1,
	eValidArray(0) => end_0_pValidArray_0,
	pValidArray(0) => end_0_pValidArray_1,
	eReadyArray(0) => end_0_readyArray_0,
	readyArray(0) => end_0_readyArray_1,
	dataOutArray(0) => end_0_dataOutArray_0,
	validArray(0) => end_0_validArray_0,
	nReadyArray(0) => end_0_nReadyArray_0
);

sink_1: entity work.sink(arch) generic map (1,0,1,32)
port map (
	clk => sink_1_clk,
	rst => sink_1_rst,
	dataInArray(0) => sink_1_dataInArray_0,
	pValidArray(0) => sink_1_pValidArray_0,
	readyArray(0) => sink_1_readyArray_0
);

sink_2: entity work.sink(arch) generic map (1,0,32,32)
port map (
	clk => sink_2_clk,
	rst => sink_2_rst,
	dataInArray(0) => sink_2_dataInArray_0,
	pValidArray(0) => sink_2_pValidArray_0,
	readyArray(0) => sink_2_readyArray_0
);

sink_3: entity work.sink(arch) generic map (1,0,32,32)
port map (
	clk => sink_3_clk,
	rst => sink_3_rst,
	dataInArray(0) => sink_3_dataInArray_0,
	pValidArray(0) => sink_3_pValidArray_0,
	readyArray(0) => sink_3_readyArray_0
);

sink_4: entity work.sink(arch) generic map (1,0,32,32)
port map (
	clk => sink_4_clk,
	rst => sink_4_rst,
	dataInArray(0) => sink_4_dataInArray_0,
	pValidArray(0) => sink_4_pValidArray_0,
	readyArray(0) => sink_4_readyArray_0
);

sink_5: entity work.sink(arch) generic map (1,0,32,32)
port map (
	clk => sink_5_clk,
	rst => sink_5_rst,
	dataInArray(0) => sink_5_dataInArray_0,
	pValidArray(0) => sink_5_pValidArray_0,
	readyArray(0) => sink_5_readyArray_0
);

sink_6: entity work.sink(arch) generic map (1,0,32,32)
port map (
	clk => sink_6_clk,
	rst => sink_6_rst,
	dataInArray(0) => sink_6_dataInArray_0,
	pValidArray(0) => sink_6_pValidArray_0,
	readyArray(0) => sink_6_readyArray_0
);

sink_7: entity work.sink(arch) generic map (1,0,32,32)
port map (
	clk => sink_7_clk,
	rst => sink_7_rst,
	dataInArray(0) => sink_7_dataInArray_0,
	pValidArray(0) => sink_7_pValidArray_0,
	readyArray(0) => sink_7_readyArray_0
);

sink_8: entity work.sink(arch) generic map (1,0,1,32)
port map (
	clk => sink_8_clk,
	rst => sink_8_rst,
	dataInArray(0) => sink_8_dataInArray_0,
	pValidArray(0) => sink_8_pValidArray_0,
	readyArray(0) => sink_8_readyArray_0
);

sink_9: entity work.sink(arch) generic map (1,0,1,32)
port map (
	clk => sink_9_clk,
	rst => sink_9_rst,
	dataInArray(0) => sink_9_dataInArray_0,
	pValidArray(0) => sink_9_pValidArray_0,
	readyArray(0) => sink_9_readyArray_0
);

end behavioral; 
